import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminForApi } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { logAdminAction } from "@/lib/admin/audit";
import { toSafeErrorRecord } from "@/lib/logging/safe-error";

const schedulerSchema = z.object({
  periodStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  periodEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  currency: z.string().length(3).default("USD"),
  dryRun: z.boolean().default(false),
});

function previousMonthPeriod() {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = now.getUTCMonth(); // 0-11
  const start = new Date(Date.UTC(year, month - 1, 1));
  const end = new Date(Date.UTC(year, month, 0));
  return {
    periodStart: start.toISOString().slice(0, 10),
    periodEnd: end.toISOString().slice(0, 10),
    label: `${start.toISOString().slice(0, 7)} partner payouts`,
  };
}

export async function POST(request: Request) {
  const auth = await requireAdminForApi();
  if (!auth.isAuthorized) return auth.response;

  const body = await request.json().catch(() => ({}));
  const parsed = schedulerSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid payload", details: parsed.error.flatten() }, { status: 400 });
  }

  const defaults = previousMonthPeriod();
  const periodStart = parsed.data.periodStart ?? defaults.periodStart;
  const periodEnd = parsed.data.periodEnd ?? defaults.periodEnd;
  const currency = parsed.data.currency.toUpperCase();
  const batchName = `${periodStart} to ${periodEnd} partner payouts (${currency})`;

  const admin = createSupabaseAdminClient();
  const { data: events, error: eventsError } = await admin
    .from("partner_commission_events")
    .select("id, partner_id, net_amount_cents, available_at")
    .eq("status", "approved")
    .is("payout_item_id", null)
    .lte("available_at", `${periodEnd}T23:59:59.999Z`)
    .order("available_at", { ascending: true })
    .limit(20000);

  if (eventsError) {
    console.error("Unexpected API error.", toSafeErrorRecord(eventsError));
    return NextResponse.json({ error: "Failed to load eligible commission events." }, { status: 500 });
  }

  const eligibleCount = (events ?? []).length;
  const totalEligibleCents = (events ?? []).reduce((acc, row) => acc + Number(row.net_amount_cents ?? 0), 0);
  if (eligibleCount === 0) {
    return NextResponse.json({
      success: true,
      dryRun: parsed.data.dryRun,
      summary: {
        periodStart,
        periodEnd,
        eligibleCount: 0,
        totalEligibleCents: 0,
      },
    });
  }

  if (parsed.data.dryRun) {
    return NextResponse.json({
      success: true,
      dryRun: true,
      summary: {
        periodStart,
        periodEnd,
        eligibleCount,
        totalEligibleCents,
      },
    });
  }

  // Delegate detailed compliance gating and item linking to the existing payout batch builder route.
  const requestLike = new Request("http://internal/api/admin/partners/payouts", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      batchName,
      periodStart,
      periodEnd,
      currency,
      notes: "Generated by scheduler run endpoint.",
      metadata: {
        scheduled: true,
      },
    }),
  });

  const payoutRouteModule = await import("@/app/api/admin/partners/payouts/route");
  const response = await payoutRouteModule.POST(requestLike);
  const payload = (await response.json().catch(() => ({}))) as Record<string, unknown>;

  await logAdminAction({
    adminUserId: auth.userId,
    actionType: "partner_payout_scheduler_run",
    metadata: {
      periodStart,
      periodEnd,
      eligibleCount,
      totalEligibleCents,
      delegatedStatus: response.status,
    },
  });

  return NextResponse.json({
    success: response.ok,
    schedulerSummary: {
      periodStart,
      periodEnd,
      eligibleCount,
      totalEligibleCents,
    },
    delegatedResponse: payload,
  });
}
