/* -------------------------------------------------------------------------- */
/*  Koydo 300-Game Catalog — Part 4: Logic, Language, Creative              */
/*  75 game definitions (IDs 226–300)                                        */
/* -------------------------------------------------------------------------- */
import type { GameDefinition } from "../types";

const P = ["#fbbf24", "#f472b6", "#34d399", "#60a5fa", "#a78bfa"] as const;

export const CATALOG_PART4: GameDefinition[] = [
  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  LOGIC (226-250)                                                       */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "log-pattern-226", title: "Logic Patterns", description: "Complete complex logical pattern sequences", icon: "🧩", gradient: "from-indigo-400 to-blue-500", category: "logic", mechanic: "pattern-complete", ages: { min: 7, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logical-reasoning", palette: P, mascotId: "kody", contentKey: "log-pattern" } },
  { id: "log-maze-227", title: "Logic Maze", description: "Solve logic puzzles to unlock maze pathways", icon: "🔮", gradient: "from-violet-400 to-purple-500", category: "logic", mechanic: "maze-runner", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "deduction", palette: P, mascotId: "sparkle", contentKey: "log-maze" } },
  { id: "log-sort-228", title: "Category Sort", description: "Sort items using logical classification rules", icon: "📋", gradient: "from-emerald-400 to-teal-500", category: "logic", mechanic: "drag-sort", ages: { min: 6, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "classification", palette: P, mascotId: "nova", contentKey: "log-classify" } },
  { id: "log-quiz-229", title: "Brain Teaser Blitz", description: "Solve brain teasers and riddles at top speed", icon: "⚡", gradient: "from-amber-400 to-orange-500", category: "logic", mechanic: "quiz-race", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "puzzles", palette: P, mascotId: "ziggy", contentKey: "log-brainteaser" } },
  { id: "log-memory-230", title: "Opposite Match", description: "Flip cards to match logical opposites", icon: "🧠", gradient: "from-sky-400 to-blue-500", category: "logic", mechanic: "memory-flip", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "opposites", palette: P, mascotId: "pixel", contentKey: "log-opposites" } },
  { id: "log-sequence-231", title: "Logic Chain", description: "Remember and repeat increasingly complex logical chains", icon: "🔗", gradient: "from-pink-400 to-rose-500", category: "logic", mechanic: "sequence-recall", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sequential-logic", palette: P, mascotId: "blaze", contentKey: "log-chain" } },
  { id: "log-slide-232", title: "Sudoku Slide", description: "Slide number tiles to solve Sudoku-style logic puzzles", icon: "🔢", gradient: "from-lime-400 to-green-500", category: "logic", mechanic: "slide-puzzle", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sudoku", palette: P, mascotId: "luna", contentKey: "log-sudoku" } },
  { id: "log-jigsaw-233", title: "Tangram Puzzle", description: "Arrange tangram pieces to form target shapes", icon: "📐", gradient: "from-fuchsia-400 to-pink-500", category: "logic", mechanic: "jigsaw", ages: { min: 6, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spatial-reasoning", palette: P, mascotId: "hero", contentKey: "log-tangram" } },
  { id: "log-code-234", title: "Logic Gate Coder", description: "Program logic gates to produce correct outputs", icon: "💻", gradient: "from-cyan-400 to-sky-500", category: "logic", mechanic: "coding-blocks", ages: { min: 9, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "boolean-logic", palette: P, mascotId: "dash", contentKey: "log-gates" } },
  { id: "log-balance-235", title: "Equation Logic", description: "Balance logical equations with truth values", icon: "⚖️", gradient: "from-rose-400 to-pink-500", category: "logic", mechanic: "balance-scale", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "propositional-logic", palette: P, mascotId: "echo", contentKey: "log-truth" } },
  { id: "log-match-236", title: "Shape Logic Match", description: "Match shapes following logical rules in a gem grid", icon: "🔷", gradient: "from-indigo-400 to-blue-500", category: "logic", mechanic: "match-three", ages: { min: 5, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "patterns", palette: P, mascotId: "kody", contentKey: "log-shapes" } },
  { id: "log-tower-237", title: "Hanoi Tower", description: "Solve Tower of Hanoi with increasing discs", icon: "🏗️", gradient: "from-amber-400 to-orange-500", category: "logic", mechanic: "tower-stack", ages: { min: 7, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "recursive-logic", palette: P, mascotId: "sparkle", contentKey: "log-hanoi" } },
  { id: "log-connect-238", title: "Graph Connect", description: "Connect graph nodes following logical constraints", icon: "🔗", gradient: "from-teal-400 to-emerald-500", category: "logic", mechanic: "connect-dots", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "graph-theory", palette: P, mascotId: "nova", contentKey: "log-graph" } },
  { id: "log-word-239", title: "Logic Word Search", description: "Find logic and reasoning terms in the grid", icon: "🔍", gradient: "from-violet-400 to-purple-500", category: "logic", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-vocab", palette: P, mascotId: "ziggy", contentKey: "log-wordsearch" } },
  { id: "log-crossword-240", title: "Logic Crossword", description: "Fill in logic and reasoning vocabulary", icon: "✏️", gradient: "from-sky-400 to-blue-500", category: "logic", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-vocab", palette: P, mascotId: "pixel", contentKey: "log-cross" } },
  { id: "log-catch-241", title: "True or False Drop", description: "Catch falling true statements, avoid false ones", icon: "✅", gradient: "from-emerald-400 to-teal-500", category: "logic", mechanic: "falling-catch", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "true-false", palette: P, mascotId: "blaze", contentKey: "log-truefalse" } },
  { id: "log-runner-242", title: "Decision Runner", description: "Run making logical decisions at each fork", icon: "🏃", gradient: "from-pink-400 to-rose-500", category: "logic", mechanic: "infinite-runner", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "decision-making", palette: P, mascotId: "luna", contentKey: "log-decision" } },
  { id: "log-platform-243", title: "Puzzle Platformer", description: "Platform through logic puzzle worlds", icon: "🎮", gradient: "from-fuchsia-400 to-pink-500", category: "logic", mechanic: "platformer", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spatial-logic", palette: P, mascotId: "hero", contentKey: "log-platform" } },
  { id: "log-builder-244", title: "Bridge of Logic", description: "Build logical bridges using if-then reasoning", icon: "🌉", gradient: "from-lime-400 to-green-500", category: "logic", mechanic: "builder", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "conditional-logic", palette: P, mascotId: "dash", contentKey: "log-bridge" } },
  { id: "log-typing-245", title: "Logic Symbol Sprint", description: "Type logic symbols and operators quickly", icon: "⌨️", gradient: "from-cyan-400 to-sky-500", category: "logic", mechanic: "typing-race", ages: { min: 9, max: 16 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-notation", palette: P, mascotId: "echo", contentKey: "log-symbols" } },
  { id: "log-color-246", title: "Venn Diagram Paint", description: "Color Venn diagram regions correctly", icon: "🎨", gradient: "from-rose-400 to-pink-500", category: "logic", mechanic: "color-fill", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "set-theory", palette: P, mascotId: "kody", contentKey: "log-venn" } },
  { id: "log-explorer-247", title: "Puzzle Island", description: "Explore an island solving logic puzzles at each stop", icon: "🏝️", gradient: "from-teal-400 to-emerald-500", category: "logic", mechanic: "map-explorer", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "puzzles", palette: P, mascotId: "sparkle", contentKey: "log-island" } },
  { id: "log-rhythm-248", title: "Pattern Rhythm", description: "Tap logical patterns to a rhythmic beat", icon: "🎵", gradient: "from-indigo-400 to-blue-500", category: "logic", mechanic: "rhythm-tap", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "rhythmic-patterns", palette: P, mascotId: "nova", contentKey: "log-rhythm" } },
  { id: "log-timeline-249", title: "Logic Discoveries", description: "Order logic and math discoveries historically", icon: "📅", gradient: "from-amber-400 to-orange-500", category: "logic", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-history", palette: P, mascotId: "ziggy", contentKey: "log-time" } },
  { id: "log-bubble-250", title: "Logic Fact Pop", description: "Pop bubbles with logically correct statements", icon: "🫧", gradient: "from-violet-400 to-purple-500", category: "logic", mechanic: "math-pop", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-facts", palette: P, mascotId: "pixel", contentKey: "log-pop" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  LANGUAGE (251-275)                                                    */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "lang-quiz-251", title: "Language Quiz Rush", description: "Translate words between languages at top speed", icon: "⚡", gradient: "from-sky-400 to-blue-500", category: "language", mechanic: "quiz-race", ages: { min: 7, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "translation", palette: P, mascotId: "kody", contentKey: "lang-translate" } },
  { id: "lang-memory-252", title: "Translation Match", description: "Match words with their translations by flipping cards", icon: "🧠", gradient: "from-emerald-400 to-teal-500", category: "language", mechanic: "memory-flip", ages: { min: 6, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "sparkle", contentKey: "lang-vocab" } },
  { id: "lang-word-253", title: "Foreign Word Search", description: "Find foreign language words in the grid", icon: "🔍", gradient: "from-violet-400 to-purple-500", category: "language", mechanic: "word-search", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "foreign-vocab", palette: P, mascotId: "nova", contentKey: "lang-wordsearch" } },
  { id: "lang-typing-254", title: "Foreign Typing Race", description: "Type foreign language words before they vanish", icon: "⌨️", gradient: "from-amber-400 to-orange-500", category: "language", mechanic: "typing-race", ages: { min: 8, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spelling", palette: P, mascotId: "ziggy", contentKey: "lang-typing" } },
  { id: "lang-sort-255", title: "Grammar Sort", description: "Sort foreign words by their grammatical gender or type", icon: "📋", gradient: "from-pink-400 to-rose-500", category: "language", mechanic: "drag-sort", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "grammar", palette: P, mascotId: "pixel", contentKey: "lang-grammar" } },
  { id: "lang-crossword-256", title: "Language Crossword", description: "Solve crosswords with foreign language clues", icon: "✏️", gradient: "from-lime-400 to-green-500", category: "language", mechanic: "crossword", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "language-vocab", palette: P, mascotId: "blaze", contentKey: "lang-cross" } },
  { id: "lang-match-257", title: "Language Gem Match", description: "Match foreign word gems with English equivalents", icon: "💎", gradient: "from-fuchsia-400 to-pink-500", category: "language", mechanic: "match-three", ages: { min: 6, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "basic-vocab", palette: P, mascotId: "luna", contentKey: "lang-gems" } },
  { id: "lang-explorer-258", title: "Language Globe Trotter", description: "Travel the world learning phrases in local languages", icon: "🌍", gradient: "from-cyan-400 to-sky-500", category: "language", mechanic: "map-explorer", ages: { min: 7, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "travel-phrases", palette: P, mascotId: "hero", contentKey: "lang-travel" } },
  { id: "lang-sequence-259", title: "Phrase Recall", description: "Remember and repeat foreign language phrases", icon: "🔔", gradient: "from-rose-400 to-pink-500", category: "language", mechanic: "sequence-recall", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phrases", palette: P, mascotId: "dash", contentKey: "lang-phrases" } },
  { id: "lang-pattern-260", title: "Conjugation Patterns", description: "Complete verb conjugation patterns", icon: "🔁", gradient: "from-indigo-400 to-blue-500", category: "language", mechanic: "pattern-complete", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "conjugation", palette: P, mascotId: "echo", contentKey: "lang-conjugate" } },
  { id: "lang-catch-261", title: "Accent Catcher", description: "Catch words with the correct accent marks as they fall", icon: "é", gradient: "from-teal-400 to-emerald-500", category: "language", mechanic: "falling-catch", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "accents", palette: P, mascotId: "kody", contentKey: "lang-accents" } },
  { id: "lang-builder-262", title: "Sentence Constructor", description: "Build sentences in foreign languages from word blocks", icon: "🧱", gradient: "from-amber-400 to-orange-500", category: "language", mechanic: "builder", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sentence-structure", palette: P, mascotId: "sparkle", contentKey: "lang-sentence" } },
  { id: "lang-maze-263", title: "Vocabulary Maze", description: "Navigate a maze using foreign language directions", icon: "🗺️", gradient: "from-violet-400 to-purple-500", category: "language", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "directions", palette: P, mascotId: "nova", contentKey: "lang-directions" } },
  { id: "lang-jigsaw-264", title: "Culture Jigsaw", description: "Assemble cultural scene puzzles from different countries", icon: "🧩", gradient: "from-sky-400 to-blue-500", category: "language", mechanic: "jigsaw", ages: { min: 6, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "culture", palette: P, mascotId: "ziggy", contentKey: "lang-culture" } },
  { id: "lang-rhythm-265", title: "Pronunciation Rhythm", description: "Tap syllables matching correct pronunciation", icon: "🎵", gradient: "from-pink-400 to-rose-500", category: "language", mechanic: "rhythm-tap", ages: { min: 6, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "pronunciation", palette: P, mascotId: "pixel", contentKey: "lang-pronun" } },
  { id: "lang-runner-266", title: "Vocab Dash", description: "Run collecting foreign vocabulary words", icon: "🏃", gradient: "from-emerald-400 to-teal-500", category: "language", mechanic: "infinite-runner", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "blaze", contentKey: "lang-dash" } },
  { id: "lang-tower-267", title: "Word Tower Babel", description: "Stack translation blocks to build the word tower", icon: "🏗️", gradient: "from-lime-400 to-green-500", category: "language", mechanic: "tower-stack", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "words", palette: P, mascotId: "luna", contentKey: "lang-babel" } },
  { id: "lang-connect-268", title: "Language Tree Connect", description: "Connect related languages on a language tree", icon: "🌳", gradient: "from-fuchsia-400 to-pink-500", category: "language", mechanic: "connect-dots", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "linguistics", palette: P, mascotId: "hero", contentKey: "lang-tree" } },
  { id: "lang-platform-269", title: "Language Land", description: "Platform through a multilingual world collecting words", icon: "🎮", gradient: "from-cyan-400 to-sky-500", category: "language", mechanic: "platformer", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "basic-vocab", palette: P, mascotId: "dash", contentKey: "lang-land" } },
  { id: "lang-timeline-270", title: "Language Evolution", description: "Order language milestones through history", icon: "📅", gradient: "from-rose-400 to-pink-500", category: "language", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "language-history", palette: P, mascotId: "echo", contentKey: "lang-history" } },
  { id: "lang-color-271", title: "Color by Language", description: "Color images using foreign language color names", icon: "🎨", gradient: "from-amber-400 to-orange-500", category: "language", mechanic: "color-fill", ages: { min: 5, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "colors", palette: P, mascotId: "kody", contentKey: "lang-colors" } },
  { id: "lang-scale-272", title: "Formal vs Informal", description: "Balance formal and informal language registers", icon: "⚖️", gradient: "from-teal-400 to-emerald-500", category: "language", mechanic: "balance-scale", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "register", palette: P, mascotId: "sparkle", contentKey: "lang-register" } },
  { id: "lang-slide-273", title: "Alphabet Slide", description: "Slide foreign alphabet letters into correct order", icon: "🔤", gradient: "from-indigo-400 to-blue-500", category: "language", mechanic: "slide-puzzle", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "alphabet", palette: P, mascotId: "nova", contentKey: "lang-alphabet" } },
  { id: "lang-code-274", title: "Language Bot Coder", description: "Program a chatbot to respond in foreign languages", icon: "💻", gradient: "from-violet-400 to-purple-500", category: "language", mechanic: "coding-blocks", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "nlp", palette: P, mascotId: "ziggy", contentKey: "lang-bot" } },
  { id: "lang-bubble-275", title: "Language Fact Pop", description: "Pop bubbles with correct foreign language facts", icon: "🫧", gradient: "from-sky-400 to-blue-500", category: "language", mechanic: "math-pop", ages: { min: 7, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "language-facts", palette: P, mascotId: "pixel", contentKey: "lang-pop" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  CREATIVE (276-300)                                                    */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "cre-color-276", title: "Masterpiece Studio", description: "Color digital canvases guided by art theory", icon: "🎨", gradient: "from-pink-400 to-rose-500", category: "creative", mechanic: "color-fill", ages: { min: 5, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-theory", palette: P, mascotId: "kody", contentKey: "cre-paint" } },
  { id: "cre-builder-277", title: "Architecture Studio", description: "Design and build famous architectural styles", icon: "🏛️", gradient: "from-amber-400 to-orange-500", category: "creative", mechanic: "builder", ages: { min: 7, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "architecture", palette: P, mascotId: "sparkle", contentKey: "cre-arch" } },
  { id: "cre-jigsaw-278", title: "Famous Painting Jigsaw", description: "Assemble famous paintings from puzzle pieces", icon: "🖼️", gradient: "from-violet-400 to-purple-500", category: "creative", mechanic: "jigsaw", ages: { min: 6, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-history", palette: P, mascotId: "nova", contentKey: "cre-paintings" } },
  { id: "cre-pattern-279", title: "Art Pattern Complete", description: "Complete artistic pattern sequences (tessellation, mandala)", icon: "🔁", gradient: "from-emerald-400 to-teal-500", category: "creative", mechanic: "pattern-complete", ages: { min: 6, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "patterns-in-art", palette: P, mascotId: "ziggy", contentKey: "cre-patterns" } },
  { id: "cre-sort-280", title: "Art Style Sort", description: "Sort artworks into their art movement categories", icon: "📋", gradient: "from-sky-400 to-blue-500", category: "creative", mechanic: "drag-sort", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-movements", palette: P, mascotId: "pixel", contentKey: "cre-movements" } },
  { id: "cre-timeline-281", title: "Art History Timeline", description: "Order art movements and masterpieces chronologically", icon: "📅", gradient: "from-fuchsia-400 to-pink-500", category: "creative", mechanic: "timeline", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-history", palette: P, mascotId: "blaze", contentKey: "cre-arttime" } },
  { id: "cre-quiz-282", title: "Art Quiz Dash", description: "Answer art trivia questions at lightning speed", icon: "⚡", gradient: "from-lime-400 to-green-500", category: "creative", mechanic: "quiz-race", ages: { min: 8, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-trivia", palette: P, mascotId: "luna", contentKey: "cre-quiz" } },
  { id: "cre-memory-283", title: "Art Pair Match", description: "Match artists with their famous works", icon: "🧠", gradient: "from-cyan-400 to-sky-500", category: "creative", mechanic: "memory-flip", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "artists", palette: P, mascotId: "hero", contentKey: "cre-artists" } },
  { id: "cre-match-284", title: "Color Theory Match", description: "Match complementary and analogous colors", icon: "🌈", gradient: "from-red-400 to-violet-500", category: "creative", mechanic: "match-three", ages: { min: 5, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "color-theory", palette: P, mascotId: "dash", contentKey: "cre-colormatch" } },
  { id: "cre-connect-285", title: "Sketch Connect", description: "Connect dots to create line art drawings", icon: "✏️", gradient: "from-rose-400 to-pink-500", category: "creative", mechanic: "connect-dots", ages: { min: 5, max: 10 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "drawing", palette: P, mascotId: "echo", contentKey: "cre-sketch" } },
  { id: "cre-explorer-286", title: "Museum Explorer", description: "Explore world museums discovering art styles", icon: "🏛️", gradient: "from-indigo-400 to-blue-500", category: "creative", mechanic: "map-explorer", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "museums", palette: P, mascotId: "kody", contentKey: "cre-museum" } },
  { id: "cre-word-287", title: "Art Vocab Search", description: "Find art vocabulary words hidden in the grid", icon: "🔍", gradient: "from-teal-400 to-emerald-500", category: "creative", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-vocab", palette: P, mascotId: "sparkle", contentKey: "cre-wordsearch" } },
  { id: "cre-crossword-288", title: "Design Crossword", description: "Fill in art and design terminology", icon: "✏️", gradient: "from-amber-400 to-orange-500", category: "creative", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "design-vocab", palette: P, mascotId: "nova", contentKey: "cre-design" } },
  { id: "cre-maze-289", title: "Gallery Maze", description: "Navigate an art gallery maze collecting masterpieces", icon: "🖼️", gradient: "from-violet-400 to-purple-500", category: "creative", mechanic: "maze-runner", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "galleries", palette: P, mascotId: "ziggy", contentKey: "cre-gallery" } },
  { id: "cre-tower-290", title: "Art Supply Tower", description: "Stack art supplies in the correct creative order", icon: "🏗️", gradient: "from-sky-400 to-blue-500", category: "creative", mechanic: "tower-stack", ages: { min: 5, max: 10 }, eduWeight: 65, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-supplies", palette: P, mascotId: "pixel", contentKey: "cre-supplies" } },
  { id: "cre-catch-291", title: "Inspiration Catcher", description: "Catch falling creative ideas and art elements", icon: "💡", gradient: "from-pink-400 to-rose-500", category: "creative", mechanic: "falling-catch", ages: { min: 5, max: 10 }, eduWeight: 65, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "creativity", palette: P, mascotId: "blaze", contentKey: "cre-ideas" } },
  { id: "cre-typing-292", title: "Art Term Typing", description: "Type art terminology before it fades", icon: "⌨️", gradient: "from-emerald-400 to-teal-500", category: "creative", mechanic: "typing-race", ages: { min: 8, max: 16 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-vocab", palette: P, mascotId: "luna", contentKey: "cre-typing" } },
  { id: "cre-sequence-293", title: "Art Process Recall", description: "Remember the steps of famous art techniques", icon: "🔔", gradient: "from-fuchsia-400 to-pink-500", category: "creative", mechanic: "sequence-recall", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "techniques", palette: P, mascotId: "hero", contentKey: "cre-process" } },
  { id: "cre-runner-294", title: "Creative Sprint", description: "Run through artistic landscapes collecting art elements", icon: "🏃", gradient: "from-lime-400 to-green-500", category: "creative", mechanic: "infinite-runner", ages: { min: 6, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-elements", palette: P, mascotId: "dash", contentKey: "cre-sprint" } },
  { id: "cre-platform-295", title: "Art World Platformer", description: "Platform through art style worlds — cubism, impressionism", icon: "🎮", gradient: "from-cyan-400 to-sky-500", category: "creative", mechanic: "platformer", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-styles", palette: P, mascotId: "echo", contentKey: "cre-styles" } },
  { id: "cre-scale-296", title: "Composition Balance", description: "Balance visual elements for good composition", icon: "⚖️", gradient: "from-rose-400 to-pink-500", category: "creative", mechanic: "balance-scale", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "composition", palette: P, mascotId: "kody", contentKey: "cre-compose" } },
  { id: "cre-slide-297", title: "Mosaic Slide", description: "Slide mosaic tiles to complete an artwork", icon: "🔲", gradient: "from-indigo-400 to-blue-500", category: "creative", mechanic: "slide-puzzle", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mosaics", palette: P, mascotId: "sparkle", contentKey: "cre-mosaic" } },
  { id: "cre-code-298", title: "Generative Art Coder", description: "Program blocks to create generative art patterns", icon: "💻", gradient: "from-teal-400 to-emerald-500", category: "creative", mechanic: "coding-blocks", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "generative-art", palette: P, mascotId: "nova", contentKey: "cre-genart" } },
  { id: "cre-rhythm-299", title: "Art & Music Fusion", description: "Create art by tapping rhythmic patterns", icon: "🎵", gradient: "from-violet-400 to-purple-500", category: "creative", mechanic: "rhythm-tap", ages: { min: 6, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "multimedia", palette: P, mascotId: "ziggy", contentKey: "cre-fusion" } },
  { id: "cre-bubble-300", title: "Creative Fact Pop", description: "Pop bubbles with correct art and design facts", icon: "🫧", gradient: "from-amber-400 to-orange-500", category: "creative", mechanic: "math-pop", ages: { min: 7, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "art-facts", palette: P, mascotId: "pixel", contentKey: "cre-pop" } },
];
