/* -------------------------------------------------------------------------- */
/*  Koydo 300-Game Catalog — Part 2: Geography, Chemistry, Physics          */
/*  75 game definitions (IDs 076–150)                                        */
/* -------------------------------------------------------------------------- */
import type { GameDefinition } from "../types";

const P = ["#fbbf24", "#f472b6", "#34d399", "#60a5fa", "#a78bfa"] as const;

export const CATALOG_PART2: GameDefinition[] = [
  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  GEOGRAPHY (076-100)                                                   */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "geo-explorer-076", title: "World Explorer", description: "Travel the globe solving geography challenges at each destination", icon: "🌍", gradient: "from-emerald-400 to-teal-500", category: "geography", mechanic: "map-explorer", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "world-geography", palette: P, mascotId: "kody", contentKey: "geo-world" } },
  { id: "geo-quiz-077", title: "Capital City Blitz", description: "Name capitals as fast as possible before the clock runs out", icon: "🏛️", gradient: "from-sky-400 to-blue-500", category: "geography", mechanic: "quiz-race", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "capitals", palette: P, mascotId: "sparkle", contentKey: "geo-capitals" } },
  { id: "geo-jigsaw-078", title: "Continent Jigsaw", description: "Assemble continent puzzle pieces on the world map", icon: "🧩", gradient: "from-violet-400 to-purple-500", category: "geography", mechanic: "jigsaw", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "continents", palette: P, mascotId: "nova", contentKey: "geo-continents" } },
  { id: "geo-sort-079", title: "Country Continent Sort", description: "Drag countries to their correct continents", icon: "📋", gradient: "from-amber-400 to-orange-500", category: "geography", mechanic: "drag-sort", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "continents", palette: P, mascotId: "ziggy", contentKey: "geo-sort" } },
  { id: "geo-memory-080", title: "Flag Match", description: "Flip cards to match flags with their countries", icon: "🏳️", gradient: "from-pink-400 to-rose-500", category: "geography", mechanic: "memory-flip", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "flags", palette: P, mascotId: "pixel", contentKey: "geo-flags" } },
  { id: "geo-word-081", title: "Country Word Search", description: "Find hidden country names in the letter grid", icon: "🔍", gradient: "from-lime-400 to-green-500", category: "geography", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "countries", palette: P, mascotId: "blaze", contentKey: "geo-wordsearch" } },
  { id: "geo-maze-082", title: "River Route Maze", description: "Navigate the longest rivers from source to sea", icon: "🏞️", gradient: "from-cyan-400 to-sky-500", category: "geography", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "rivers", palette: P, mascotId: "luna", contentKey: "geo-rivers" } },
  { id: "geo-timeline-083", title: "Discovery Timeline", description: "Order geographic discoveries chronologically", icon: "📅", gradient: "from-fuchsia-400 to-pink-500", category: "geography", mechanic: "timeline", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "exploration-history", palette: P, mascotId: "hero", contentKey: "geo-discovery" } },
  { id: "geo-color-084", title: "Biome Map Coloring", description: "Color world regions by their biome type", icon: "🎨", gradient: "from-green-400 to-emerald-500", category: "geography", mechanic: "color-fill", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biomes", palette: P, mascotId: "dash", contentKey: "geo-biomes" } },
  { id: "geo-typing-085", title: "Capital Typing Sprint", description: "Type capital city names before time runs out", icon: "⌨️", gradient: "from-rose-400 to-pink-500", category: "geography", mechanic: "typing-race", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "capitals", palette: P, mascotId: "echo", contentKey: "geo-typing" } },
  { id: "geo-match-086", title: "Landmark Gem Match", description: "Match landmark gems from the same continent", icon: "🗼", gradient: "from-indigo-400 to-blue-500", category: "geography", mechanic: "match-three", ages: { min: 6, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "landmarks", palette: P, mascotId: "kody", contentKey: "geo-landmarks" } },
  { id: "geo-tower-087", title: "Mountain Stack", description: "Stack mountain blocks in height order", icon: "🏔️", gradient: "from-teal-400 to-emerald-500", category: "geography", mechanic: "tower-stack", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mountains", palette: P, mascotId: "sparkle", contentKey: "geo-mountains" } },
  { id: "geo-catch-088", title: "Falling Continents", description: "Catch facts about the correct continent as they fall", icon: "🌏", gradient: "from-yellow-400 to-amber-500", category: "geography", mechanic: "falling-catch", ages: { min: 6, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "continents", palette: P, mascotId: "nova", contentKey: "geo-falling" } },
  { id: "geo-pattern-089", title: "Climate Pattern", description: "Complete climate zone patterns around the globe", icon: "🌤️", gradient: "from-sky-400 to-blue-500", category: "geography", mechanic: "pattern-complete", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "climate", palette: P, mascotId: "ziggy", contentKey: "geo-climate" } },
  { id: "geo-connect-090", title: "Trade Route Dots", description: "Connect dots tracing historic trade routes", icon: "🚢", gradient: "from-amber-400 to-orange-500", category: "geography", mechanic: "connect-dots", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "trade-routes", palette: P, mascotId: "pixel", contentKey: "geo-trade" } },
  { id: "geo-crossword-091", title: "Geography Crossword", description: "Fill in geographic terms and place names", icon: "✏️", gradient: "from-violet-400 to-purple-500", category: "geography", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "geo-vocab", palette: P, mascotId: "blaze", contentKey: "geo-crossword" } },
  { id: "geo-runner-092", title: "Safari Runner", description: "Run through African landscapes collecting animal facts", icon: "🦁", gradient: "from-emerald-400 to-teal-500", category: "geography", mechanic: "infinite-runner", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "africa", palette: P, mascotId: "luna", contentKey: "geo-safari" } },
  { id: "geo-platform-093", title: "Ocean Diver", description: "Platform through ocean depths discovering marine zones", icon: "🤿", gradient: "from-blue-400 to-indigo-500", category: "geography", mechanic: "platformer", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "oceans", palette: P, mascotId: "hero", contentKey: "geo-ocean" } },
  { id: "geo-builder-094", title: "City Builder", description: "Build famous cities from geographic clues", icon: "🏗️", gradient: "from-pink-400 to-rose-500", category: "geography", mechanic: "builder", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "cities", palette: P, mascotId: "dash", contentKey: "geo-cities" } },
  { id: "geo-code-095", title: "Map Code Navigator", description: "Program directions to navigate between landmarks", icon: "💻", gradient: "from-cyan-400 to-sky-500", category: "geography", mechanic: "coding-blocks", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "navigation", palette: P, mascotId: "echo", contentKey: "geo-nav" } },
  { id: "geo-scale-096", title: "Population Scales", description: "Balance country populations on a scale", icon: "⚖️", gradient: "from-fuchsia-400 to-pink-500", category: "geography", mechanic: "balance-scale", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "demographics", palette: P, mascotId: "kody", contentKey: "geo-pop" } },
  { id: "geo-sequence-097", title: "Continent Recall", description: "Remember the sequence of geographic facts", icon: "🔔", gradient: "from-lime-400 to-green-500", category: "geography", mechanic: "sequence-recall", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "world-facts", palette: P, mascotId: "sparkle", contentKey: "geo-recall" } },
  { id: "geo-rhythm-098", title: "Drum Circle World", description: "Tap world music rhythms from different cultures", icon: "🥁", gradient: "from-rose-400 to-pink-500", category: "geography", mechanic: "rhythm-tap", ages: { min: 6, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "cultures", palette: P, mascotId: "nova", contentKey: "geo-drums" } },
  { id: "geo-slide-099", title: "Hemisphere Slide", description: "Slide country tiles to their correct hemisphere", icon: "🌐", gradient: "from-teal-400 to-emerald-500", category: "geography", mechanic: "slide-puzzle", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "hemispheres", palette: P, mascotId: "ziggy", contentKey: "geo-hemi" } },
  { id: "geo-bubble-100", title: "Geo Fact Pop", description: "Pop bubbles containing correct geography facts", icon: "🫧", gradient: "from-indigo-400 to-blue-500", category: "geography", mechanic: "math-pop", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "world-facts", palette: P, mascotId: "pixel", contentKey: "geo-pop-quiz" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  CHEMISTRY (101-125)                                                   */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "chem-lab-101", title: "Element Lab", description: "Combine elements to discover compounds and reactions", icon: "🧪", gradient: "from-emerald-400 to-teal-500", category: "chemistry", mechanic: "element-lab", ages: { min: 9, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "reactions", palette: P, mascotId: "kody", contentKey: "chem-lab" } },
  { id: "chem-quiz-102", title: "Chemistry Quiz Dash", description: "Race through rapid-fire chemistry questions", icon: "⚡", gradient: "from-violet-400 to-purple-500", category: "chemistry", mechanic: "quiz-race", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "general-chem", palette: P, mascotId: "sparkle", contentKey: "chem-quiz" } },
  { id: "chem-memory-103", title: "Element Symbol Match", description: "Match element symbols with their names", icon: "🧠", gradient: "from-sky-400 to-blue-500", category: "chemistry", mechanic: "memory-flip", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "elements", palette: P, mascotId: "nova", contentKey: "chem-symbols" } },
  { id: "chem-sort-104", title: "Element Category Sort", description: "Sort elements into metals, non-metals, and metalloids", icon: "📋", gradient: "from-amber-400 to-orange-500", category: "chemistry", mechanic: "drag-sort", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "periodic-table", palette: P, mascotId: "ziggy", contentKey: "chem-sort" } },
  { id: "chem-balance-105", title: "Equation Balancer", description: "Balance chemical equations on a lab scale", icon: "⚖️", gradient: "from-pink-400 to-rose-500", category: "chemistry", mechanic: "balance-scale", ages: { min: 10, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "stoichiometry", palette: P, mascotId: "pixel", contentKey: "chem-balance" } },
  { id: "chem-match-106", title: "Molecule Match 3", description: "Match molecular components in a gem-matching grid", icon: "💎", gradient: "from-fuchsia-400 to-pink-500", category: "chemistry", mechanic: "match-three", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "molecules", palette: P, mascotId: "blaze", contentKey: "chem-match" } },
  { id: "chem-pattern-107", title: "Periodic Pattern", description: "Find patterns in periodic table rows and groups", icon: "🔁", gradient: "from-lime-400 to-green-500", category: "chemistry", mechanic: "pattern-complete", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "periodicity", palette: P, mascotId: "luna", contentKey: "chem-pattern" } },
  { id: "chem-builder-108", title: "Molecule Builder", description: "Construct molecules by connecting atoms", icon: "⚛️", gradient: "from-cyan-400 to-sky-500", category: "chemistry", mechanic: "builder", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "molecular-structure", palette: P, mascotId: "hero", contentKey: "chem-build" } },
  { id: "chem-typing-109", title: "Element Typing Blitz", description: "Type element names before they disappear", icon: "⌨️", gradient: "from-rose-400 to-pink-500", category: "chemistry", mechanic: "typing-race", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "elements", palette: P, mascotId: "dash", contentKey: "chem-typing" } },
  { id: "chem-word-110", title: "Chemistry Word Hunt", description: "Find chemistry vocabulary hidden in the grid", icon: "🔍", gradient: "from-teal-400 to-emerald-500", category: "chemistry", mechanic: "word-search", ages: { min: 9, max: 16 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chem-vocab", palette: P, mascotId: "echo", contentKey: "chem-wordsearch" } },
  { id: "chem-catch-111", title: "Atom Catcher", description: "Catch the correct atoms as they fall from above", icon: "⚛️", gradient: "from-indigo-400 to-blue-500", category: "chemistry", mechanic: "falling-catch", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "atoms", palette: P, mascotId: "kody", contentKey: "chem-catch" } },
  { id: "chem-maze-112", title: "Reaction Pathway Maze", description: "Navigate through reaction pathways to form products", icon: "🔬", gradient: "from-emerald-400 to-teal-500", category: "chemistry", mechanic: "maze-runner", ages: { min: 10, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "reactions", palette: P, mascotId: "sparkle", contentKey: "chem-maze" } },
  { id: "chem-timeline-113", title: "Chemistry History", description: "Order chemistry discoveries from alchemy to modern", icon: "📅", gradient: "from-yellow-400 to-amber-500", category: "chemistry", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chem-history", palette: P, mascotId: "nova", contentKey: "chem-time" } },
  { id: "chem-crossword-114", title: "Chemistry Crossword", description: "Complete a crossword with element and compound clues", icon: "✏️", gradient: "from-violet-400 to-purple-500", category: "chemistry", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chem-vocab", palette: P, mascotId: "ziggy", contentKey: "chem-cross" } },
  { id: "chem-jigsaw-115", title: "Periodic Table Jigsaw", description: "Assemble the periodic table from scattered pieces", icon: "🧩", gradient: "from-sky-400 to-blue-500", category: "chemistry", mechanic: "jigsaw", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "periodic-table", palette: P, mascotId: "pixel", contentKey: "chem-jigsaw" } },
  { id: "chem-runner-116", title: "Particle Dash", description: "Run collecting subatomic particles to build atoms", icon: "🏃", gradient: "from-pink-400 to-rose-500", category: "chemistry", mechanic: "infinite-runner", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "atomic-structure", palette: P, mascotId: "blaze", contentKey: "chem-dash" } },
  { id: "chem-platform-117", title: "Lab Explorer", description: "Jump between lab benches conducting experiments", icon: "🎮", gradient: "from-amber-400 to-orange-500", category: "chemistry", mechanic: "platformer", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "lab-safety", palette: P, mascotId: "luna", contentKey: "chem-explore" } },
  { id: "chem-sequence-118", title: "Reaction Sequence", description: "Remember the correct order of reaction steps", icon: "🔔", gradient: "from-lime-400 to-green-500", category: "chemistry", mechanic: "sequence-recall", ages: { min: 10, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "reactions", palette: P, mascotId: "hero", contentKey: "chem-seq" } },
  { id: "chem-color-119", title: "pH Color Map", description: "Color solutions by their pH level indicator colors", icon: "🎨", gradient: "from-fuchsia-400 to-pink-500", category: "chemistry", mechanic: "color-fill", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "acids-bases", palette: P, mascotId: "dash", contentKey: "chem-ph" } },
  { id: "chem-connect-120", title: "Bond Connect", description: "Connect atoms with the correct chemical bonds", icon: "🔗", gradient: "from-emerald-400 to-teal-500", category: "chemistry", mechanic: "connect-dots", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "bonding", palette: P, mascotId: "echo", contentKey: "chem-bonds" } },
  { id: "chem-tower-121", title: "Density Tower", description: "Stack liquids in order of their density", icon: "🏗️", gradient: "from-cyan-400 to-sky-500", category: "chemistry", mechanic: "tower-stack", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "density", palette: P, mascotId: "kody", contentKey: "chem-density" } },
  { id: "chem-slide-122", title: "Electron Shell Slide", description: "Slide electrons into the correct energy shells", icon: "🔄", gradient: "from-violet-400 to-purple-500", category: "chemistry", mechanic: "slide-puzzle", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "electron-config", palette: P, mascotId: "sparkle", contentKey: "chem-shells" } },
  { id: "chem-code-123", title: "Lab Robot Programmer", description: "Program a robot to mix chemicals safely", icon: "🤖", gradient: "from-indigo-400 to-blue-500", category: "chemistry", mechanic: "coding-blocks", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "lab-procedures", palette: P, mascotId: "nova", contentKey: "chem-robot" } },
  { id: "chem-rhythm-124", title: "Reaction Rate Rhythm", description: "Tap to match the rate of different chemical reactions", icon: "🎵", gradient: "from-teal-400 to-emerald-500", category: "chemistry", mechanic: "rhythm-tap", ages: { min: 9, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "kinetics", palette: P, mascotId: "ziggy", contentKey: "chem-rate" } },
  { id: "chem-bubble-125", title: "Chemistry Fact Pop", description: "Pop bubbles containing correct chemistry facts", icon: "🫧", gradient: "from-rose-400 to-pink-500", category: "chemistry", mechanic: "math-pop", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chem-facts", palette: P, mascotId: "pixel", contentKey: "chem-pop" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  PHYSICS (126-150)                                                     */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "phys-builder-126", title: "Bridge Builder", description: "Build bridges that withstand physics simulations", icon: "🌉", gradient: "from-sky-400 to-blue-500", category: "physics", mechanic: "builder", ages: { min: 8, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "structural-engineering", palette: P, mascotId: "kody", contentKey: "phys-bridge" } },
  { id: "phys-balance-127", title: "Force Balance", description: "Balance force vectors on a physics scale", icon: "⚖️", gradient: "from-emerald-400 to-teal-500", category: "physics", mechanic: "balance-scale", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "forces", palette: P, mascotId: "sparkle", contentKey: "phys-force" } },
  { id: "phys-quiz-128", title: "Physics Quiz Blast", description: "Answer physics questions at lightning speed", icon: "⚡", gradient: "from-amber-400 to-orange-500", category: "physics", mechanic: "quiz-race", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "general-physics", palette: P, mascotId: "nova", contentKey: "phys-quiz" } },
  { id: "phys-platform-129", title: "Gravity Jumper", description: "Platform with different gravity on each level", icon: "🪐", gradient: "from-violet-400 to-purple-500", category: "physics", mechanic: "platformer", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "gravity", palette: P, mascotId: "ziggy", contentKey: "phys-gravity" } },
  { id: "phys-runner-130", title: "Velocity Runner", description: "Accelerate and decelerate learning about motion", icon: "🏃", gradient: "from-pink-400 to-rose-500", category: "physics", mechanic: "infinite-runner", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "motion", palette: P, mascotId: "pixel", contentKey: "phys-velocity" } },
  { id: "phys-maze-131", title: "Light Ray Maze", description: "Navigate light rays through mirrors and lenses", icon: "🔦", gradient: "from-yellow-400 to-amber-500", category: "physics", mechanic: "maze-runner", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "optics", palette: P, mascotId: "blaze", contentKey: "phys-light" } },
  { id: "phys-sort-132", title: "Energy Type Sort", description: "Sort examples into kinetic, potential, and thermal", icon: "📋", gradient: "from-lime-400 to-green-500", category: "physics", mechanic: "drag-sort", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "energy", palette: P, mascotId: "luna", contentKey: "phys-energy" } },
  { id: "phys-tower-133", title: "Tower of Torque", description: "Stack objects understanding torque and balance", icon: "🏗️", gradient: "from-fuchsia-400 to-pink-500", category: "physics", mechanic: "tower-stack", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "torque", palette: P, mascotId: "hero", contentKey: "phys-torque" } },
  { id: "phys-catch-134", title: "Particle Rain", description: "Catch the correct fundamental particles as they fall", icon: "⚛️", gradient: "from-cyan-400 to-sky-500", category: "physics", mechanic: "falling-catch", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "particle-physics", palette: P, mascotId: "dash", contentKey: "phys-particles" } },
  { id: "phys-memory-135", title: "Physics Pair Match", description: "Match physics concepts with their formulas", icon: "🧠", gradient: "from-rose-400 to-pink-500", category: "physics", mechanic: "memory-flip", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "formulas", palette: P, mascotId: "echo", contentKey: "phys-formulas" } },
  { id: "phys-pattern-136", title: "Wave Patterns", description: "Complete wave frequency and amplitude patterns", icon: "🌊", gradient: "from-indigo-400 to-blue-500", category: "physics", mechanic: "pattern-complete", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "waves", palette: P, mascotId: "kody", contentKey: "phys-waves" } },
  { id: "phys-connect-137", title: "Circuit Connect", description: "Connect circuit components to light the bulb", icon: "💡", gradient: "from-amber-400 to-yellow-500", category: "physics", mechanic: "connect-dots", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "circuits", palette: P, mascotId: "sparkle", contentKey: "phys-circuit" } },
  { id: "phys-timeline-138", title: "Physics Discovery Timeline", description: "Order physics breakthroughs chronologically", icon: "📅", gradient: "from-teal-400 to-emerald-500", category: "physics", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "physics-history", palette: P, mascotId: "nova", contentKey: "phys-time" } },
  { id: "phys-crossword-139", title: "Physics Crossword", description: "Fill in physics terminology crossword", icon: "✏️", gradient: "from-violet-400 to-purple-500", category: "physics", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phys-vocab", palette: P, mascotId: "ziggy", contentKey: "phys-cross" } },
  { id: "phys-word-140", title: "Physics Word Search", description: "Find physics terms hidden in the grid", icon: "🔍", gradient: "from-sky-400 to-blue-500", category: "physics", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phys-vocab", palette: P, mascotId: "pixel", contentKey: "phys-wordsearch" } },
  { id: "phys-jigsaw-141", title: "Machine Jigsaw", description: "Assemble simple machines from their parts", icon: "🧩", gradient: "from-emerald-400 to-teal-500", category: "physics", mechanic: "jigsaw", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "simple-machines", palette: P, mascotId: "blaze", contentKey: "phys-machines" } },
  { id: "phys-typing-142", title: "Formula Typing Race", description: "Type physics formulas before they fade", icon: "⌨️", gradient: "from-pink-400 to-rose-500", category: "physics", mechanic: "typing-race", ages: { min: 10, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "formulas", palette: P, mascotId: "luna", contentKey: "phys-typing" } },
  { id: "phys-sequence-143", title: "Experiment Steps", description: "Remember the correct experimental procedure", icon: "🔔", gradient: "from-fuchsia-400 to-pink-500", category: "physics", mechanic: "sequence-recall", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "scientific-method", palette: P, mascotId: "hero", contentKey: "phys-method" } },
  { id: "phys-color-144", title: "Spectrum Painter", description: "Color the electromagnetic spectrum correctly", icon: "🌈", gradient: "from-red-400 to-violet-500", category: "physics", mechanic: "color-fill", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "em-spectrum", palette: P, mascotId: "dash", contentKey: "phys-spectrum" } },
  { id: "phys-slide-145", title: "Gear Slide Puzzle", description: "Slide gears into position to create a mechanism", icon: "⚙️", gradient: "from-gray-400 to-slate-500", category: "physics", mechanic: "slide-puzzle", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mechanics", palette: P, mascotId: "echo", contentKey: "phys-gears" } },
  { id: "phys-code-146", title: "Physics Simulator Code", description: "Code simulations of physical phenomena", icon: "💻", gradient: "from-indigo-400 to-blue-500", category: "physics", mechanic: "coding-blocks", ages: { min: 9, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "simulation", palette: P, mascotId: "kody", contentKey: "phys-sim" } },
  { id: "phys-explorer-147", title: "Space Physics Explorer", description: "Explore space learning orbital mechanics", icon: "🚀", gradient: "from-violet-400 to-purple-500", category: "physics", mechanic: "map-explorer", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "orbital-mechanics", palette: P, mascotId: "sparkle", contentKey: "phys-orbits" } },
  { id: "phys-match-148", title: "Magnet Match 3", description: "Match magnetic poles and fields in a gem grid", icon: "🧲", gradient: "from-red-400 to-rose-500", category: "physics", mechanic: "match-three", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "magnetism", palette: P, mascotId: "nova", contentKey: "phys-magnet" } },
  { id: "phys-rhythm-149", title: "Sound Wave Rhythm", description: "Tap to match sound wave frequencies", icon: "🎵", gradient: "from-amber-400 to-orange-500", category: "physics", mechanic: "rhythm-tap", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "acoustics", palette: P, mascotId: "ziggy", contentKey: "phys-sound" } },
  { id: "phys-bubble-150", title: "Physics Fact Pop", description: "Pop bubbles with correct physics statements", icon: "🫧", gradient: "from-teal-400 to-emerald-500", category: "physics", mechanic: "math-pop", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phys-facts", palette: P, mascotId: "pixel", contentKey: "phys-pop" } },
];
