/* -------------------------------------------------------------------------- */
/*  Koydo 300-Game Catalog — Part 3: History, Coding, Music                 */
/*  75 game definitions (IDs 151–225)                                        */
/* -------------------------------------------------------------------------- */
import type { GameDefinition } from "../types";

const P = ["#fbbf24", "#f472b6", "#34d399", "#60a5fa", "#a78bfa"] as const;

export const CATALOG_PART3: GameDefinition[] = [
  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  HISTORY (151-175)                                                     */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "hist-timeline-151", title: "World History Timeline", description: "Order world events from ancient to modern", icon: "📅", gradient: "from-amber-400 to-orange-500", category: "history", mechanic: "timeline", ages: { min: 8, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "world-history", palette: P, mascotId: "kody", contentKey: "hist-world" } },
  { id: "hist-quiz-152", title: "History Quiz Rush", description: "Race through rapid-fire history questions", icon: "⚡", gradient: "from-emerald-400 to-teal-500", category: "history", mechanic: "quiz-race", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "general-history", palette: P, mascotId: "sparkle", contentKey: "hist-quiz" } },
  { id: "hist-explorer-153", title: "Time Traveler", description: "Travel to historic locations solving period puzzles", icon: "⏳", gradient: "from-violet-400 to-purple-500", category: "history", mechanic: "map-explorer", ages: { min: 8, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "civilizations", palette: P, mascotId: "nova", contentKey: "hist-travel" } },
  { id: "hist-memory-154", title: "Historic Figure Match", description: "Match historic figures with their achievements", icon: "🧠", gradient: "from-sky-400 to-blue-500", category: "history", mechanic: "memory-flip", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "famous-people", palette: P, mascotId: "ziggy", contentKey: "hist-figures" } },
  { id: "hist-sort-155", title: "Era Sort", description: "Sort events into the correct historical era", icon: "📋", gradient: "from-pink-400 to-rose-500", category: "history", mechanic: "drag-sort", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "eras", palette: P, mascotId: "pixel", contentKey: "hist-eras" } },
  { id: "hist-jigsaw-156", title: "Ancient Map Jigsaw", description: "Assemble ancient maps from puzzle pieces", icon: "🗺️", gradient: "from-amber-400 to-orange-500", category: "history", mechanic: "jigsaw", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "ancient-maps", palette: P, mascotId: "blaze", contentKey: "hist-maps" } },
  { id: "hist-word-157", title: "History Word Hunt", description: "Find historical terms hidden in the grid", icon: "🔍", gradient: "from-lime-400 to-green-500", category: "history", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "hist-vocab", palette: P, mascotId: "luna", contentKey: "hist-wordsearch" } },
  { id: "hist-crossword-158", title: "History Crossword", description: "Complete crosswords with historical clues", icon: "✏️", gradient: "from-fuchsia-400 to-pink-500", category: "history", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "hist-vocab", palette: P, mascotId: "hero", contentKey: "hist-cross" } },
  { id: "hist-maze-159", title: "Castle Maze", description: "Navigate through medieval castle passages", icon: "🏰", gradient: "from-cyan-400 to-sky-500", category: "history", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "medieval", palette: P, mascotId: "dash", contentKey: "hist-castle" } },
  { id: "hist-match-160", title: "Artifact Match 3", description: "Match ancient artifacts in a gem-matching grid", icon: "🏺", gradient: "from-rose-400 to-pink-500", category: "history", mechanic: "match-three", ages: { min: 7, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "archaeology", palette: P, mascotId: "echo", contentKey: "hist-artifact" } },
  { id: "hist-builder-161", title: "Pyramid Builder", description: "Build ancient structures following historical plans", icon: "🏛️", gradient: "from-yellow-400 to-amber-500", category: "history", mechanic: "builder", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "ancient-architecture", palette: P, mascotId: "kody", contentKey: "hist-pyramid" } },
  { id: "hist-typing-162", title: "Historic Dates Typing", description: "Type important dates before they vanish", icon: "⌨️", gradient: "from-indigo-400 to-blue-500", category: "history", mechanic: "typing-race", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "dates", palette: P, mascotId: "sparkle", contentKey: "hist-dates" } },
  { id: "hist-catch-163", title: "Timeline Catcher", description: "Catch falling events from the correct era", icon: "🌧️", gradient: "from-teal-400 to-emerald-500", category: "history", mechanic: "falling-catch", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "events", palette: P, mascotId: "nova", contentKey: "hist-catch" } },
  { id: "hist-pattern-164", title: "Dynasty Patterns", description: "Complete patterns of ruling dynasties", icon: "👑", gradient: "from-violet-400 to-purple-500", category: "history", mechanic: "pattern-complete", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "dynasties", palette: P, mascotId: "ziggy", contentKey: "hist-dynasty" } },
  { id: "hist-platform-165", title: "Ancient Runner", description: "Run through ancient civilizations collecting artifacts", icon: "🏃", gradient: "from-amber-400 to-orange-500", category: "history", mechanic: "platformer", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "civilizations", palette: P, mascotId: "pixel", contentKey: "hist-ancient" } },
  { id: "hist-runner-166", title: "Explorer Dash", description: "Run the Silk Road collecting trade goods", icon: "🐫", gradient: "from-emerald-400 to-teal-500", category: "history", mechanic: "infinite-runner", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "trade-routes", palette: P, mascotId: "blaze", contentKey: "hist-silk" } },
  { id: "hist-sequence-167", title: "Battle Order", description: "Remember the sequence of historic battle events", icon: "🔔", gradient: "from-sky-400 to-blue-500", category: "history", mechanic: "sequence-recall", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "military-history", palette: P, mascotId: "luna", contentKey: "hist-battle" } },
  { id: "hist-color-168", title: "Empire Map Coloring", description: "Color historical empire territories correctly", icon: "🎨", gradient: "from-pink-400 to-rose-500", category: "history", mechanic: "color-fill", ages: { min: 8, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "empires", palette: P, mascotId: "hero", contentKey: "hist-empires" } },
  { id: "hist-connect-169", title: "Trade Route Connect", description: "Connect ancient trade route waypoints", icon: "🚢", gradient: "from-fuchsia-400 to-pink-500", category: "history", mechanic: "connect-dots", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "trade", palette: P, mascotId: "dash", contentKey: "hist-trade" } },
  { id: "hist-tower-170", title: "Civilization Tower", description: "Stack civilization achievements in chronological order", icon: "🏗️", gradient: "from-lime-400 to-green-500", category: "history", mechanic: "tower-stack", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "achievements", palette: P, mascotId: "echo", contentKey: "hist-civtower" } },
  { id: "hist-slide-171", title: "Century Slide Puzzle", description: "Slide events into the correct century", icon: "🧩", gradient: "from-cyan-400 to-sky-500", category: "history", mechanic: "slide-puzzle", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "centuries", palette: P, mascotId: "kody", contentKey: "hist-century" } },
  { id: "hist-code-172", title: "History Archive Code", description: "Program a robot archaeologist to catalog finds", icon: "💻", gradient: "from-violet-400 to-purple-500", category: "history", mechanic: "coding-blocks", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "archaeology", palette: P, mascotId: "sparkle", contentKey: "hist-archive" } },
  { id: "hist-rhythm-173", title: "Ancient Music Rhythm", description: "Tap to the rhythm of music from different eras", icon: "🎵", gradient: "from-rose-400 to-pink-500", category: "history", mechanic: "rhythm-tap", ages: { min: 7, max: 14 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-history", palette: P, mascotId: "nova", contentKey: "hist-music" } },
  { id: "hist-scale-174", title: "Treaty Balance", description: "Balance the terms of historic peace treaties", icon: "⚖️", gradient: "from-teal-400 to-emerald-500", category: "history", mechanic: "balance-scale", ages: { min: 10, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "diplomacy", palette: P, mascotId: "ziggy", contentKey: "hist-treaty" } },
  { id: "hist-bubble-175", title: "History Fact Pop", description: "Pop bubbles containing correct historical facts", icon: "🫧", gradient: "from-indigo-400 to-blue-500", category: "history", mechanic: "math-pop", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "hist-facts", palette: P, mascotId: "pixel", contentKey: "hist-pop" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  CODING (176-200)                                                      */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "code-blocks-176", title: "Code Quest", description: "Snap coding blocks together to solve programming puzzles", icon: "💻", gradient: "from-indigo-400 to-blue-500", category: "coding", mechanic: "coding-blocks", ages: { min: 7, max: 16 }, eduWeight: 95, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "programming", palette: P, mascotId: "kody", contentKey: "code-quest" } },
  { id: "code-maze-177", title: "Algorithm Maze", description: "Write algorithms to navigate a robot through mazes", icon: "🤖", gradient: "from-emerald-400 to-teal-500", category: "coding", mechanic: "maze-runner", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "algorithms", palette: P, mascotId: "sparkle", contentKey: "code-maze" } },
  { id: "code-sort-178", title: "Data Structure Sort", description: "Sort items into arrays, stacks, and queues", icon: "📋", gradient: "from-violet-400 to-purple-500", category: "coding", mechanic: "drag-sort", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "data-structures", palette: P, mascotId: "nova", contentKey: "code-struct" } },
  { id: "code-quiz-179", title: "Debug Blitz", description: "Find and fix bugs in code snippets as fast as you can", icon: "🐛", gradient: "from-amber-400 to-orange-500", category: "coding", mechanic: "quiz-race", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "debugging", palette: P, mascotId: "ziggy", contentKey: "code-debug" } },
  { id: "code-pattern-180", title: "Code Pattern Master", description: "Complete coding pattern sequences", icon: "🔁", gradient: "from-sky-400 to-blue-500", category: "coding", mechanic: "pattern-complete", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "patterns", palette: P, mascotId: "pixel", contentKey: "code-pattern" } },
  { id: "code-typing-181", title: "Code Typing Sprint", description: "Type code keywords before they time out", icon: "⌨️", gradient: "from-pink-400 to-rose-500", category: "coding", mechanic: "typing-race", ages: { min: 8, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "syntax", palette: P, mascotId: "blaze", contentKey: "code-typing" } },
  { id: "code-memory-182", title: "Function Match", description: "Match functions with their return values", icon: "🧠", gradient: "from-lime-400 to-green-500", category: "coding", mechanic: "memory-flip", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "functions", palette: P, mascotId: "luna", contentKey: "code-func" } },
  { id: "code-sequence-183", title: "Algorithm Steps", description: "Remember the correct algorithm execution order", icon: "🔔", gradient: "from-fuchsia-400 to-pink-500", category: "coding", mechanic: "sequence-recall", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "algorithms", palette: P, mascotId: "hero", contentKey: "code-algo" } },
  { id: "code-builder-184", title: "App Builder", description: "Build simple app interfaces from component blocks", icon: "🏗️", gradient: "from-cyan-400 to-sky-500", category: "coding", mechanic: "builder", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "ui-design", palette: P, mascotId: "dash", contentKey: "code-app" } },
  { id: "code-word-185", title: "Programming Word Search", description: "Find programming terms in the grid", icon: "🔍", gradient: "from-rose-400 to-pink-500", category: "coding", mechanic: "word-search", ages: { min: 8, max: 16 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "programming-vocab", palette: P, mascotId: "echo", contentKey: "code-wordsearch" } },
  { id: "code-runner-186", title: "Binary Runner", description: "Run collecting 0s and 1s to form correct binary numbers", icon: "🏃", gradient: "from-gray-400 to-slate-500", category: "coding", mechanic: "infinite-runner", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "binary", palette: P, mascotId: "kody", contentKey: "code-binary" } },
  { id: "code-match-187", title: "Syntax Gem Match", description: "Match syntax elements in a gem-matching grid", icon: "💎", gradient: "from-indigo-400 to-blue-500", category: "coding", mechanic: "match-three", ages: { min: 7, max: 14 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "syntax", palette: P, mascotId: "sparkle", contentKey: "code-syntax" } },
  { id: "code-platform-188", title: "API Adventure", description: "Platform through servers learning about APIs", icon: "🎮", gradient: "from-emerald-400 to-teal-500", category: "coding", mechanic: "platformer", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "apis", palette: P, mascotId: "nova", contentKey: "code-api" } },
  { id: "code-crossword-189", title: "Coding Crossword", description: "Fill in programming vocabulary crossword", icon: "✏️", gradient: "from-amber-400 to-orange-500", category: "coding", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocab", palette: P, mascotId: "ziggy", contentKey: "code-cross" } },
  { id: "code-connect-190", title: "Network Connect", description: "Connect network nodes to build a computer network", icon: "🌐", gradient: "from-sky-400 to-blue-500", category: "coding", mechanic: "connect-dots", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "networking", palette: P, mascotId: "pixel", contentKey: "code-network" } },
  { id: "code-jigsaw-191", title: "Code Snippet Jigsaw", description: "Assemble code snippets into working programs", icon: "🧩", gradient: "from-violet-400 to-purple-500", category: "coding", mechanic: "jigsaw", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "code-reading", palette: P, mascotId: "blaze", contentKey: "code-jigsaw" } },
  { id: "code-tower-192", title: "Stack Tower", description: "Stack function calls like a call stack", icon: "📚", gradient: "from-teal-400 to-emerald-500", category: "coding", mechanic: "tower-stack", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "call-stack", palette: P, mascotId: "luna", contentKey: "code-stack" } },
  { id: "code-catch-193", title: "Variable Catcher", description: "Catch variables of the correct data type", icon: "🎯", gradient: "from-pink-400 to-rose-500", category: "coding", mechanic: "falling-catch", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "data-types", palette: P, mascotId: "hero", contentKey: "code-vars" } },
  { id: "code-timeline-194", title: "Computing Timeline", description: "Order computing milestones chronologically", icon: "📅", gradient: "from-fuchsia-400 to-pink-500", category: "coding", mechanic: "timeline", ages: { min: 8, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "computing-history", palette: P, mascotId: "dash", contentKey: "code-time" } },
  { id: "code-color-195", title: "Pixel Art Coder", description: "Color pixels using coordinate programming", icon: "🎨", gradient: "from-emerald-400 to-teal-500", category: "coding", mechanic: "color-fill", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "coordinates", palette: P, mascotId: "echo", contentKey: "code-pixel" } },
  { id: "code-scale-196", title: "Complexity Scale", description: "Balance algorithm time complexities", icon: "⚖️", gradient: "from-indigo-400 to-blue-500", category: "coding", mechanic: "balance-scale", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "big-o", palette: P, mascotId: "kody", contentKey: "code-bigo" } },
  { id: "code-explorer-197", title: "Internet Explorer", description: "Travel the internet learning about protocols", icon: "🗺️", gradient: "from-cyan-400 to-sky-500", category: "coding", mechanic: "map-explorer", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "internet", palette: P, mascotId: "sparkle", contentKey: "code-internet" } },
  { id: "code-slide-198", title: "Logic Gate Slide", description: "Slide logic gates to form correct circuits", icon: "🔌", gradient: "from-gray-400 to-slate-500", category: "coding", mechanic: "slide-puzzle", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "logic-gates", palette: P, mascotId: "nova", contentKey: "code-gates" } },
  { id: "code-rhythm-199", title: "Clock Cycle Rhythm", description: "Tap to the rhythm of CPU clock cycles", icon: "🎵", gradient: "from-violet-400 to-purple-500", category: "coding", mechanic: "rhythm-tap", ages: { min: 9, max: 16 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "hardware", palette: P, mascotId: "ziggy", contentKey: "code-clock" } },
  { id: "code-bubble-200", title: "Code Fact Pop", description: "Pop bubbles with correct programming concepts", icon: "🫧", gradient: "from-sky-400 to-blue-500", category: "coding", mechanic: "math-pop", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "concepts", palette: P, mascotId: "pixel", contentKey: "code-pop" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  MUSIC (201-225)                                                       */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "mus-rhythm-201", title: "Beat Master", description: "Tap perfect rhythms to popular song patterns", icon: "🥁", gradient: "from-pink-400 to-rose-500", category: "music", mechanic: "rhythm-tap", ages: { min: 5, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "rhythm", palette: P, mascotId: "kody", contentKey: "mus-beat" } },
  { id: "mus-quiz-202", title: "Music Theory Quiz", description: "Answer music theory questions at speed", icon: "⚡", gradient: "from-amber-400 to-orange-500", category: "music", mechanic: "quiz-race", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "theory", palette: P, mascotId: "sparkle", contentKey: "mus-theory" } },
  { id: "mus-memory-203", title: "Note Pair Match", description: "Match musical notes with their names and values", icon: "🧠", gradient: "from-violet-400 to-purple-500", category: "music", mechanic: "memory-flip", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "notes", palette: P, mascotId: "nova", contentKey: "mus-notes" } },
  { id: "mus-sequence-204", title: "Melody Recall", description: "Remember and replay melody sequences", icon: "🎹", gradient: "from-sky-400 to-blue-500", category: "music", mechanic: "sequence-recall", ages: { min: 6, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "melody", palette: P, mascotId: "ziggy", contentKey: "mus-melody" } },
  { id: "mus-sort-205", title: "Instrument Family Sort", description: "Sort instruments into strings, brass, woodwind, percussion", icon: "🎻", gradient: "from-emerald-400 to-teal-500", category: "music", mechanic: "drag-sort", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "instruments", palette: P, mascotId: "pixel", contentKey: "mus-instruments" } },
  { id: "mus-pattern-206", title: "Chord Pattern", description: "Complete chord progression patterns", icon: "🎸", gradient: "from-lime-400 to-green-500", category: "music", mechanic: "pattern-complete", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "harmony", palette: P, mascotId: "blaze", contentKey: "mus-chords" } },
  { id: "mus-timeline-207", title: "Music History Timeline", description: "Order music genres and composers chronologically", icon: "📅", gradient: "from-fuchsia-400 to-pink-500", category: "music", mechanic: "timeline", ages: { min: 9, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-history", palette: P, mascotId: "luna", contentKey: "mus-history" } },
  { id: "mus-crossword-208", title: "Music Vocab Crossword", description: "Fill in musical terms in a crossword", icon: "✏️", gradient: "from-cyan-400 to-sky-500", category: "music", mechanic: "crossword", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-vocab", palette: P, mascotId: "hero", contentKey: "mus-cross" } },
  { id: "mus-match-209", title: "Music Note Match 3", description: "Match musical notes in a colorful gem grid", icon: "🎵", gradient: "from-rose-400 to-pink-500", category: "music", mechanic: "match-three", ages: { min: 5, max: 10 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "notes", palette: P, mascotId: "dash", contentKey: "mus-match" } },
  { id: "mus-word-210", title: "Music Word Hunt", description: "Find musical terms hidden in the letter grid", icon: "🔍", gradient: "from-indigo-400 to-blue-500", category: "music", mechanic: "word-search", ages: { min: 7, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-vocab", palette: P, mascotId: "echo", contentKey: "mus-wordsearch" } },
  { id: "mus-jigsaw-211", title: "Album Art Jigsaw", description: "Assemble classic album artwork puzzles", icon: "🧩", gradient: "from-amber-400 to-orange-500", category: "music", mechanic: "jigsaw", ages: { min: 6, max: 12 }, eduWeight: 65, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-culture", palette: P, mascotId: "kody", contentKey: "mus-jigsaw" } },
  { id: "mus-catch-212", title: "Note Catcher", description: "Catch the correct musical notes as they fall", icon: "🎼", gradient: "from-teal-400 to-emerald-500", category: "music", mechanic: "falling-catch", ages: { min: 5, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "note-reading", palette: P, mascotId: "sparkle", contentKey: "mus-catch" } },
  { id: "mus-maze-213", title: "Sound Wave Maze", description: "Navigate through sound waves to reach the concert hall", icon: "🔊", gradient: "from-violet-400 to-purple-500", category: "music", mechanic: "maze-runner", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sound", palette: P, mascotId: "nova", contentKey: "mus-soundmaze" } },
  { id: "mus-typing-214", title: "Lyrics Typing Race", description: "Type famous song lyrics before time runs out", icon: "⌨️", gradient: "from-pink-400 to-rose-500", category: "music", mechanic: "typing-race", ages: { min: 8, max: 16 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "lyrics", palette: P, mascotId: "ziggy", contentKey: "mus-lyrics" } },
  { id: "mus-builder-215", title: "Song Builder", description: "Build songs by arranging musical sections", icon: "🎹", gradient: "from-emerald-400 to-teal-500", category: "music", mechanic: "builder", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "composition", palette: P, mascotId: "pixel", contentKey: "mus-compose" } },
  { id: "mus-connect-216", title: "Staff Connect", description: "Connect notes on the musical staff in order", icon: "🎶", gradient: "from-sky-400 to-blue-500", category: "music", mechanic: "connect-dots", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "notation", palette: P, mascotId: "blaze", contentKey: "mus-staff" } },
  { id: "mus-tower-217", title: "Harmony Tower", description: "Stack harmonizing notes to build chords", icon: "🏗️", gradient: "from-amber-400 to-orange-500", category: "music", mechanic: "tower-stack", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "harmony", palette: P, mascotId: "luna", contentKey: "mus-harmony" } },
  { id: "mus-platform-218", title: "Music Land Platformer", description: "Jump through a musical world collecting notes", icon: "🎮", gradient: "from-fuchsia-400 to-pink-500", category: "music", mechanic: "platformer", ages: { min: 5, max: 10 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-fun", palette: P, mascotId: "hero", contentKey: "mus-land" } },
  { id: "mus-runner-219", title: "Tempo Runner", description: "Run at different tempos — allegro, andante, adagio", icon: "🏃", gradient: "from-lime-400 to-green-500", category: "music", mechanic: "infinite-runner", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "tempo", palette: P, mascotId: "dash", contentKey: "mus-tempo" } },
  { id: "mus-color-220", title: "Synesthesia Paint", description: "Color sounds — paint what you hear", icon: "🎨", gradient: "from-rainbow-400 to-pink-500", category: "music", mechanic: "color-fill", ages: { min: 5, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "synesthesia", palette: P, mascotId: "echo", contentKey: "mus-color" } },
  { id: "mus-scale-221", title: "Dynamic Balance", description: "Balance forte and piano dynamics on a scale", icon: "⚖️", gradient: "from-rose-400 to-pink-500", category: "music", mechanic: "balance-scale", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "dynamics", palette: P, mascotId: "kody", contentKey: "mus-dynamics" } },
  { id: "mus-slide-222", title: "Scale Slide Puzzle", description: "Slide notes into the correct scale order", icon: "🎵", gradient: "from-cyan-400 to-sky-500", category: "music", mechanic: "slide-puzzle", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "scales", palette: P, mascotId: "sparkle", contentKey: "mus-scale" } },
  { id: "mus-code-223", title: "Music Code Composer", description: "Program musical sequences with coding blocks", icon: "💻", gradient: "from-indigo-400 to-blue-500", category: "music", mechanic: "coding-blocks", ages: { min: 8, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "algorithmic-music", palette: P, mascotId: "nova", contentKey: "mus-code" } },
  { id: "mus-explorer-224", title: "World Music Explorer", description: "Travel the world discovering music traditions", icon: "🗺️", gradient: "from-teal-400 to-emerald-500", category: "music", mechanic: "map-explorer", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "world-music", palette: P, mascotId: "ziggy", contentKey: "mus-world" } },
  { id: "mus-bubble-225", title: "Music Fact Pop", description: "Pop bubbles with correct music facts", icon: "🫧", gradient: "from-violet-400 to-purple-500", category: "music", mechanic: "math-pop", ages: { min: 7, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "music-facts", palette: P, mascotId: "pixel", contentKey: "mus-pop" } },
];
