/* -------------------------------------------------------------------------- */
/*  Koydo 300-Game Catalog — Part 1: Math, Literacy, Science, Geography     */
/*  75 game definitions (IDs 001–075)                                        */
/* -------------------------------------------------------------------------- */
import type { GameDefinition } from "../types";

const P = ["#fbbf24", "#f472b6", "#34d399", "#60a5fa", "#a78bfa"] as const;

export const CATALOG_PART1: GameDefinition[] = [
  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  MATH (001-025)                                                        */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "math-candy-calc-001", title: "Candy Calc Crunch", description: "Match number candies in sweet arithmetic combos", icon: "🍬", gradient: "from-pink-400 to-rose-500", category: "math", mechanic: "match-three", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "arithmetic", palette: P, mascotId: "kody", contentKey: "math-match" } },
  { id: "math-quiz-blitz-002", title: "Math Quiz Blitz", description: "Race the clock answering rapid-fire math questions", icon: "⚡", gradient: "from-amber-400 to-orange-500", category: "math", mechanic: "quiz-race", ages: { min: 7, max: 12 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "arithmetic", palette: P, mascotId: "sparkle", contentKey: "math-quiz" } },
  { id: "math-bubble-pop-003", title: "Math Bubble Pop", description: "Pop the bubbles carrying the right answers", icon: "🫧", gradient: "from-sky-400 to-blue-500", category: "math", mechanic: "math-pop", ages: { min: 6, max: 10 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "arithmetic", palette: P, mascotId: "nova", contentKey: "math-bubble" } },
  { id: "math-balance-004", title: "Equation Balance", description: "Place weights to balance math equations", icon: "⚖️", gradient: "from-emerald-400 to-teal-500", category: "math", mechanic: "balance-scale", ages: { min: 7, max: 12 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "algebra", palette: P, mascotId: "ziggy", contentKey: "math-balance" } },
  { id: "math-pattern-005", title: "Number Pattern Master", description: "Complete number sequences and patterns", icon: "🔢", gradient: "from-violet-400 to-purple-500", category: "math", mechanic: "pattern-complete", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sequences", palette: P, mascotId: "pixel", contentKey: "math-pattern" } },
  { id: "math-sort-006", title: "Number Sort Challenge", description: "Sort numbers into the right categories", icon: "📊", gradient: "from-fuchsia-400 to-pink-500", category: "math", mechanic: "drag-sort", ages: { min: 6, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "number-sense", palette: P, mascotId: "blaze", contentKey: "math-sort" } },
  { id: "math-memory-007", title: "Math Fact Memory", description: "Flip cards to match equations with answers", icon: "🧠", gradient: "from-rose-400 to-pink-500", category: "math", mechanic: "memory-flip", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "multiplication", palette: P, mascotId: "luna", contentKey: "math-memory" } },
  { id: "math-tower-008", title: "Addition Tower", description: "Stack blocks by solving addition problems", icon: "🏗️", gradient: "from-lime-400 to-green-500", category: "math", mechanic: "tower-stack", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "addition", palette: P, mascotId: "hero", contentKey: "math-tower" } },
  { id: "math-runner-009", title: "Multiplication Runner", description: "Run and collect the correct multiplication answers", icon: "🏃", gradient: "from-cyan-400 to-sky-500", category: "math", mechanic: "infinite-runner", ages: { min: 8, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "multiplication", palette: P, mascotId: "dash", contentKey: "math-runner" } },
  { id: "math-slide-010", title: "Fraction Slide Puzzle", description: "Slide tiles to arrange fractions in order", icon: "🧩", gradient: "from-indigo-400 to-blue-500", category: "math", mechanic: "slide-puzzle", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "fractions", palette: P, mascotId: "echo", contentKey: "math-slide" } },
  { id: "math-maze-011", title: "Math Maze Explorer", description: "Navigate the maze collecting correct answers", icon: "🔢", gradient: "from-red-400 to-rose-500", category: "math", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mixed-ops", palette: P, mascotId: "kody", contentKey: "math-maze" } },
  { id: "math-typing-012", title: "Speed Math Typing", description: "Type answers as fast as you can before they fall", icon: "⌨️", gradient: "from-yellow-400 to-amber-500", category: "math", mechanic: "typing-race", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mental-math", palette: P, mascotId: "sparkle", contentKey: "math-type" } },
  { id: "math-catch-013", title: "Falling Numbers", description: "Catch the correct numbers as they fall from the sky", icon: "🌧️", gradient: "from-teal-400 to-emerald-500", category: "math", mechanic: "falling-catch", ages: { min: 5, max: 9 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "counting", palette: P, mascotId: "nova", contentKey: "math-catch" } },
  { id: "math-sequence-014", title: "Math Sequence Simon", description: "Remember and repeat the math sequence", icon: "🔔", gradient: "from-amber-400 to-orange-500", category: "math", mechanic: "sequence-recall", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "sequences", palette: P, mascotId: "ziggy", contentKey: "math-seq" } },
  { id: "math-platform-015", title: "Platform Equations", description: "Jump through platforms solving equations", icon: "🎮", gradient: "from-emerald-400 to-teal-500", category: "math", mechanic: "platformer", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "equations", palette: P, mascotId: "pixel", contentKey: "math-platform" } },
  { id: "math-connect-016", title: "Connect the Dots: Graphs", description: "Connect numbered dots to form math graphs", icon: "📈", gradient: "from-sky-400 to-blue-500", category: "math", mechanic: "connect-dots", ages: { min: 9, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "geometry", palette: P, mascotId: "blaze", contentKey: "math-dots" } },
  { id: "math-timeline-017", title: "Math History Timeline", description: "Order famous math discoveries chronologically", icon: "📅", gradient: "from-violet-400 to-purple-500", category: "math", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "math-history", palette: P, mascotId: "luna", contentKey: "math-time" } },
  { id: "math-jigsaw-018", title: "Geometry Jigsaw", description: "Assemble geometric shape puzzles", icon: "📐", gradient: "from-pink-400 to-rose-500", category: "math", mechanic: "jigsaw", ages: { min: 6, max: 10 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "geometry", palette: P, mascotId: "hero", contentKey: "math-jigsaw" } },
  { id: "math-crossword-019", title: "Math Crossword", description: "Fill in crossword grids with math answers", icon: "✏️", gradient: "from-lime-400 to-green-500", category: "math", mechanic: "crossword", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "dash", contentKey: "math-cross" } },
  { id: "math-rhythm-020", title: "Rhythm Multiplication", description: "Tap multiplication answers to the beat", icon: "🎵", gradient: "from-fuchsia-400 to-pink-500", category: "math", mechanic: "rhythm-tap", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "multiplication", palette: P, mascotId: "echo", contentKey: "math-rhythm" } },
  { id: "math-color-021", title: "Color by Number", description: "Color regions using math-answer colors", icon: "🎨", gradient: "from-rose-400 to-pink-500", category: "math", mechanic: "color-fill", ages: { min: 5, max: 9 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "counting", palette: P, mascotId: "kody", contentKey: "math-color" } },
  { id: "math-code-022", title: "Code the Calculator", description: "Program blocks to solve math challenges", icon: "💻", gradient: "from-indigo-400 to-blue-500", category: "math", mechanic: "coding-blocks", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "computational-math", palette: P, mascotId: "sparkle", contentKey: "math-code" } },
  { id: "math-word-search-023", title: "Math Terms Search", description: "Find hidden math vocabulary words", icon: "🔍", gradient: "from-teal-400 to-emerald-500", category: "math", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 65, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "math-vocab", palette: P, mascotId: "nova", contentKey: "math-wordsearch" } },
  { id: "math-builder-024", title: "Shape Builder", description: "Build geometric shapes to match targets", icon: "🔺", gradient: "from-amber-400 to-orange-500", category: "math", mechanic: "builder", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "geometry", palette: P, mascotId: "ziggy", contentKey: "math-build" } },
  { id: "math-explorer-025", title: "Math Land Explorer", description: "Explore a math world solving problems at each stop", icon: "🗺️", gradient: "from-cyan-400 to-sky-500", category: "math", mechanic: "map-explorer", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "mixed-math", palette: P, mascotId: "pixel", contentKey: "math-explore" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  LITERACY (026-050)                                                    */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "lit-word-search-026", title: "Word Explorer", description: "Find hidden words in a bustling letter grid", icon: "🔍", gradient: "from-sky-400 to-blue-500", category: "literacy", mechanic: "word-search", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "kody", contentKey: "lit-ws-animals" } },
  { id: "lit-typing-027", title: "Typing Adventure", description: "Type words before they hit the ground", icon: "⌨️", gradient: "from-emerald-400 to-teal-500", category: "literacy", mechanic: "typing-race", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "typing", palette: P, mascotId: "sparkle", contentKey: "lit-typing" } },
  { id: "lit-crossword-028", title: "Vocabulary Crossword", description: "Solve crossword puzzles with vocabulary clues", icon: "✏️", gradient: "from-violet-400 to-purple-500", category: "literacy", mechanic: "crossword", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "nova", contentKey: "lit-crossword" } },
  { id: "lit-memory-029", title: "Synonym Match", description: "Flip cards to match words with their synonyms", icon: "🧠", gradient: "from-pink-400 to-rose-500", category: "literacy", mechanic: "memory-flip", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "synonyms", palette: P, mascotId: "ziggy", contentKey: "lit-synonym" } },
  { id: "lit-sort-030", title: "Parts of Speech Sort", description: "Sort words into nouns, verbs, and adjectives", icon: "📋", gradient: "from-amber-400 to-orange-500", category: "literacy", mechanic: "drag-sort", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "grammar", palette: P, mascotId: "pixel", contentKey: "lit-grammar" } },
  { id: "lit-catch-031", title: "Letter Catcher", description: "Catch falling letters to spell words", icon: "🔤", gradient: "from-lime-400 to-green-500", category: "literacy", mechanic: "falling-catch", ages: { min: 5, max: 9 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spelling", palette: P, mascotId: "blaze", contentKey: "lit-catch" } },
  { id: "lit-quiz-032", title: "Spelling Bee Race", description: "Race to spell words correctly", icon: "🐝", gradient: "from-yellow-400 to-amber-500", category: "literacy", mechanic: "quiz-race", ages: { min: 6, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spelling", palette: P, mascotId: "luna", contentKey: "lit-spelling" } },
  { id: "lit-match-033", title: "Letter Gem Match", description: "Match letter gems to form words", icon: "💎", gradient: "from-fuchsia-400 to-pink-500", category: "literacy", mechanic: "match-three", ages: { min: 5, max: 9 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "letters", palette: P, mascotId: "hero", contentKey: "lit-match" } },
  { id: "lit-pattern-034", title: "Word Pattern Complete", description: "Complete word patterns and rhymes", icon: "🔁", gradient: "from-teal-400 to-emerald-500", category: "literacy", mechanic: "pattern-complete", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phonics", palette: P, mascotId: "dash", contentKey: "lit-pattern" } },
  { id: "lit-maze-035", title: "Story Maze", description: "Navigate a maze to build a story", icon: "📖", gradient: "from-rose-400 to-pink-500", category: "literacy", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "storytelling", palette: P, mascotId: "echo", contentKey: "lit-story" } },
  { id: "lit-slide-036", title: "ABC Slide Puzzle", description: "Slide letters into alphabetical order", icon: "🔠", gradient: "from-indigo-400 to-blue-500", category: "literacy", mechanic: "slide-puzzle", ages: { min: 5, max: 8 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "alphabet", palette: P, mascotId: "kody", contentKey: "lit-slide" } },
  { id: "lit-jigsaw-037", title: "Story Scene Jigsaw", description: "Assemble jigsaw tiles to reveal story scenes", icon: "🧩", gradient: "from-violet-400 to-purple-500", category: "literacy", mechanic: "jigsaw", ages: { min: 5, max: 9 }, eduWeight: 65, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "reading", palette: P, mascotId: "sparkle", contentKey: "lit-jigsaw" } },
  { id: "lit-tower-038", title: "Word Tower", description: "Stack word blocks to build the tallest tower", icon: "🏢", gradient: "from-cyan-400 to-sky-500", category: "literacy", mechanic: "tower-stack", ages: { min: 6, max: 10 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "vocabulary", palette: P, mascotId: "nova", contentKey: "lit-tower" } },
  { id: "lit-connect-039", title: "Story Dots", description: "Connect dots to reveal story illustrations", icon: "✏️", gradient: "from-amber-400 to-orange-500", category: "literacy", mechanic: "connect-dots", ages: { min: 5, max: 8 }, eduWeight: 60, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "stories", palette: P, mascotId: "ziggy", contentKey: "lit-dots" } },
  { id: "lit-platform-040", title: "Phonics Platformer", description: "Jump through platforms collecting phonics sounds", icon: "🎮", gradient: "from-emerald-400 to-teal-500", category: "literacy", mechanic: "platformer", ages: { min: 5, max: 8 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phonics", palette: P, mascotId: "pixel", contentKey: "lit-phonics" } },
  { id: "lit-sequence-041", title: "Alphabet Sequence", description: "Remember the alphabet sequence — Simon Says style", icon: "🔔", gradient: "from-pink-400 to-rose-500", category: "literacy", mechanic: "sequence-recall", ages: { min: 5, max: 8 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "alphabet", palette: P, mascotId: "blaze", contentKey: "lit-abc-seq" } },
  { id: "lit-runner-042", title: "Reading Runner", description: "Run and collect words to complete sentences", icon: "🏃", gradient: "from-sky-400 to-blue-500", category: "literacy", mechanic: "infinite-runner", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "reading", palette: P, mascotId: "luna", contentKey: "lit-runner" } },
  { id: "lit-rhythm-043", title: "Poetry Rhythm", description: "Tap syllables to the rhythm of poems", icon: "🎼", gradient: "from-fuchsia-400 to-pink-500", category: "literacy", mechanic: "rhythm-tap", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "poetry", palette: P, mascotId: "hero", contentKey: "lit-rhythm" } },
  { id: "lit-color-044", title: "Vowel Color Map", description: "Color words by their vowel sounds", icon: "🎨", gradient: "from-lime-400 to-green-500", category: "literacy", mechanic: "color-fill", ages: { min: 5, max: 9 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "phonics", palette: P, mascotId: "dash", contentKey: "lit-vowel" } },
  { id: "lit-code-045", title: "Story Code Builder", description: "Program blocks to tell interactive stories", icon: "💻", gradient: "from-violet-400 to-purple-500", category: "literacy", mechanic: "coding-blocks", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "creative-writing", palette: P, mascotId: "echo", contentKey: "lit-code" } },
  { id: "lit-timeline-046", title: "Literary Timeline", description: "Order famous stories by publication date", icon: "📅", gradient: "from-rose-400 to-pink-500", category: "literacy", mechanic: "timeline", ages: { min: 10, max: 16 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "literature", palette: P, mascotId: "kody", contentKey: "lit-time" } },
  { id: "lit-explorer-047", title: "Book World Explorer", description: "Travel the world exploring famous literary settings", icon: "🗺️", gradient: "from-amber-400 to-orange-500", category: "literacy", mechanic: "map-explorer", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "literature", palette: P, mascotId: "sparkle", contentKey: "lit-explore" } },
  { id: "lit-builder-048", title: "Sentence Builder", description: "Build correct sentences from word blocks", icon: "🧱", gradient: "from-teal-400 to-emerald-500", category: "literacy", mechanic: "builder", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "grammar", palette: P, mascotId: "nova", contentKey: "lit-sentence" } },
  { id: "lit-bubble-049", title: "Word Pop", description: "Pop bubbles containing correctly spelled words", icon: "🫧", gradient: "from-cyan-400 to-sky-500", category: "literacy", mechanic: "math-pop", ages: { min: 6, max: 10 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "spelling", palette: P, mascotId: "ziggy", contentKey: "lit-pop" } },
  { id: "lit-lab-050", title: "Word Alchemy", description: "Combine root words and suffixes to create new words", icon: "🧪", gradient: "from-indigo-400 to-blue-500", category: "literacy", mechanic: "element-lab", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "morphology", palette: P, mascotId: "pixel", contentKey: "lit-alchemy" } },

  /* ═══════════════════════════════════════════════════════════════════════ */
  /*  SCIENCE (051-075)                                                     */
  /* ═══════════════════════════════════════════════════════════════════════ */
  { id: "sci-quiz-051", title: "Science Quiz Rush", description: "Answer science questions at lightning speed", icon: "⚡", gradient: "from-emerald-400 to-teal-500", category: "science", mechanic: "quiz-race", ages: { min: 7, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "general-science", palette: P, mascotId: "kody", contentKey: "sci-quiz" } },
  { id: "sci-sort-052", title: "Living vs Non-Living", description: "Sort items into living and non-living categories", icon: "🌱", gradient: "from-lime-400 to-green-500", category: "science", mechanic: "drag-sort", ages: { min: 5, max: 9 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biology", palette: P, mascotId: "sparkle", contentKey: "sci-living" } },
  { id: "sci-memory-053", title: "Body Part Pairs", description: "Match organs with their functions", icon: "🫀", gradient: "from-red-400 to-rose-500", category: "science", mechanic: "memory-flip", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "anatomy", palette: P, mascotId: "nova", contentKey: "sci-body" } },
  { id: "sci-match-054", title: "Cell Match 3", description: "Match cell components in a Candy Crush-style grid", icon: "🔬", gradient: "from-violet-400 to-purple-500", category: "science", mechanic: "match-three", ages: { min: 8, max: 14 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biology", palette: P, mascotId: "ziggy", contentKey: "sci-cell" } },
  { id: "sci-maze-055", title: "Digestive System Maze", description: "Navigate food through the digestive system", icon: "🍎", gradient: "from-amber-400 to-orange-500", category: "science", mechanic: "maze-runner", ages: { min: 7, max: 12 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biology", palette: P, mascotId: "pixel", contentKey: "sci-digest" } },
  { id: "sci-catch-056", title: "DNA Nucleotide Catcher", description: "Catch the right DNA bases as they fall", icon: "🧬", gradient: "from-sky-400 to-blue-500", category: "science", mechanic: "falling-catch", ages: { min: 10, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "genetics", palette: P, mascotId: "blaze", contentKey: "sci-dna" } },
  { id: "sci-pattern-057", title: "Periodic Patterns", description: "Complete patterns in the periodic table", icon: "⚛️", gradient: "from-fuchsia-400 to-pink-500", category: "science", mechanic: "pattern-complete", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chemistry", palette: P, mascotId: "luna", contentKey: "sci-periodic" } },
  { id: "sci-platform-058", title: "Ecosystem Explorer", description: "Jump through ecosystems collecting species", icon: "🌿", gradient: "from-green-400 to-emerald-500", category: "science", mechanic: "platformer", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "ecology", palette: P, mascotId: "hero", contentKey: "sci-eco" } },
  { id: "sci-timeline-059", title: "Science Discovery Timeline", description: "Order scientific discoveries from oldest to newest", icon: "📅", gradient: "from-teal-400 to-emerald-500", category: "science", mechanic: "timeline", ages: { min: 9, max: 16 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "science-history", palette: P, mascotId: "dash", contentKey: "sci-time" } },
  { id: "sci-jigsaw-060", title: "Solar System Jigsaw", description: "Assemble the solar system puzzle", icon: "🪐", gradient: "from-indigo-400 to-blue-500", category: "science", mechanic: "jigsaw", ages: { min: 6, max: 12 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "astronomy", palette: P, mascotId: "echo", contentKey: "sci-solar" } },
  { id: "sci-connect-061", title: "Constellation Dots", description: "Connect dots to form constellations", icon: "⭐", gradient: "from-pink-400 to-rose-500", category: "science", mechanic: "connect-dots", ages: { min: 7, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "astronomy", palette: P, mascotId: "kody", contentKey: "sci-stars" } },
  { id: "sci-color-062", title: "Anatomy Coloring", description: "Color body systems with the correct colors", icon: "🎨", gradient: "from-rose-400 to-pink-500", category: "science", mechanic: "color-fill", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "anatomy", palette: P, mascotId: "sparkle", contentKey: "sci-anatomy" } },
  { id: "sci-tower-063", title: "Food Chain Tower", description: "Stack organisms in the correct food chain order", icon: "🏗️", gradient: "from-lime-400 to-green-500", category: "science", mechanic: "tower-stack", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "ecology", palette: P, mascotId: "nova", contentKey: "sci-foodchain" } },
  { id: "sci-slide-064", title: "Planet Order Slide", description: "Slide planets into correct orbital order", icon: "🌍", gradient: "from-cyan-400 to-sky-500", category: "science", mechanic: "slide-puzzle", ages: { min: 6, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "astronomy", palette: P, mascotId: "ziggy", contentKey: "sci-planets" } },
  { id: "sci-runner-065", title: "Photosynthesis Runner", description: "Run collecting sunlight, water, and CO₂ for photosynthesis", icon: "🌻", gradient: "from-yellow-400 to-amber-500", category: "science", mechanic: "infinite-runner", ages: { min: 8, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biology", palette: P, mascotId: "pixel", contentKey: "sci-photo" } },
  { id: "sci-crossword-066", title: "Science Vocabulary Crossword", description: "Fill in scientific terms in a crossword", icon: "✏️", gradient: "from-violet-400 to-purple-500", category: "science", mechanic: "crossword", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "science-vocab", palette: P, mascotId: "blaze", contentKey: "sci-cross" } },
  { id: "sci-word-067", title: "Science Word Hunt", description: "Find scientific terms hidden in the grid", icon: "🔍", gradient: "from-amber-400 to-orange-500", category: "science", mechanic: "word-search", ages: { min: 8, max: 14 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "science-vocab", palette: P, mascotId: "luna", contentKey: "sci-wordsearch" } },
  { id: "sci-sequence-068", title: "Mitosis Sequence", description: "Remember the stages of cell division", icon: "🔬", gradient: "from-emerald-400 to-teal-500", category: "science", mechanic: "sequence-recall", ages: { min: 10, max: 16 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "biology", palette: P, mascotId: "hero", contentKey: "sci-mitosis" } },
  { id: "sci-typing-069", title: "Element Typing Race", description: "Type element names before they reach the bottom", icon: "⌨️", gradient: "from-sky-400 to-blue-500", category: "science", mechanic: "typing-race", ages: { min: 9, max: 16 }, eduWeight: 75, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chemistry", palette: P, mascotId: "dash", contentKey: "sci-typing" } },
  { id: "sci-balance-070", title: "Chemical Equation Balance", description: "Balance chemical equations on a scale", icon: "⚖️", gradient: "from-fuchsia-400 to-pink-500", category: "science", mechanic: "balance-scale", ages: { min: 10, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chemistry", palette: P, mascotId: "echo", contentKey: "sci-chem-bal" } },
  { id: "sci-bubble-071", title: "Science Fact Pop", description: "Pop bubbles with correct science facts", icon: "🫧", gradient: "from-teal-400 to-emerald-500", category: "science", mechanic: "math-pop", ages: { min: 7, max: 12 }, eduWeight: 80, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "general-science", palette: P, mascotId: "kody", contentKey: "sci-pop" } },
  { id: "sci-code-072", title: "Robot Scientist", description: "Program a lab robot to run experiments", icon: "🤖", gradient: "from-indigo-400 to-blue-500", category: "science", mechanic: "coding-blocks", ages: { min: 8, max: 14 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "scientific-method", palette: P, mascotId: "sparkle", contentKey: "sci-robot" } },
  { id: "sci-rhythm-073", title: "Heartbeat Rhythm", description: "Tap to the rhythm of heartbeat patterns", icon: "💓", gradient: "from-red-400 to-rose-500", category: "science", mechanic: "rhythm-tap", ages: { min: 7, max: 12 }, eduWeight: 70, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "anatomy", palette: P, mascotId: "nova", contentKey: "sci-heart" } },
  { id: "sci-builder-074", title: "Molecule Builder", description: "Build molecules from atomic building blocks", icon: "⚛️", gradient: "from-lime-400 to-green-500", category: "science", mechanic: "builder", ages: { min: 9, max: 16 }, eduWeight: 90, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "chemistry", palette: P, mascotId: "ziggy", contentKey: "sci-molecule" } },
  { id: "sci-explorer-075", title: "Space Explorer", description: "Explore planets and moons collecting data", icon: "🚀", gradient: "from-violet-400 to-purple-500", category: "science", mechanic: "map-explorer", ages: { min: 7, max: 14 }, eduWeight: 85, ageLock: false, safeForChildren: true, levels: 0, themeConfig: { subject: "astronomy", palette: P, mascotId: "pixel", contentKey: "sci-space" } },
];
