/**
 * CDL Test Question Bank
 *
 * Comprehensive question database covering all CDL test sections.
 * Based on FMCSA federal CDL testing standards (same in all 50 states).
 * Passing score: 80% in every state.
 *
 * Sections:
 *   - General Knowledge (50+ questions)
 *   - Air Brakes (50+ questions)
 *   - Combination Vehicles (30+ questions)
 *   - Hazmat (30+ questions)
 *   - Tanker (20+ questions)
 *   - Doubles/Triples (20+ questions)
 *   - Passenger (20+ questions)
 *   - School Bus (20+ questions)
 */

export type CdlQuestion = {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  section: string;
  /** Optional diagram reference for visual questions */
  diagramRef?: string;
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GENERAL KNOWLEDGE (50+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const GENERAL_KNOWLEDGE_QUESTIONS: CdlQuestion[] = [
  // ── Safe Driving ──────────────────────────────────────────────────────────
  {
    id: "gk-001",
    question: "You are driving a 60-foot truck at 55 mph. What is the minimum safe following distance?",
    options: ["4 seconds", "5 seconds", "6 seconds", "7 seconds"],
    correctIndex: 3,
    explanation: "At speeds above 40 mph, use the formula: 1 second per 10 feet of vehicle length, plus 1 extra second. For a 60-foot truck: 6 + 1 = 7 seconds.",
    section: "Safe Driving",
  },
  {
    id: "gk-002",
    question: "The most common cause of truck rollovers is:",
    options: ["Tire blowout", "Excessive speed in curves", "Brake failure", "Wind gusts"],
    correctIndex: 1,
    explanation: "The number one cause of truck rollovers is entering a curve or ramp too fast. Loaded trucks have a high center of gravity that makes them especially vulnerable to lateral forces in turns.",
    section: "Safe Driving",
  },
  {
    id: "gk-003",
    question: "Which side of a commercial vehicle has the largest blind spot (No-Zone)?",
    options: ["The front", "The left side", "The right side", "The rear"],
    correctIndex: 2,
    explanation: "The right-side No-Zone extends approximately two full lanes, making it the largest and most dangerous blind spot. Always check your right mirror carefully before turning right.",
    section: "Safe Driving",
  },
  {
    id: "gk-004",
    question: "When making a right turn in a large truck, you should:",
    options: [
      "Swing wide to the left before turning right",
      "Turn from the right lane and stay in the right lane",
      "Keep the rear of the vehicle close to the curb",
      "Turn wide as you complete the turn to avoid off-tracking",
    ],
    correctIndex: 3,
    explanation: "Due to off-tracking, the rear wheels follow a shorter path than the front wheels. Turn wide as you complete the turn. Never swing left to make a right turn — this creates a squeeze point for other vehicles.",
    section: "Safe Driving",
  },
  {
    id: "gk-005",
    question: "What is the proper technique for downhill braking in a truck?",
    options: [
      "Apply brakes continuously on the downgrade",
      "Apply brakes hard when speed is 5 mph above target, release when back at target",
      "Use engine braking only — never touch the brake pedal",
      "Pump the brakes rapidly to keep them cool",
    ],
    correctIndex: 1,
    explanation: "Use the 'snub braking' technique: apply brakes firmly when speed is 5 mph above your safe speed, then release until speed builds again. This allows brakes to cool between applications and prevents brake fade.",
    section: "Safe Driving",
  },
  {
    id: "gk-006",
    question: "When driving at night, your headlights typically illuminate the road about:",
    options: ["100 feet ahead", "250 feet ahead", "350 feet ahead", "500 feet ahead"],
    correctIndex: 2,
    explanation: "Low-beam headlights illuminate roughly 250 feet and high beams about 350-500 feet. At 55 mph it takes over 400 feet to stop, meaning you may overdrive your headlights. Reduce speed so you can stop within the illuminated distance.",
    section: "Safe Driving",
  },
  {
    id: "gk-007",
    question: "Hydroplaning can begin at speeds as low as:",
    options: ["15 mph", "20 mph", "30 mph", "45 mph"],
    correctIndex: 2,
    explanation: "Hydroplaning can begin at speeds as low as 30 mph when water accumulates on the road surface. It is more likely with worn tires. Slow down when it rains.",
    section: "Safe Driving",
  },
  {
    id: "gk-008",
    question: "What is the total stopping distance for a truck traveling at 55 mph on dry pavement?",
    options: ["About 200 feet", "About 300 feet", "About 400 feet", "About 600 feet"],
    correctIndex: 2,
    explanation: "At 55 mph: perception distance (~60 ft) + reaction distance (~60 ft) + braking distance (~280 ft) = approximately 400 feet. At higher speeds or wet conditions, this increases dramatically.",
    section: "Safe Driving",
  },
  {
    id: "gk-009",
    question: "When meeting an oncoming vehicle at night, you should dim your headlights within:",
    options: ["200 feet", "300 feet", "500 feet", "1,000 feet"],
    correctIndex: 2,
    explanation: "Dim your headlights within 500 feet of an oncoming vehicle. Also dim within 500 feet when following another vehicle to avoid blinding them through their mirrors.",
    section: "Safe Driving",
  },
  {
    id: "gk-010",
    question: "You should NOT use your horn to:",
    options: [
      "Alert a pedestrian who appears to be walking into your path",
      "Express frustration with another driver",
      "Warn other drivers when you are passing",
      "Alert a driver who is drifting into your lane",
    ],
    correctIndex: 1,
    explanation: "Never use your horn aggressively or out of frustration. Use it only to alert others to potential danger — such as warning pedestrians, alerting drifting drivers, or signaling your presence when passing.",
    section: "Safe Driving",
  },
  {
    id: "gk-011",
    question: "Counter-steering means:",
    options: [
      "Turning the wheel quickly in the opposite direction of a skid",
      "Turning the wheel in the direction you want the front of the vehicle to go",
      "Applying opposite lock on the steering wheel and braking hard",
      "Steering into the oncoming lane to avoid an obstacle",
    ],
    correctIndex: 1,
    explanation: "Counter-steering means turning the wheel in the direction you want the front of the vehicle to go. In a rear-wheel skid, this means turning toward the skid. Once the vehicle straightens, counter-steer again as needed.",
    section: "Safe Driving",
  },
  {
    id: "gk-012",
    question: "When driving on slippery surfaces, you should turn and brake:",
    options: [
      "At the same time for maximum control",
      "As gently as possible, never simultaneously",
      "Hard to get through the slippery section quickly",
      "Only using the engine brake/retarder",
    ],
    correctIndex: 1,
    explanation: "On slippery roads, any sudden action can cause a skid. Make turns as gently as possible, and never brake while turning. Reduce speed before the turn.",
    section: "Safe Driving",
  },

  // ── Vehicle Inspection ────────────────────────────────────────────────────
  {
    id: "gk-013",
    question: "During a pre-trip inspection, what is the minimum tread depth for steer tires?",
    options: ["2/32 inch", "3/32 inch", "4/32 inch", "6/32 inch"],
    correctIndex: 2,
    explanation: "Federal regulations require a minimum tread depth of 4/32 inch on steer (front) tires. All other tires require a minimum of 2/32 inch.",
    section: "Vehicle Inspection",
    diagramRef: "/assets/cdl/brake-wheel-assembly.png",
  },
  {
    id: "gk-014",
    question: "Rust streaks around wheel lug nuts indicate:",
    options: ["Normal weathering", "The nuts may be loose", "The wheel has been repainted", "Excessive brake dust"],
    correctIndex: 1,
    explanation: "Rust trails or streaks radiating outward from lug nuts indicate the nuts are loose — the slight movement creates friction that produces rust. This is an important pre-trip check.",
    section: "Vehicle Inspection",
  },
  {
    id: "gk-015",
    question: "What should you check for when inspecting the exhaust system?",
    options: [
      "That the muffler is chrome",
      "Leaks, damage, and proper mounting — especially under the cab",
      "Only the tailpipe exit position",
      "The catalytic converter temperature",
    ],
    correctIndex: 1,
    explanation: "Check for loose, broken, or missing exhaust parts; leaks from pipes, manifold, or muffler; exhaust system parts rubbing against fuel system parts or tires. Carbon monoxide can leak into the cab from a damaged exhaust system.",
    section: "Vehicle Inspection",
  },
  {
    id: "gk-016",
    question: "How do you test the parking brake during a pre-trip?",
    options: [
      "Pull the knob and drive forward slowly",
      "Set the parking brake, put in gear, gently apply throttle — vehicle should not move",
      "Release the parking brake and check the warning light",
      "Listen for the air release sound when applied",
    ],
    correctIndex: 1,
    explanation: "With the parking brake applied, put the vehicle in a low gear and gently apply the throttle. The vehicle should hold and not move. If it moves, the parking brake is defective.",
    section: "Vehicle Inspection",
    diagramRef: "/assets/cdl/cab-dashboard.png",
  },
  {
    id: "gk-017",
    question: "What is the minimum brake lining thickness before brakes must be replaced?",
    options: ["1/8 inch", "3/16 inch", "1/4 inch", "3/8 inch"],
    correctIndex: 2,
    explanation: "Brake linings must be at least 1/4 inch thick. Below this, the vehicle should not be driven until brakes are replaced. Check through the inspection port on the brake drum.",
    section: "Vehicle Inspection",
    diagramRef: "/assets/cdl/brake-wheel-assembly.png",
  },
  {
    id: "gk-018",
    question: "During inspection, you find a cracked windshield. When is this a safety violation?",
    options: [
      "Any crack of any size",
      "Any crack in the driver's direct line of vision, or any intersecting cracks",
      "Only cracks longer than 12 inches",
      "Only cracks that spider-web",
    ],
    correctIndex: 1,
    explanation: "A cracked windshield is a violation if the crack is in the area cleaned by the wipers on the driver's side, or if there are intersecting cracks. Small chips outside the driver's view area are not violations.",
    section: "Vehicle Inspection",
  },
  {
    id: "gk-019",
    question: "How much steering wheel free play is acceptable for power steering?",
    options: ["Less than 1 inch", "About 2 inches (10 degrees)", "Up to 4 inches", "Any amount is fine with power steering"],
    correctIndex: 1,
    explanation: "For a 20-inch steering wheel with power steering, free play should not exceed about 2 inches (approximately 10 degrees of rotation) before the front wheels begin to move.",
    section: "Vehicle Inspection",
    diagramRef: "/assets/cdl/steering-system.png",
  },
  {
    id: "gk-020",
    question: "What color are the identification lights on top of the cab?",
    options: ["Red", "White", "Amber", "Yellow-green"],
    correctIndex: 2,
    explanation: "The three identification lights centered on the top of the cab must be amber. They indicate the width of the vehicle to oncoming traffic. Rear identification lights are red.",
    section: "Vehicle Inspection",
    diagramRef: "/assets/cdl/truck-lighting.png",
  },

  // ── Transporting Cargo ────────────────────────────────────────────────────
  {
    id: "gk-021",
    question: "How often must you stop and check your cargo securement during a trip?",
    options: [
      "Every 100 miles or 2 hours",
      "Within the first 50 miles, then every 150 miles or 3 hours",
      "Every 200 miles or 4 hours",
      "Only at the beginning and end of the trip",
    ],
    correctIndex: 1,
    explanation: "You must check cargo within the first 50 miles of a trip, and then every 150 miles or 3 hours (whichever comes first) thereafter.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-022",
    question: "The maximum legal height for a CMV from the road surface is:",
    options: ["12 feet 6 inches", "13 feet 6 inches", "14 feet", "14 feet 6 inches"],
    correctIndex: 1,
    explanation: "The maximum height is generally 13 feet 6 inches, though some states allow 14 feet. Always know the height of your load and watch for low clearance bridges.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-023",
    question: "Cargo that is loaded too high can:",
    options: [
      "Improve fuel economy",
      "Make the vehicle more stable in wind",
      "Raise the center of gravity and increase rollover risk",
      "Reduce tire wear",
    ],
    correctIndex: 2,
    explanation: "High loads raise the center of gravity, which increases the risk of rollover — especially in curves, on ramps, and during sudden maneuvers. Distribute weight as low as possible.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-024",
    question: "Which type of tie-down is NOT acceptable for cargo securement?",
    options: ["Chains", "Wire rope", "Synthetic webbing", "Bungee cords"],
    correctIndex: 3,
    explanation: "Bungee cords (elastic straps) are not acceptable for cargo securement on commercial vehicles. They stretch and do not provide the working load limit required by FMCSA regulations. Use chains, wire rope, or rated synthetic webbing.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-025",
    question: "If cargo extends more than 4 feet beyond the rear of the body, you must:",
    options: [
      "Drive with 4-way flashers on",
      "Mark it with a red flag (daytime) or red light (night) visible at 500 feet",
      "Reduce speed to 45 mph",
      "Obtain an oversize load permit",
    ],
    correctIndex: 1,
    explanation: "Overhanging cargo must be marked: a red flag (18 inches square minimum) during the day, and a red light visible from 500 feet at night. Some states also require oversize load signs.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-026",
    question: "Cargo should be secured using at least the following minimum number of tie-downs for a 15-foot load:",
    options: ["1 tie-down", "2 tie-downs", "3 tie-downs", "4 tie-downs"],
    correctIndex: 1,
    explanation: "Use at least 1 tie-down for cargo 5 feet or shorter, and 1 additional tie-down for each additional 10 feet (or fraction thereof). A 15-foot load requires at least 2 tie-downs. Regardless of length, you always need at least 2 tie-downs if the cargo is not contained by the vehicle structure.",
    section: "Transporting Cargo",
  },

  // ── Regulations (HOS, FMCSA) ─────────────────────────────────────────────
  {
    id: "gk-027",
    question: "What is the maximum number of hours a property-carrying CMV driver can drive after 10 consecutive hours off duty?",
    options: ["8 hours", "10 hours", "11 hours", "14 hours"],
    correctIndex: 2,
    explanation: "Property-carrying drivers may drive a maximum of 11 hours after 10 consecutive hours off duty. All driving must occur within a 14-hour on-duty window.",
    section: "Regulations",
  },
  {
    id: "gk-028",
    question: "The BAC (Blood Alcohol Concentration) limit for CDL drivers is:",
    options: ["0.02%", "0.04%", "0.06%", "0.08%"],
    correctIndex: 1,
    explanation: "The BAC limit for commercial drivers is 0.04% — half the limit for regular passenger vehicle drivers (0.08%). However, a CDL driver should not consume any alcohol within 4 hours of driving.",
    section: "Regulations",
  },
  {
    id: "gk-029",
    question: "The 14-hour driving window means:",
    options: [
      "You can drive for 14 hours straight",
      "After 10 hours off, you have a 14-hour window to complete all driving; the window does not stop for breaks",
      "You must take 14 hours off between shifts",
      "You can be on duty for 14 hours per week",
    ],
    correctIndex: 1,
    explanation: "The 14-hour window starts when you begin any on-duty activity. You must complete all driving within this window. The clock does NOT stop for off-duty breaks — it runs continuously until 14 hours have passed.",
    section: "Regulations",
  },
  {
    id: "gk-030",
    question: "What is the 30-minute break rule for property-carrying drivers?",
    options: [
      "30 minutes off every 4 hours",
      "A 30-minute break required before driving after 8 cumulative hours of driving",
      "30 minutes of sleeper berth required every shift",
      "The 30-minute rule was eliminated",
    ],
    correctIndex: 1,
    explanation: "Property-carrying drivers must take a 30-minute break (off-duty or sleeper berth) before driving if 8 cumulative hours of driving time have passed since last off-duty period of 30+ minutes.",
    section: "Regulations",
  },
  {
    id: "gk-031",
    question: "The 60/70-hour on-duty limit means:",
    options: [
      "You cannot drive more than 60 hours in 7 days or 70 hours in 8 days",
      "You cannot be on duty more than 60 hours in 7 days or 70 hours in 8 days",
      "You must rest 60-70 hours per week",
      "Your employer chooses your weekly hour limit",
    ],
    correctIndex: 1,
    explanation: "You cannot drive after being on duty for 60 hours in 7 consecutive days (if your company does not operate every day) or 70 hours in 8 consecutive days (if your company operates every day). This is the weekly limit, not a per-shift limit.",
    section: "Regulations",
  },
  {
    id: "gk-032",
    question: "Which of the following disqualifies you from holding a CDL?",
    options: [
      "A single speeding ticket over 15 mph in your personal vehicle",
      "Two serious traffic violations within 3 years while operating a CMV",
      "A parking violation in your personal vehicle",
      "An expired medical card that was renewed within 30 days",
    ],
    correctIndex: 1,
    explanation: "Two serious traffic violations within a 3-year period result in a 60-day CDL disqualification. Three violations within 3 years result in 120-day disqualification. Serious violations include speeding 15+ mph over, reckless driving, improper lane changes, following too closely, and more.",
    section: "Regulations",
  },
  {
    id: "gk-033",
    question: "What is the minimum age to drive a CMV in interstate commerce?",
    options: ["18 years old", "19 years old", "21 years old", "25 years old"],
    correctIndex: 2,
    explanation: "You must be at least 21 years old to drive a CMV in interstate commerce (across state lines). Some states allow intrastate CDL driving at age 18, but federal interstate operations require age 21.",
    section: "Regulations",
  },

  // ── Hazardous Conditions ──────────────────────────────────────────────────
  {
    id: "gk-034",
    question: "If you are driving in heavy rain, you should reduce your speed by at least:",
    options: ["10 mph", "1/4 of the speed limit", "1/3 of the speed limit", "1/2 of the speed limit"],
    correctIndex: 2,
    explanation: "In heavy rain, reduce your speed by at least 1/3. On packed snow, reduce by 1/2. On ice, slow to a crawl and stop driving as soon as safely possible.",
    section: "Hazardous Conditions",
  },
  {
    id: "gk-035",
    question: "Black ice is most likely to form on:",
    options: [
      "Straight, flat sections of highway",
      "Bridges, overpasses, and shaded areas",
      "Concrete roads only",
      "Roads with heavy traffic",
    ],
    correctIndex: 1,
    explanation: "Bridges, overpasses, and shaded areas freeze first because cold air circulates both above and below the road surface. These areas can be icy even when the rest of the road appears dry.",
    section: "Hazardous Conditions",
  },
  {
    id: "gk-036",
    question: "When driving in fog, you should use:",
    options: ["High-beam headlights for maximum visibility", "Low-beam headlights", "Parking lights only", "No lights to avoid reflection"],
    correctIndex: 1,
    explanation: "Use low-beam headlights in fog. High beams reflect off fog particles and actually reduce your visibility. Also use fog lights if equipped, and reduce speed.",
    section: "Hazardous Conditions",
  },
  {
    id: "gk-037",
    question: "If your vehicle starts to skid on ice, you should:",
    options: [
      "Apply the brakes firmly",
      "Accelerate to pull out of the skid",
      "Turn into the skid and avoid braking",
      "Put the transmission in neutral",
    ],
    correctIndex: 2,
    explanation: "If you skid on ice: take your foot off the accelerator, do NOT brake, and steer (counter-steer) in the direction you want the front of the vehicle to go. Once you regain traction, straighten the wheel.",
    section: "Hazardous Conditions",
  },
  {
    id: "gk-038",
    question: "During strong crosswinds, which vehicles are most susceptible to being pushed off course?",
    options: [
      "Loaded flatbed trucks",
      "Empty or lightly loaded high-profile vehicles",
      "Tanker trucks fully loaded",
      "Low-boy trailers",
    ],
    correctIndex: 1,
    explanation: "Empty or lightly loaded high-profile vehicles (box trailers, dry vans) act like sails and are most susceptible to crosswinds. Be especially careful on open stretches, bridges, and when passing other large vehicles.",
    section: "Hazardous Conditions",
  },

  // ── Emergency Procedures ──────────────────────────────────────────────────
  {
    id: "gk-039",
    question: "After an emergency stop, where should you place your three reflective triangles?",
    options: [
      "All three behind the vehicle, evenly spaced",
      "Within 10 feet, at 100 feet, and at 200 feet behind the vehicle",
      "At 50 feet, 100 feet, and 150 feet behind the vehicle",
      "One in front and two behind",
    ],
    correctIndex: 1,
    explanation: "Place triangles within 10 feet of the rear of the vehicle, at 100 feet behind, and at 200 feet behind. On a curve or near a hill crest, place the farthest triangle before the obstruction to give drivers warning.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-040",
    question: "During a tire blowout, you should:",
    options: [
      "Brake hard immediately",
      "Hold the wheel firmly, do NOT brake, and gradually slow down",
      "Steer onto the shoulder immediately",
      "Downshift quickly to engine brake",
    ],
    correctIndex: 1,
    explanation: "During a blowout: grip the steering wheel firmly, do NOT brake (braking can cause loss of control), stay in your lane, and gradually slow down. Pull off the road when safe and you have control.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-041",
    question: "If your vehicle catches fire, you should:",
    options: [
      "Keep driving to the nearest fire station",
      "Pull over, shut off the engine, and get away from the vehicle",
      "Open the hood to assess the fire",
      "Pour water on the engine immediately",
    ],
    correctIndex: 1,
    explanation: "Pull over as far from buildings and other vehicles as possible. Shut off the engine, set the parking brake, grab the fire extinguisher, and get away. Call 911. Do NOT open the hood — adding oxygen can intensify the fire.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-042",
    question: "What type of fire extinguisher is required in a commercial vehicle?",
    options: [
      "A rated (ordinary combustibles only)",
      "B:C rated minimum (5 pounds)",
      "ABC rated (at least 10 pounds) with UL rating of 10 B:C or more",
      "Any household extinguisher",
    ],
    correctIndex: 2,
    explanation: "CMVs must carry a properly charged and rated fire extinguisher: UL rating of 5 B:C or more, OR two with 4 B:C ratings. Most drivers carry a single 10 B:C or higher ABC-rated extinguisher.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-043",
    question: "If you must leave the road to avoid a collision, you should:",
    options: [
      "Brake as hard as possible before leaving the pavement",
      "Steer right, avoid braking until speed has dropped, and avoid turning back sharply",
      "Turn the wheel hard left into the median",
      "Close your eyes and hold on",
    ],
    correctIndex: 1,
    explanation: "If you must leave the road: steer to the right (shoulder) if possible, avoid braking on the shoulder (loose gravel can cause loss of control), and when safe to re-enter, turn back gently — sharp re-entry from a soft shoulder can cause rollover.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-044",
    question: "An emergency vehicle with its lights and siren on is approaching from behind. You should:",
    options: [
      "Speed up to get out of the way",
      "Stop immediately wherever you are",
      "Pull to the right side of the road and stop",
      "Move to the left lane",
    ],
    correctIndex: 2,
    explanation: "Pull to the right side of the road and stop. Do not stop in an intersection. Let the emergency vehicle pass before moving. Never follow an emergency vehicle closer than 500 feet.",
    section: "Emergency Procedures",
  },

  // ── Additional General Knowledge ──────────────────────────────────────────
  {
    id: "gk-045",
    question: "When backing a CMV, you should:",
    options: [
      "Use a spotter whenever possible",
      "Back as quickly as possible to minimize time in a dangerous position",
      "Never use your mirrors — always turn and look",
      "Sound the horn continuously while backing",
    ],
    correctIndex: 0,
    explanation: "Use a spotter (helper) whenever possible when backing. If no spotter is available, walk around the vehicle before backing to check for obstacles. Back slowly and check mirrors frequently.",
    section: "Safe Driving",
  },
  {
    id: "gk-046",
    question: "A 'stale green light' means:",
    options: [
      "The traffic light is old and needs replacement",
      "The green light has been on for a while and may change soon",
      "The light is malfunctioning",
      "A dedicated green arrow for trucks",
    ],
    correctIndex: 1,
    explanation: "A 'stale green light' is one that has been green for a while when you approach. It may change to yellow soon. Be prepared to stop — do not speed up to beat a changing light, especially in a heavy vehicle.",
    section: "Safe Driving",
  },
  {
    id: "gk-047",
    question: "What is the purpose of retarders (Jake brakes)?",
    options: [
      "To increase acceleration on hills",
      "To help slow the vehicle without using service brakes",
      "To lock the trailer brakes in an emergency",
      "To reduce engine noise",
    ],
    correctIndex: 1,
    explanation: "Retarders (engine brakes / Jake brakes) help slow the vehicle without using the service brakes, reducing brake wear and preventing overheating on long downgrades. Turn them off on slippery roads — they can cause drive-wheel skids.",
    section: "Safe Driving",
  },
  {
    id: "gk-048",
    question: "GVWR stands for:",
    options: [
      "Gross Vehicle Weight Rating — the maximum safe weight as set by the manufacturer",
      "General Vehicle Width Requirement",
      "Gross Volume Weight Ratio",
      "Government Vehicle Warranty Registration",
    ],
    correctIndex: 0,
    explanation: "GVWR is the Gross Vehicle Weight Rating — the maximum weight a vehicle can safely carry, including its own weight, as determined by the manufacturer. Exceeding GVWR is a serious violation.",
    section: "Regulations",
  },
  {
    id: "gk-049",
    question: "Which of the following is NOT a Class A CDL combination vehicle?",
    options: [
      "A tractor pulling a 15,000 lb trailer",
      "A straight truck with a GVWR of 30,000 lbs (no trailer)",
      "A tractor pulling two trailers totaling 12,000 lbs",
      "A truck pulling a trailer with a GVWR over 10,000 lbs when the combination exceeds 26,001 lbs",
    ],
    correctIndex: 1,
    explanation: "A Class A CDL is required for combination vehicles where the GCWR exceeds 26,001 lbs AND the towed vehicle has a GVWR over 10,000 lbs. A straight truck (no trailer) would be Class B, not Class A.",
    section: "Regulations",
  },
  {
    id: "gk-050",
    question: "You discover a cargo shift during an en-route inspection. You should:",
    options: [
      "Continue to the next truck stop",
      "Secure the cargo before driving any further",
      "Drive slowly with hazard lights on",
      "Call your dispatcher for instructions",
    ],
    correctIndex: 1,
    explanation: "A shifted cargo is a safety hazard — it can affect steering, cause rollover, or fall from the vehicle. Secure it immediately before driving any further.",
    section: "Transporting Cargo",
  },
  {
    id: "gk-051",
    question: "The proper way to use a fire extinguisher is:",
    options: [
      "Aim at the top of the flames",
      "PASS: Pull pin, Aim at base of fire, Squeeze handle, Sweep side to side",
      "Spray continuously in one spot",
      "Stand as close to the fire as possible",
    ],
    correctIndex: 1,
    explanation: "Remember PASS: Pull the pin, Aim at the base of the fire (not the flames), Squeeze the handle, and Sweep side to side. Stand 10-15 feet away.",
    section: "Emergency Procedures",
  },
  {
    id: "gk-052",
    question: "Road surfaces are most slippery:",
    options: [
      "After it has been raining for several hours",
      "Just after rain begins, when oil and water first mix",
      "During a heavy downpour",
      "After the rain stops completely",
    ],
    correctIndex: 1,
    explanation: "Roads are most slippery just after rain begins. Oil, grease, and dust on the road surface mix with water to create a slick film. After continued rain, this mixture washes away.",
    section: "Hazardous Conditions",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// AIR BRAKES (50+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const AIR_BRAKES_QUESTIONS: CdlQuestion[] = [
  {
    id: "ab-001",
    question: "The air compressor governor cuts out (stops pumping) at approximately:",
    options: ["60 psi", "90 psi", "100 psi", "125 psi"],
    correctIndex: 3,
    explanation: "The governor controls when the compressor pumps air. It typically cuts in (starts pumping) around 100 psi and cuts out (stops) around 125 psi.",
    section: "Air Brake System",
    diagramRef: "/assets/cdl/air-brake-system.png",
  },
  {
    id: "ab-002",
    question: "The air compressor governor cuts in (starts pumping) at approximately:",
    options: ["60 psi", "80 psi", "100 psi", "120 psi"],
    correctIndex: 2,
    explanation: "The governor cuts in at approximately 100 psi (when tank pressure drops to this level) and cuts out at approximately 125 psi.",
    section: "Air Brake System",
  },
  {
    id: "ab-003",
    question: "With the engine at operating RPM, the air pressure should build from 85 to 100 psi within:",
    options: ["15 seconds", "30 seconds", "45 seconds", "1 minute"],
    correctIndex: 2,
    explanation: "The air pressure should build from 85 to 100 psi within 45 seconds with the engine at operating RPM. If it takes longer, the air compressor or system may be defective.",
    section: "Air Brake System",
  },
  {
    id: "ab-004",
    question: "The low air pressure warning signal must activate before pressure drops below:",
    options: ["40 psi", "50 psi", "60 psi", "80 psi"],
    correctIndex: 2,
    explanation: "The low air pressure warning (light, buzzer, or both) must come on before the pressure drops below 60 psi. This gives you time to stop safely before the brakes lock up.",
    section: "Air Brake System",
  },
  {
    id: "ab-005",
    question: "What happens when air pressure drops to approximately 20-45 psi?",
    options: [
      "Nothing — the brakes still work normally",
      "The spring brakes will apply automatically",
      "The engine shuts off",
      "Only the trailer brakes lock up",
    ],
    correctIndex: 1,
    explanation: "When air pressure drops to 20-45 psi, the spring brakes will apply automatically. Spring brakes use powerful springs that are held back by air pressure — when pressure is lost, the springs push the brake shoes against the drums.",
    section: "Air Brake System",
  },
  {
    id: "ab-006",
    question: "The purpose of the air dryer in an air brake system is to:",
    options: [
      "Cool the air compressor",
      "Remove moisture from the compressed air before it reaches the tanks",
      "Increase air pressure output",
      "Lubricate the brake chambers",
    ],
    correctIndex: 1,
    explanation: "The air dryer removes moisture from compressed air. Moisture in the system can freeze in cold weather (blocking air flow), corrode components, and reduce braking effectiveness.",
    section: "Air Brake System",
  },
  {
    id: "ab-007",
    question: "How should you drain the air tanks (if not automatic)?",
    options: [
      "Once a week",
      "At the end of each driving day",
      "Only when the air dryer fails",
      "Once a month during scheduled maintenance",
    ],
    correctIndex: 1,
    explanation: "Drain air tanks at the end of each driving day by opening the drain valve on the bottom of each tank. This removes moisture and oil that collected during the day. Drain the wet (supply) tank first.",
    section: "Air Brake System",
  },
  {
    id: "ab-008",
    question: "During the applied-pressure (leakage) test, the air pressure should not drop more than:",
    options: [
      "1 psi per minute (single) / 2 psi (combination)",
      "2 psi per minute (single) / 3 psi (combination)",
      "3 psi per minute (single) / 4 psi (combination)",
      "4 psi per minute (single) / 6 psi (combination)",
    ],
    correctIndex: 2,
    explanation: "With brakes fully applied, the pressure drop should not exceed: 3 psi in one minute for a single vehicle, or 4 psi in one minute for a combination vehicle. Greater drops indicate air leaks.",
    section: "Air Brake Tests",
  },
  {
    id: "ab-009",
    question: "What is the purpose of the supply (emergency) air line between the tractor and trailer?",
    options: [
      "It carries air to operate the trailer brakes",
      "It supplies air to the trailer air tanks and controls the emergency brakes",
      "It is the only line needed for braking",
      "It supplies air to the trailer suspension",
    ],
    correctIndex: 1,
    explanation: "The supply (emergency) line has two functions: it supplies air to fill the trailer air tanks, and it controls the trailer emergency brakes. If this line is disconnected or loses pressure, the trailer emergency brakes will apply.",
    section: "Air Brake System",
  },
  {
    id: "ab-010",
    question: "The service (control) air line between tractor and trailer:",
    options: [
      "Fills the trailer air tanks",
      "Carries air controlled by the foot brake or trailer hand valve to apply trailer brakes",
      "Controls the trailer emergency brakes",
      "Supplies air for the trailer suspension system",
    ],
    correctIndex: 1,
    explanation: "The service (control) line carries air pressure controlled by the foot brake (or trailer hand valve) to apply the trailer brakes. It does not supply air to fill the tanks — that's the supply line's job.",
    section: "Air Brake System",
  },
  {
    id: "ab-011",
    question: "The tractor protection valve:",
    options: [
      "Prevents trailer air from flowing back to the tractor if the trailer breaks away",
      "Protects the tractor air supply by closing the supply line when air pressure drops too low",
      "Controls maximum braking force to the tractor",
      "Prevents overcharging of the tractor tanks",
    ],
    correctIndex: 1,
    explanation: "The tractor protection valve closes automatically when supply line pressure drops to 20-45 psi. This preserves the tractor's air supply so the tractor brakes still work even if the trailer air system has a major leak.",
    section: "Air Brake System",
  },
  {
    id: "ab-012",
    question: "What is brake lag?",
    options: [
      "The time from when you see a hazard to when you press the brake",
      "The delay between pressing the brake pedal and the brakes actually working on air brake systems",
      "The distance traveled while brakes are being applied",
      "Fading brake effectiveness on long downgrades",
    ],
    correctIndex: 1,
    explanation: "Brake lag is the time it takes air to travel through the lines to the brakes after pressing the pedal — typically 4/10 of a second. At 55 mph, the vehicle travels 32 feet during brake lag alone. This is unique to air brakes; hydraulic brakes have no lag.",
    section: "Air Brake System",
  },
  {
    id: "ab-013",
    question: "Brake fade occurs when:",
    options: [
      "Brakes are cold",
      "Brakes get too hot from overuse and lose stopping power",
      "Air pressure is too high",
      "The slack adjuster is properly adjusted",
    ],
    correctIndex: 1,
    explanation: "Brake fade happens when brakes overheat from excessive use (e.g., riding brakes on a long downgrade). Hot drums expand away from the shoes, requiring more pressure to stop and potentially failing completely. This is why proper downhill braking technique is critical.",
    section: "Air Brake System",
  },
  {
    id: "ab-014",
    question: "What is the purpose of the slack adjuster?",
    options: [
      "To adjust the air pressure in the brake chambers",
      "To convert the push rod's linear motion into rotational force to turn the S-cam",
      "To tighten the brake drum to the wheel",
      "To release the spring brakes",
    ],
    correctIndex: 1,
    explanation: "The slack adjuster is a lever arm that converts the push rod's straight-line (linear) push into rotational force that turns the S-cam or disc brake caliper. It also provides a means to adjust for brake lining wear.",
    section: "Air Brake System",
    diagramRef: "/assets/cdl/brake-wheel-assembly.png",
  },
  {
    id: "ab-015",
    question: "Maximum push rod travel (stroke) for most type 30 brake chambers is:",
    options: ["1 inch", "1.5 inches", "2 inches", "3 inches"],
    correctIndex: 2,
    explanation: "For a type 30 long-stroke brake chamber, the maximum legal push rod travel is 2 inches. Exceeding this means the brakes are out of adjustment — the most common single defect found during roadside inspections.",
    section: "Air Brake System",
  },
  {
    id: "ab-016",
    question: "Spring brakes should NEVER be used to:",
    options: [
      "Park the vehicle",
      "Hold the vehicle on a grade",
      "Stop the vehicle if the air system fails at highway speed",
      "Stop the vehicle during normal parking",
    ],
    correctIndex: 2,
    explanation: "Spring brakes should not be relied upon to stop a vehicle at highway speeds. They apply full force to the rear wheels only, which can cause jackknifing. If air pressure is dropping, stop as soon as safely possible BEFORE the spring brakes apply automatically.",
    section: "Air Brake System",
  },
  {
    id: "ab-017",
    question: "During the air brake check, you pump the brake pedal to reduce pressure. The low air warning should activate at or before:",
    options: ["40 psi", "50 psi", "60 psi", "80 psi"],
    correctIndex: 2,
    explanation: "The low air pressure warning must activate before the pressure drops below 60 psi. If it doesn't, the warning system is defective and the vehicle should not be driven.",
    section: "Air Brake Tests",
  },
  {
    id: "ab-018",
    question: "The parking brake control knob is typically what color?",
    options: ["Red", "Yellow", "Blue", "Green"],
    correctIndex: 1,
    explanation: "The parking brake (spring brake) control is a yellow diamond-shaped push-pull knob. Push in to release the spring brakes, pull out to apply them.",
    section: "Air Brake System",
  },
  {
    id: "ab-019",
    question: "The trailer air supply control (red button/knob) is used to:",
    options: [
      "Apply the trailer brakes only",
      "Supply air to the trailer and release the trailer spring brakes",
      "Lock the trailer wheels during parking",
      "Increase trailer air pressure above normal levels",
    ],
    correctIndex: 1,
    explanation: "The red trailer air supply button/knob controls the flow of air to the trailer. Pushing it in supplies air (and releases trailer spring brakes). Pulling it out or having it pop out shuts off air supply and applies trailer spring brakes.",
    section: "Air Brake System",
  },
  {
    id: "ab-020",
    question: "What should you do if your low air pressure warning comes on while driving?",
    options: [
      "Continue to the next rest area",
      "Pull over and stop safely as soon as possible",
      "Pump the brakes to rebuild pressure",
      "Drive faster to build air pressure with the compressor",
    ],
    correctIndex: 1,
    explanation: "Stop safely as soon as possible. Continued driving risks having the spring brakes apply automatically, which at highway speed can be dangerous (jackknife). Do not try to 'limp' to a service facility.",
    section: "Air Brake System",
  },
  {
    id: "ab-021",
    question: "Dual air brake systems:",
    options: [
      "Have two of everything — two compressors, two governors",
      "Use a single air compressor but have two separate air tanks and separate circuits to front and rear axles",
      "Are only required on vehicles over 80,000 lbs",
      "Use one tank for the tractor and another for the trailer",
    ],
    correctIndex: 1,
    explanation: "Dual systems use a single compressor but split into primary and secondary circuits (usually front/rear axle split). If one circuit fails, the other still provides braking. Both circuits must show adequate pressure during pre-trip.",
    section: "Air Brake System",
    diagramRef: "/assets/cdl/air-brake-system.png",
  },
  {
    id: "ab-022",
    question: "Fanning (pumping) the brakes on a long downgrade can:",
    options: [
      "Help the brakes cool down",
      "Increase stopping power",
      "Cause air pressure to drop dangerously low",
      "Prevent brake fade",
    ],
    correctIndex: 2,
    explanation: "Fanning the brakes uses air faster than the compressor can replace it, potentially dropping pressure to the point where brakes won't work. Use the proper snub braking technique instead.",
    section: "Air Brake System",
  },
  {
    id: "ab-023",
    question: "An air brake system is fully charged when the gauge reads:",
    options: ["80-90 psi", "90-100 psi", "100-125 psi", "125-150 psi"],
    correctIndex: 2,
    explanation: "A fully charged system reads between the governor cut-in (about 100 psi) and cut-out (about 125 psi). If the gauge reads higher than 135 psi, the governor may be defective.",
    section: "Air Brake System",
  },
  {
    id: "ab-024",
    question: "The S-cam brake gets its name because:",
    options: [
      "It was invented by someone named Sam",
      "It uses an S-shaped cam that forces the brake shoes apart when rotated",
      "The brake pads are shaped like an S",
      "The air hoses are routed in an S pattern",
    ],
    correctIndex: 1,
    explanation: "The S-cam is an S-shaped metal piece that, when rotated by the slack adjuster, pushes the brake shoes outward against the brake drum. It is the most common type of foundation brake on heavy trucks.",
    section: "Air Brake System",
  },
  {
    id: "ab-025",
    question: "If one air system in a dual system is damaged, the braking force will be:",
    options: [
      "Completely lost",
      "Reduced — you will still have braking but it will take longer to stop",
      "Unchanged — the other system compensates fully",
      "Available only on the trailer",
    ],
    correctIndex: 1,
    explanation: "Losing one circuit means losing braking on those axles. The remaining circuit still works, but stopping distances will be much longer. Stop as soon as safely possible and get the system repaired.",
    section: "Air Brake System",
  },
  // Additional air brake questions
  {
    id: "ab-026",
    question: "What do alcohol evaporators do in an air brake system?",
    options: [
      "Remove alcohol from the driver's breath",
      "Introduce alcohol into the air system to reduce ice formation in cold weather",
      "Evaporate excess brake fluid",
      "Cool the air compressor",
    ],
    correctIndex: 1,
    explanation: "Some air brake systems have alcohol evaporators that automatically add a small amount of alcohol to the air system to help prevent ice from forming in air lines during cold weather. They must be checked and refilled in cold weather.",
    section: "Air Brake System",
  },
  {
    id: "ab-027",
    question: "Wedge brakes use:",
    options: [
      "An S-cam to spread the shoes",
      "A wedge pushed between the brake shoes by the push rod to force them apart",
      "Hydraulic fluid to apply pressure",
      "Spring pressure only",
    ],
    correctIndex: 1,
    explanation: "Wedge brakes use a brake chamber push rod that pushes a wedge between the ends of the brake shoes, forcing them apart against the drum. They may have single or dual chambers.",
    section: "Air Brake System",
  },
  {
    id: "ab-028",
    question: "The one-way check valve between the primary and secondary tanks ensures:",
    options: [
      "Air can flow freely between tanks",
      "If one tank develops a leak, air is not lost from both tanks",
      "Maximum pressure is maintained at all times",
      "The wet tank drains first",
    ],
    correctIndex: 1,
    explanation: "One-way check valves prevent air from flowing backwards between the primary and secondary tanks. If one tank develops a leak, the other retains its air supply for braking.",
    section: "Air Brake System",
  },
  {
    id: "ab-029",
    question: "Automatic slack adjusters:",
    options: [
      "Never need checking or adjustment",
      "Should be checked during pre-trip — if push rod travel exceeds limits, there may be a mechanical problem",
      "Require daily manual adjustment",
      "Are only used on trailer axles",
    ],
    correctIndex: 1,
    explanation: "While automatic slack adjusters adjust themselves, they must still be checked during pre-trip inspections. If an automatic adjuster is out of adjustment, it likely indicates a mechanical problem — it should be repaired, not just manually adjusted.",
    section: "Air Brake System",
  },
  {
    id: "ab-030",
    question: "To check for air leaks during the static leakage test, with a fully charged system and engine off, the air loss rate should not exceed:",
    options: [
      "1 psi per minute for a single vehicle",
      "2 psi per minute for a single vehicle",
      "3 psi per minute for a combination",
      "Both A and C are correct thresholds",
    ],
    correctIndex: 1,
    explanation: "With the engine off and brakes released: single vehicles should lose no more than 2 psi per minute; combination vehicles no more than 3 psi per minute. These are the static (brakes not applied) leakage limits.",
    section: "Air Brake Tests",
  },
  {
    id: "ab-031",
    question: "The service brake system:",
    options: [
      "Uses spring force to apply the brakes",
      "Uses air pressure to apply the brakes during normal driving",
      "Is only used for parking",
      "Applies only to the steer axle",
    ],
    correctIndex: 1,
    explanation: "The service brake system uses air pressure from the foot brake valve to apply brakes on all wheels during normal driving. This is in contrast to the parking/emergency system which uses spring force.",
    section: "Air Brake System",
  },
  {
    id: "ab-032",
    question: "You should test the air leakage rate:",
    options: [
      "Weekly at the shop",
      "During every pre-trip inspection",
      "Only when you suspect a leak",
      "Monthly",
    ],
    correctIndex: 1,
    explanation: "Check the air leakage rate during every pre-trip inspection. Build full air pressure, turn off the engine, release the parking brake, and time the pressure drop. Then apply the brakes and check the applied leakage rate.",
    section: "Air Brake Tests",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMBINATION VEHICLES (30+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const COMBINATION_VEHICLES_QUESTIONS: CdlQuestion[] = [
  {
    id: "cv-001",
    question: "When coupling, the fifth wheel should be tilted:",
    options: [
      "Level with the ground",
      "Down toward the rear of the tractor",
      "Up toward the front of the tractor",
      "It doesn't matter",
    ],
    correctIndex: 1,
    explanation: "The fifth wheel should be tilted slightly down toward the rear so the trailer apron plate contacts the fifth wheel ramp smoothly. If level or tilted wrong, coupling may fail.",
    section: "Coupling/Uncoupling",
    diagramRef: "/assets/cdl/coupling-system.png",
  },
  {
    id: "cv-002",
    question: "After coupling, how do you test that the coupling is secure?",
    options: [
      "Visually check that the fifth wheel jaws are closed around the kingpin",
      "Pull the trailer forward gently with the tractor brakes released",
      "Apply the trailer brakes and try to pull forward with the tractor in low gear (tug test)",
      "All of the above",
    ],
    correctIndex: 3,
    explanation: "All three checks should be performed: (1) visually inspect the fifth wheel jaws are closed and locked around the kingpin, (2) check that there's no gap between the upper and lower fifth wheel, and (3) perform the tug test — set trailer brakes and gently try to pull away.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-003",
    question: "Before uncoupling, the trailer should be on:",
    options: [
      "A downhill slope for easy separation",
      "Firm, level ground",
      "Any paved surface",
      "Soft ground to prevent rolling",
    ],
    correctIndex: 1,
    explanation: "Always uncouple on firm, level ground. If the ground is soft, the trailer landing gear can sink. If the ground is not level, the trailer can roll away after uncoupling.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-004",
    question: "A tractor jackknife occurs when:",
    options: [
      "The trailer swings out and the tractor stays straight",
      "The drive wheels lock and the tractor slides sideways while the trailer pushes it",
      "The front steer tires blow out",
      "The fifth wheel unlocks while driving",
    ],
    correctIndex: 1,
    explanation: "A jackknife happens when the drive wheels lose traction and the tractor skids, swinging sideways while the heavier trailer pushes it from behind. Prevention: don't brake too hard, maintain proper following distance.",
    section: "Safe Driving",
  },
  {
    id: "cv-005",
    question: "A trailer jackknife (trailer swing) occurs when:",
    options: [
      "The tractor drive wheels skid",
      "The trailer wheels lock up and the trailer swings around toward the tractor",
      "The kingpin snaps",
      "The front tires lose traction",
    ],
    correctIndex: 1,
    explanation: "Trailer jackknife happens when the trailer wheels lock (often on slippery roads or from hard braking). The locked trailer slides sideways. ABS on the trailer helps prevent this.",
    section: "Safe Driving",
  },
  {
    id: "cv-006",
    question: "The crack-the-whip effect is a concern primarily with:",
    options: [
      "Single trailers",
      "Doubles and triples combinations",
      "Straight trucks",
      "Buses",
    ],
    correctIndex: 1,
    explanation: "The crack-the-whip effect amplifies rearward sway in multi-trailer combinations. The last trailer in a set of doubles or triples can swing much more than the first, especially during sudden lane changes or evasive maneuvers.",
    section: "Safe Driving",
    diagramRef: "/assets/cdl/doubles-triples-coupling.png",
  },
  {
    id: "cv-007",
    question: "When should you use the trailer hand valve (trolley valve)?",
    options: [
      "For regular braking while driving",
      "To test the trailer brakes during pre-trip",
      "As the primary brake at all times",
      "To help stop faster in emergencies",
    ],
    correctIndex: 1,
    explanation: "The trailer hand valve should only be used for testing trailer brakes. Never use it for regular braking while driving — it can cause the trailer to lock up and jackknife. Use the foot brake for normal braking.",
    section: "Braking",
  },
  {
    id: "cv-008",
    question: "What is off-tracking?",
    options: [
      "When the GPS loses signal",
      "When the rear wheels of a trailer follow a shorter (tighter) path than the front wheels in a turn",
      "When the vehicle drifts across lane markings",
      "When the trailer sways side to side at highway speed",
    ],
    correctIndex: 1,
    explanation: "Off-tracking means the rear wheels track closer to the inside of a turn than the front wheels. The longer the vehicle, the greater the off-tracking. This is why wide turns are needed, especially for right turns.",
    section: "Safe Driving",
  },
  {
    id: "cv-009",
    question: "When coupling, before backing under the trailer you should check that:",
    options: [
      "The trailer kingpin is aligned with the throat of the fifth wheel",
      "The trailer brakes are released so it can move",
      "The landing gear is fully retracted",
      "The air lines are already connected",
    ],
    correctIndex: 0,
    explanation: "Before backing under: ensure the kingpin is aligned with the fifth wheel throat, the trailer height is correct (just above the fifth wheel plate), the landing gear is still down, and the trailer brakes are set.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-010",
    question: "The trailer height should be _____ for proper coupling:",
    options: [
      "Level with or slightly above the center of the fifth wheel",
      "As high as possible to clear the tractor frame",
      "Low enough to slide the fifth wheel under the trailer nose",
      "It doesn't matter as long as the kingpin reaches",
    ],
    correctIndex: 2,
    explanation: "The trailer should be low enough that the tractor fifth wheel plate slides under the trailer apron (nose). If too high, the tractor can go under the trailer; too low, it can hit the trailer nose. Adjust with landing gear.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-011",
    question: "After coupling, you should raise the landing gear:",
    options: [
      "Before connecting the air lines",
      "Only after performing the tug test and confirming secure coupling",
      "Immediately after the kingpin clicks into the fifth wheel",
      "It can remain down during driving for extra stability",
    ],
    correctIndex: 1,
    explanation: "Raise the landing gear AFTER confirming the coupling is secure (visual check + tug test). If you raise it before confirming coupling and the coupling is not secure, the trailer nose will drop to the ground.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-012",
    question: "The service air line on a combination vehicle is typically coded what color?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctIndex: 1,
    explanation: "The service (control) line is coded blue. The supply (emergency) line is coded red. Memory aid: blue/service, red/emergency. The glad hands (couplers) are color-coded to match.",
    section: "Air Systems",
  },
  {
    id: "cv-013",
    question: "If the supply (emergency) air line to the trailer breaks or disconnects while driving:",
    options: [
      "Nothing happens — the service line takes over",
      "The trailer emergency brakes will apply",
      "Only the tractor brakes work",
      "Both B and C",
    ],
    correctIndex: 3,
    explanation: "If the supply line breaks, air escapes from the trailer air tank through the broken line, pressure drops, and the trailer spring (emergency) brakes apply automatically. The tractor brakes still work normally.",
    section: "Air Systems",
  },
  {
    id: "cv-014",
    question: "Where should you connect the safety chains on a converter dolly?",
    options: [
      "To the lead trailer's pintle hook",
      "Crossed under the connection point to the front trailer",
      "Straight on each side of the tongue",
      "Only to the rear trailer",
    ],
    correctIndex: 1,
    explanation: "Safety chains on the converter dolly should be crossed under the connection point. Crossing them forms a 'cradle' that catches the tongue if it breaks loose, preventing it from dragging on the ground.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "cv-015",
    question: "When driving a combination vehicle in a curve, you should:",
    options: [
      "Speed up to maintain momentum",
      "Brake hard in the curve if you're going too fast",
      "Slow to a safe speed before the curve and maintain steady speed through it",
      "Use the trailer hand brake in the curve for stability",
    ],
    correctIndex: 2,
    explanation: "Slow down before entering the curve. Braking in a curve can cause trailer jackknife or rollover. Maintain a steady speed through the curve, then accelerate gently when straightening out.",
    section: "Safe Driving",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// HAZMAT ENDORSEMENT (30+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const HAZMAT_QUESTIONS: CdlQuestion[] = [
  {
    id: "hm-001",
    question: "Who is responsible for correctly labeling and packaging hazardous materials for shipping?",
    options: ["The driver", "The shipper", "The carrier", "The consignee"],
    correctIndex: 1,
    explanation: "The shipper is responsible for properly packaging, labeling, and marking hazmat shipments. The carrier and driver are responsible for safe transport, but the shipper prepares the materials.",
    section: "General Hazmat",
    diagramRef: "/assets/cdl/hazmat-placards.png",
  },
  {
    id: "hm-002",
    question: "Hazmat placards must be placed:",
    options: [
      "Only on the rear of the vehicle",
      "On the front, rear, and both sides of the vehicle",
      "Only on the trailer",
      "On the driver's door",
    ],
    correctIndex: 1,
    explanation: "Placards must be displayed on all four sides of the vehicle — front, rear, and both sides. They must be readable from any direction. If the vehicle has a cargo-only trailer, both the tractor and trailer must be placarded.",
    section: "General Hazmat",
  },
  {
    id: "hm-003",
    question: "A Hazmat shipping paper must include:",
    options: [
      "The driver's CDL number",
      "The proper shipping name, hazard class, ID number, and packing group",
      "Only the weight of the shipment",
      "The destination address only",
    ],
    correctIndex: 1,
    explanation: "Shipping papers must include: proper shipping name, hazard class or division, UN/NA identification number, packing group (if assigned), total quantity, and emergency response phone number.",
    section: "Shipping Papers",
  },
  {
    id: "hm-004",
    question: "Where must hazmat shipping papers be kept while driving?",
    options: [
      "In the glove box",
      "In the driver's door pouch or within arm's reach while belted",
      "On the dashboard",
      "In the trailer",
    ],
    correctIndex: 1,
    explanation: "While driving, shipping papers must be within arm's reach while belted in the driver's seat, OR in a pouch on the driver's door. When out of the vehicle, papers must be on the driver's seat or in the door pouch — visible to anyone entering the cab.",
    section: "Shipping Papers",
  },
  {
    id: "hm-005",
    question: "Class 1 hazardous materials are:",
    options: ["Flammable liquids", "Explosives", "Corrosives", "Radioactive materials"],
    correctIndex: 1,
    explanation: "Class 1 = Explosives (6 divisions: 1.1 mass explosion, 1.2 projection, 1.3 fire/minor blast, 1.4 no significant blast, 1.5 insensitive, 1.6 extremely insensitive).",
    section: "Hazard Classes",
  },
  {
    id: "hm-006",
    question: "Class 3 hazardous materials are:",
    options: ["Gases", "Explosives", "Flammable liquids", "Oxidizers"],
    correctIndex: 2,
    explanation: "Class 3 = Flammable liquids. Common examples: gasoline, acetone, certain paints. Flash point is below 141 degrees F (60.5 degrees C).",
    section: "Hazard Classes",
  },
  {
    id: "hm-007",
    question: "Class 8 hazardous materials are:",
    options: ["Poisons", "Radioactive", "Corrosives", "Miscellaneous dangerous goods"],
    correctIndex: 2,
    explanation: "Class 8 = Corrosives. These are materials that damage or destroy skin, metal, or other materials on contact. Examples: battery acid (sulfuric acid), hydrochloric acid, sodium hydroxide (lye).",
    section: "Hazard Classes",
  },
  {
    id: "hm-008",
    question: "Which hazmat class requires a TSA security threat assessment for the endorsement?",
    options: [
      "Class 3 only",
      "All hazmat endorsements require a TSA background check",
      "Class 1 and Class 7 only",
      "Class 9 only",
    ],
    correctIndex: 1,
    explanation: "ALL CDL Hazmat (H) endorsements require a TSA security threat assessment (background check, fingerprinting). This must be renewed when the CDL is renewed.",
    section: "General Hazmat",
  },
  {
    id: "hm-009",
    question: "When fueling a vehicle carrying hazmat, you must:",
    options: [
      "Keep the engine running for power",
      "Turn off the engine and ensure someone is always at the nozzle",
      "Fuel only at designated hazmat fueling stations",
      "Fuel only during daylight hours",
    ],
    correctIndex: 1,
    explanation: "When fueling with hazmat aboard: turn off the engine, someone must be at the fuel nozzle at all times, and a person must be watching the vehicle. Do not smoke within 25 feet.",
    section: "Safe Transport",
  },
  {
    id: "hm-010",
    question: "The Emergency Response Guidebook (ERG) is used by:",
    options: [
      "Only hazmat specialists",
      "First responders to identify hazardous materials and initial protective actions",
      "Only the shipper",
      "Border patrol officers",
    ],
    correctIndex: 1,
    explanation: "The ERG is a guide for first responders during the initial phase of a hazmat incident. It helps identify hazards and determine immediate protective actions. Every emergency vehicle should carry one.",
    section: "Emergency Response",
  },
  {
    id: "hm-011",
    question: "You must stop your hazmat vehicle before crossing railroad tracks when:",
    options: [
      "Only when a train is visible",
      "Always — all vehicles placarded for hazmat must stop 15-50 feet from the nearest rail",
      "Only for Class 1 and Class 7 materials",
      "Only if the crossing has no gates",
    ],
    correctIndex: 1,
    explanation: "ALL placarded hazmat vehicles must stop 15-50 feet from the nearest rail at ALL railroad crossings. Look both ways, listen, and do not shift gears while crossing.",
    section: "Safe Transport",
  },
  {
    id: "hm-012",
    question: "Smoking is prohibited within ____ feet of a placarded hazmat vehicle:",
    options: ["10 feet", "15 feet", "25 feet", "50 feet"],
    correctIndex: 2,
    explanation: "No smoking within 25 feet of a hazmat vehicle. This applies during loading, unloading, driving, and parking.",
    section: "Safe Transport",
  },
  {
    id: "hm-013",
    question: "You discover a leaking container of hazardous material. You should:",
    options: [
      "Continue driving to the nearest truck stop",
      "Touch the material to identify it",
      "Not drive the vehicle; identify the material, warn others, and contact authorities",
      "Try to repair the container yourself",
    ],
    correctIndex: 2,
    explanation: "Never drive with a known hazmat leak. Identify the material from shipping papers (without touching it), move people away, contact 911 and your carrier. Use the ERG for initial guidance.",
    section: "Emergency Response",
  },
  {
    id: "hm-014",
    question: "Which hazmat cannot be loaded together on the same vehicle?",
    options: [
      "Class 3 and Class 8",
      "Class 1 (Explosives) and Class 5 (Oxidizers)",
      "Class 9 and Class 3",
      "Class 2 and Class 8",
    ],
    correctIndex: 1,
    explanation: "The Segregation Table in 49 CFR 177.848 specifies which hazmat classes cannot be loaded together. Explosives (Class 1) and Oxidizers (Class 5) is a classic prohibited combination — oxidizers can accelerate an explosion.",
    section: "Loading",
  },
  {
    id: "hm-015",
    question: "A hazmat vehicle must be placarded if carrying ____ or more of a non-bulk hazardous material:",
    options: ["100 lbs", "500 lbs", "1,001 lbs", "5,000 lbs"],
    correctIndex: 2,
    explanation: "Placards are required for non-bulk shipments of 1,001 lbs or more aggregate gross weight. However, certain materials (Table 1 materials like explosives, poison gas, radioactive) require placards at ANY quantity.",
    section: "General Hazmat",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TANKER ENDORSEMENT (20+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const TANKER_QUESTIONS: CdlQuestion[] = [
  {
    id: "tk-001",
    question: "Liquid surge in a tanker can:",
    options: [
      "Improve stability",
      "Push the truck through intersections and cause rollovers in turns",
      "Help with braking",
      "Only occur in completely full tanks",
    ],
    correctIndex: 1,
    explanation: "Liquid surge is the movement of liquid in a partially filled tank. It can push the vehicle forward after braking (through an intersection), push it sideways in curves (rollover), and make the vehicle hard to control.",
    section: "Liquid Surge",
    diagramRef: "/assets/cdl/tanker-liquid-surge.png",
  },
  {
    id: "tk-002",
    question: "Baffled tanks have:",
    options: [
      "Solid dividers that separate the tank into multiple compartments",
      "Bulkheads with holes that slow liquid flow but do not prevent front-to-back surge",
      "No internal structures",
      "Pressurized dividers",
    ],
    correctIndex: 1,
    explanation: "Baffles are internal bulkheads with holes that allow liquid to flow through but slow down the surge. They help control forward-to-back surge but do NOT prevent side-to-side surge.",
    section: "Tank Types",
  },
  {
    id: "tk-003",
    question: "A smooth bore (un-baffled) tanker is used for:",
    options: [
      "Gasoline only",
      "Food-grade products like milk, where baffles would trap residue and create sanitation problems",
      "All chemicals",
      "Only dry bulk loads",
    ],
    correctIndex: 1,
    explanation: "Smooth bore tankers have no baffles. They are required for food-grade liquids (milk, fruit juice) because baffles create corners that are difficult to clean, causing sanitation concerns. Smooth bore tankers have the worst surge problem.",
    section: "Tank Types",
  },
  {
    id: "tk-004",
    question: "The most dangerous tanker fill level for surge is:",
    options: [
      "Completely full (100%)",
      "Completely empty (0%)",
      "Half full (50%)",
      "About 3/4 full (75%)",
    ],
    correctIndex: 2,
    explanation: "A half-full tank allows the most liquid movement (surge). Completely full and completely empty tanks have little to no surge. Partially loaded tanks (especially 25-75%) are the most dangerous.",
    section: "Liquid Surge",
  },
  {
    id: "tk-005",
    question: "Outage (or ullage) refers to:",
    options: [
      "Spilled liquid after delivery",
      "The empty space in a tank to allow liquid expansion",
      "The amount of liquid lost to evaporation",
      "The capacity of the tank minus the load",
    ],
    correctIndex: 1,
    explanation: "Outage is the intentional empty space left in a tank to allow for liquid expansion. Liquids expand as they warm. Without sufficient outage, pressure can build and cause the tank to rupture or pop a relief valve.",
    section: "Loading",
  },
  {
    id: "tk-006",
    question: "When stopping a tanker vehicle, you should:",
    options: [
      "Brake hard and fast to minimize stopping distance",
      "Brake gently and gradually, leaving extra following distance",
      "Use the trailer hand valve primarily",
      "Downshift first, then brake hard",
    ],
    correctIndex: 1,
    explanation: "Brake gently and early. Hard braking causes liquid surge that can push the vehicle forward. Leave extra following distance and start braking earlier than you would with a dry van.",
    section: "Safe Driving",
  },
  {
    id: "tk-007",
    question: "The center of gravity in a tanker is:",
    options: [
      "Always the same regardless of load",
      "Higher than most other cargo vehicles, increasing rollover risk",
      "Lower than flatbed trucks",
      "Not affected by liquid movement",
    ],
    correctIndex: 1,
    explanation: "Tankers have a high center of gravity. Liquid sloshing raises it even higher in curves. This makes tankers much more prone to rollover than other vehicle types — especially in curves, on ramps, and during evasive maneuvers.",
    section: "Safe Driving",
  },
  {
    id: "tk-008",
    question: "An elliptical (oval) tank shape is used because:",
    options: [
      "It is the cheapest to manufacture",
      "It has a lower center of gravity than a circular cross-section",
      "It holds more liquid than a round tank",
      "It is easier to clean",
    ],
    correctIndex: 1,
    explanation: "Elliptical (oval) tank cross-sections lower the center of gravity compared to circular tanks, making the vehicle more stable. However, they cost more to build. Many petroleum tankers use this shape.",
    section: "Tank Types",
  },
  {
    id: "tk-009",
    question: "Tanker vehicles require a CDL with a tanker endorsement (N) when the tank capacity exceeds:",
    options: [
      "100 gallons",
      "500 gallons",
      "1,000 gallons",
      "119 gallons (permanently attached) or 1,000 gallons (temporary)",
    ],
    correctIndex: 2,
    explanation: "A tanker endorsement is required for any vehicle designed to transport liquid or gas in a tank with a capacity of 1,000 gallons or more. This includes permanently attached and portable tanks.",
    section: "Regulations",
  },
  {
    id: "tk-010",
    question: "When driving a tanker around a curve, you should:",
    options: [
      "Go at the posted speed limit",
      "Go well below the posted curve speed — tankers have a lower rollover threshold",
      "Accelerate through the curve for stability",
      "Brake firmly in the middle of the curve",
    ],
    correctIndex: 1,
    explanation: "Posted curve speeds are for passenger cars. Tankers have a much lower rollover threshold due to high center of gravity and liquid surge. Enter curves well below the posted speed.",
    section: "Safe Driving",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// DOUBLES/TRIPLES ENDORSEMENT (20+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const DOUBLES_TRIPLES_QUESTIONS: CdlQuestion[] = [
  {
    id: "dt-001",
    question: "When coupling a converter dolly to the rear trailer, the first thing you should do is:",
    options: [
      "Connect the air lines",
      "Secure the dolly with its own brakes or chocks",
      "Back the dolly under the trailer",
      "Raise the trailer landing gear",
    ],
    correctIndex: 1,
    explanation: "First, make sure the dolly is secure — set its brakes or chock the wheels. A rolling dolly is dangerous. Then position it in line with the kingpin before backing under.",
    section: "Coupling/Uncoupling",
    diagramRef: "/assets/cdl/doubles-triples-coupling.png",
  },
  {
    id: "dt-002",
    question: "The crack-the-whip effect in doubles/triples is worst for:",
    options: [
      "The tractor",
      "The lead trailer",
      "The last trailer in the combination",
      "All trailers equally",
    ],
    correctIndex: 2,
    explanation: "The crack-the-whip effect amplifies rearward. The last trailer in a combination experiences the most severe lateral (side-to-side) movement. This can cause the rear trailer to overturn even when the tractor and lead trailer remain stable.",
    section: "Safe Driving",
  },
  {
    id: "dt-003",
    question: "When loading doubles, the heaviest trailer should be:",
    options: [
      "In the rear position",
      "In the front (closest to the tractor) position",
      "It doesn't matter",
      "In the middle if triples",
    ],
    correctIndex: 1,
    explanation: "The heaviest trailer should always be closest to the tractor. This improves stability, reduces sway, and helps with braking. In triples, the lightest trailer goes in the rear.",
    section: "Loading",
  },
  {
    id: "dt-004",
    question: "When driving doubles/triples, you should allow:",
    options: [
      "The same following distance as a single trailer",
      "More following distance than a single trailer because of longer stopping distance",
      "Less following distance to prevent vehicles from cutting in",
      "Following distance based on speed alone",
    ],
    correctIndex: 1,
    explanation: "Doubles and triples need more following distance due to their greater length and longer stopping distances. Use the formula: 1 second per 10 feet of vehicle length, plus 1 additional second at speeds over 40 mph.",
    section: "Safe Driving",
  },
  {
    id: "dt-005",
    question: "On a converter dolly, the pintle hook connects to:",
    options: [
      "The kingpin of the rear trailer",
      "The tow bar (drawbar) of the dolly",
      "The fifth wheel of the lead trailer",
      "The safety chains",
    ],
    correctIndex: 1,
    explanation: "The pintle hook on the rear of the lead trailer connects to the drawbar (tongue) of the converter dolly. The dolly's own fifth wheel then connects to the kingpin of the rear trailer.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "dt-006",
    question: "When uncoupling doubles, which trailer should you disconnect first?",
    options: [
      "The front trailer",
      "The rear trailer",
      "Either one — order doesn't matter",
      "Whichever is lighter",
    ],
    correctIndex: 1,
    explanation: "Always uncouple the rear trailer first when breaking down doubles. The rear trailer needs to be disconnected from the converter dolly and parked before the dolly is disconnected from the lead trailer.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "dt-007",
    question: "Doubles/triples are more likely to rollover than single trailers because:",
    options: [
      "They are always heavier",
      "They have more axles",
      "The rearward amplification (crack-the-whip) causes greater forces on rear trailers",
      "Their engines are less powerful",
    ],
    correctIndex: 2,
    explanation: "Rearward amplification (crack-the-whip) means that turning or swerving forces are magnified for each successive trailer. Even a gentle lane change at the tractor can create rollover forces at the rear trailer.",
    section: "Safe Driving",
  },
  {
    id: "dt-008",
    question: "To prevent the crack-the-whip effect, you should:",
    options: [
      "Drive faster to keep the trailers taut",
      "Make smooth, gradual steering movements and lane changes",
      "Use the trailer hand brake frequently",
      "Lock the converter dolly fifth wheel",
    ],
    correctIndex: 1,
    explanation: "Smooth, gradual inputs are the key to safe doubles/triples driving. Avoid sudden lane changes, sharp turns, and abrupt braking. Steer gently and plan maneuvers well ahead.",
    section: "Safe Driving",
  },
  {
    id: "dt-009",
    question: "When coupling the converter dolly to the lead trailer, the air lines from the dolly connect to:",
    options: [
      "The tractor's glad hands",
      "The shut-off valves (glad hands) at the rear of the lead trailer",
      "The dolly's own air tank only",
      "Nowhere — the dolly has its own air system",
    ],
    correctIndex: 1,
    explanation: "The dolly's air lines connect to the glad hands (shut-off valves) at the rear of the lead trailer. This supplies air to the dolly and rear trailer brakes from the tractor's air system.",
    section: "Coupling/Uncoupling",
  },
  {
    id: "dt-010",
    question: "When making a tight turn with doubles, you should:",
    options: [
      "Take the turn at normal speed",
      "Make the turn wider than with a single trailer to account for greater off-tracking",
      "Speed up to pull the trailers through",
      "Jack-knife the lead trailer slightly",
    ],
    correctIndex: 1,
    explanation: "Doubles have more off-tracking than singles. The rear trailer cuts the corner even more than the front. Make wider turns, go slowly, and check mirrors constantly for the rear trailer's position.",
    section: "Safe Driving",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// PASSENGER ENDORSEMENT (20+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const PASSENGER_QUESTIONS: CdlQuestion[] = [
  {
    id: "ps-001",
    question: "The standee line on a bus indicates:",
    options: [
      "Where passengers should stand while the bus is in motion",
      "The line behind which passengers must stand — no standing allowed forward of this line",
      "Emergency exit boundaries",
      "Wheelchair securement zones",
    ],
    correctIndex: 1,
    explanation: "No passengers may stand forward of the standee line (or behind the rear standee line if equipped). Standees must remain behind this line while the bus is in motion.",
    section: "Bus Operations",
  },
  {
    id: "ps-002",
    question: "At a railroad crossing, a bus driver must:",
    options: [
      "Slow to 15 mph and look both ways",
      "Stop within 15-50 feet, open the door (or window), look and listen, then proceed only when safe",
      "Sound the horn and proceed at 5 mph",
      "Stop only if a train is visible",
    ],
    correctIndex: 1,
    explanation: "Bus drivers must stop at ALL railroad crossings 15-50 feet from the nearest rail. Open the door or window, look and listen in both directions, and cross only when certain no train is approaching. Do not shift gears while crossing.",
    section: "Bus Operations",
  },
  {
    id: "ps-003",
    question: "How many roof emergency exits must have signs indicating they are emergency exits?",
    options: ["None — roof exits are optional", "All of them", "Only the first one", "One on each side"],
    correctIndex: 1,
    explanation: "All emergency exits (roof hatches, side windows, rear door) must be clearly labeled as emergency exits. They must be operable from the inside without tools.",
    section: "Emergency Equipment",
  },
  {
    id: "ps-004",
    question: "A passenger bus must carry:",
    options: [
      "A fire extinguisher, spare electrical fuses, and emergency reflective triangles",
      "Only a first aid kit",
      "A fire extinguisher only",
      "A CB radio",
    ],
    correctIndex: 0,
    explanation: "At minimum, a bus must carry: a properly rated fire extinguisher, spare electrical fuses (unless equipped with circuit breakers), and three reflective emergency triangles.",
    section: "Emergency Equipment",
  },
  {
    id: "ps-005",
    question: "If a rider on your bus is being disruptive, you should:",
    options: [
      "Ignore it and keep driving",
      "Stop the bus in a safe location and address the situation; you may need to remove the person",
      "Speed up to reach the next stop faster",
      "Ask other passengers to handle it",
    ],
    correctIndex: 1,
    explanation: "If a passenger is creating a safety concern, stop the bus in a safe location. Try to resolve the issue. If necessary, ask the disruptive person to leave. Never drive distracted by a disruptive passenger.",
    section: "Bus Operations",
  },
  {
    id: "ps-006",
    question: "When discharging passengers at a stop, the driver should:",
    options: [
      "Let passengers exit through any door",
      "Watch passengers get off and monitor traffic to warn of any danger",
      "Immediately pull away as soon as the last person exits",
      "Exit the bus to assist every passenger",
    ],
    correctIndex: 1,
    explanation: "Watch passengers exit. Monitor mirrors and traffic. Wait until passengers have safely cleared the roadway before pulling away. If passengers are near the rear wheels, do not move.",
    section: "Bus Operations",
  },
  {
    id: "ps-007",
    question: "How many passenger seats must a vehicle have for the driver to need a P endorsement?",
    options: ["8 or fewer", "10 or fewer", "More than 15 (including driver)", "More than 16 (including driver)"],
    correctIndex: 3,
    explanation: "A CDL with passenger (P) endorsement is required when the vehicle is designed to transport 16 or more persons (including the driver).",
    section: "Regulations",
  },
  {
    id: "ps-008",
    question: "Prohibited items on a passenger bus include:",
    options: [
      "Luggage and personal bags",
      "Service animals",
      "Hazardous materials (except small quantities permitted for personal use)",
      "Musical instruments",
    ],
    correctIndex: 2,
    explanation: "Most hazmat is prohibited on buses with passengers. Small amounts for personal use are allowed (e.g., hair spray, nail polish), but Division 6.1 poisons, tear gas, Class 1 explosives, etc., are always prohibited.",
    section: "Regulations",
  },
  {
    id: "ps-009",
    question: "A charter bus or transit bus must have aisle clearance of at least:",
    options: ["12 inches", "15 inches", "18 inches", "24 inches"],
    correctIndex: 1,
    explanation: "Bus aisles must have at least 15 inches of clearance. Bags and items must not block the aisle. This ensures passengers can exit safely in an emergency.",
    section: "Bus Operations",
  },
  {
    id: "ps-010",
    question: "If your bus breaks down on a highway, you should:",
    options: [
      "Keep all passengers on the bus at all times",
      "Evacuate passengers far away from the bus to the shoulder",
      "Use your best judgment — staying on the bus may be safer than evacuating into traffic",
      "Leave passengers on the bus and walk to get help",
    ],
    correctIndex: 2,
    explanation: "Use your judgment based on the situation. Staying on the bus may be safer than evacuating passengers into traffic. But if fire, hazmat, or an unsafe location is involved, evacuate immediately. Set up emergency triangles.",
    section: "Emergency Procedures",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SCHOOL BUS ENDORSEMENT (20+ questions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const SCHOOL_BUS_QUESTIONS: CdlQuestion[] = [
  {
    id: "sb-001",
    question: "The danger zone around a school bus extends approximately:",
    options: ["5 feet in all directions", "10 feet in all directions", "15 feet in all directions", "20 feet from the front only"],
    correctIndex: 1,
    explanation: "The danger zone extends approximately 10 feet in all directions around the bus. Children are at greatest risk in this area because the driver may not see them. The area directly in front and to the right of the bus is the most dangerous.",
    section: "Danger Zone",
    diagramRef: "/assets/cdl/school-bus-danger-zones.png",
  },
  {
    id: "sb-002",
    question: "The most dangerous area of the school bus danger zone is:",
    options: [
      "Directly behind the bus",
      "The left side",
      "Directly in front where the driver cannot see small children",
      "The rear right corner",
    ],
    correctIndex: 2,
    explanation: "The area directly in front of the bus is the most dangerous. Small children may not be visible below the hood line if they bend down (to pick up a dropped object, for example). They can be run over if the bus moves forward.",
    section: "Danger Zone",
  },
  {
    id: "sb-003",
    question: "When loading students, you should activate the amber warning lights:",
    options: [
      "After the bus has stopped",
      "At least 200 feet before the stop (or about 100 feet in the city)",
      "Only in school zones",
      "They are not required during loading",
    ],
    correctIndex: 1,
    explanation: "Activate amber (yellow) warning lights at least 200 feet before the stop in rural areas and at least 100 feet in urban areas. This warns traffic that the bus is about to stop for passengers.",
    section: "Loading/Unloading",
  },
  {
    id: "sb-004",
    question: "If a student drops something near the bus, they should:",
    options: [
      "Pick it up immediately",
      "Leave it and tell the driver, who will retrieve it after students are safe",
      "Ask another student to pick it up",
      "Wait until the bus moves to pick it up",
    ],
    correctIndex: 1,
    explanation: "Students should NEVER bend down near the bus. If something is dropped, they should leave it and tell the driver. Bending down puts them in the driver's blind spot directly in front of or beside the bus.",
    section: "Danger Zone",
  },
  {
    id: "sb-005",
    question: "When making a stop to unload students who must cross the road, the students should walk:",
    options: [
      "Behind the bus to cross",
      "At least 10 feet in front of the bus so the driver can see them, then cross when signaled",
      "Across the road at any point near the bus",
      "To the nearest crosswalk, even if far from the bus",
    ],
    correctIndex: 1,
    explanation: "Students crossing the road should walk at least 10 feet in front of the bus (along the road edge) until they can see the driver and the driver can see them. They cross only when the driver gives the signal that it is safe.",
    section: "Loading/Unloading",
  },
  {
    id: "sb-006",
    question: "Mirror types on a school bus include all EXCEPT:",
    options: [
      "Flat exterior mirrors",
      "Convex exterior mirrors",
      "Crossover mirrors mounted on the front",
      "Telescoping rear-view camera mirrors",
    ],
    correctIndex: 3,
    explanation: "School buses use: flat exterior mirrors (for distance), convex exterior mirrors (for wider angle near the bus), and crossover mirrors (mounted on front hood to see the danger zone directly in front). Telescoping camera mirrors are not standard equipment.",
    section: "Equipment",
  },
  {
    id: "sb-007",
    question: "When do you activate the red flashing lights and STOP arm?",
    options: [
      "200 feet before the stop",
      "When the bus is fully stopped and ready to load/unload",
      "While slowing down for the stop",
      "Only when students are actively crossing",
    ],
    correctIndex: 1,
    explanation: "Activate the red flashing lights and STOP arm AFTER the bus has come to a complete stop and you are ready to open the door for loading/unloading. The amber lights should already have warned traffic that you were stopping.",
    section: "Loading/Unloading",
  },
  {
    id: "sb-008",
    question: "Emergency evacuation of a school bus is necessary when:",
    options: [
      "A student is misbehaving",
      "There is a fire, imminent danger of fire, or the bus is in an unsafe position (e.g., on railroad tracks)",
      "It is raining heavily",
      "The bus is at a railroad crossing",
    ],
    correctIndex: 1,
    explanation: "Evacuate when there is a fire, danger of fire, the bus cannot be moved from a dangerous location (railroad tracks, rising flood water), or there is a hazmat spill. Evacuate to at least 100 feet from the bus.",
    section: "Emergency Procedures",
  },
  {
    id: "sb-009",
    question: "Students should be evacuated to at least ____ from the bus in an emergency:",
    options: ["25 feet", "50 feet", "100 feet", "200 feet"],
    correctIndex: 2,
    explanation: "Students should be led at least 100 feet away from the bus in case of fire or explosion hazard. Upwind is preferable if fire is involved. Use both front and rear exits if possible.",
    section: "Emergency Procedures",
  },
  {
    id: "sb-010",
    question: "If your school bus stalls on railroad tracks, you should:",
    options: [
      "Try to restart the engine repeatedly",
      "Evacuate immediately — move students away from the tracks at a 45-degree angle toward the oncoming train",
      "Call the railroad company first",
      "Evacuate students directly away from the tracks, perpendicular to the rails",
    ],
    correctIndex: 1,
    explanation: "Evacuate immediately. Move students away from the tracks at a 45-degree angle TOWARD the direction of the oncoming train. This is because if a train hits the bus, debris is thrown in the direction of travel — away from your evacuation direction.",
    section: "Emergency Procedures",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MASTER EXPORT
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const CDL_QUESTION_BANK = {
  "General Knowledge": GENERAL_KNOWLEDGE_QUESTIONS,
  "Air Brakes": AIR_BRAKES_QUESTIONS,
  "Combination Vehicles": COMBINATION_VEHICLES_QUESTIONS,
  "Hazmat": HAZMAT_QUESTIONS,
  "Tanker": TANKER_QUESTIONS,
  "Doubles/Triples": DOUBLES_TRIPLES_QUESTIONS,
  "Passenger": PASSENGER_QUESTIONS,
  "School Bus": SCHOOL_BUS_QUESTIONS,
} as const;

export type CdlTestSection = keyof typeof CDL_QUESTION_BANK;

export const CDL_SECTION_META: Record<CdlTestSection, { passingScore: number; timeLimitMinutes: number; questionCount: number }> = {
  "General Knowledge": { passingScore: 80, timeLimitMinutes: 60, questionCount: 50 },
  "Air Brakes": { passingScore: 80, timeLimitMinutes: 25, questionCount: 25 },
  "Combination Vehicles": { passingScore: 80, timeLimitMinutes: 20, questionCount: 20 },
  "Hazmat": { passingScore: 80, timeLimitMinutes: 30, questionCount: 30 },
  "Tanker": { passingScore: 80, timeLimitMinutes: 20, questionCount: 20 },
  "Doubles/Triples": { passingScore: 80, timeLimitMinutes: 20, questionCount: 20 },
  "Passenger": { passingScore: 80, timeLimitMinutes: 20, questionCount: 20 },
  "School Bus": { passingScore: 80, timeLimitMinutes: 20, questionCount: 20 },
};
