import type { LearningModule } from "@/lib/modules/types";

export const hvac_101_Module: LearningModule = {
  "id": "hvac-101",
  "title": "HVAC Fundamentals",
  "description": "Learn the core principles of heating, ventilation, and air conditioning systems — from thermodynamics and the refrigeration cycle to ductwork design, electrical controls, and indoor air quality standards.",
  "subject": "Trades",
  "tags": [
    "core",
    "curriculum",
    "interactive",
    "trades",
    "hvac"
  ],
  "minAge": 16,
  "maxAge": 99,
  "version": "1.1.0",
  "difficultyBand": "beginner",
  "localeSupport": [
    "en"
  ],
  "thumbnail": "/placeholders/lesson-robot.svg",
  "learningObjectives": [
    "Explain the three modes of heat transfer and calculate heat loads using BTU measurements",
    "Trace the vapor-compression refrigeration cycle and identify the function of each major component",
    "Compare heating system types including furnaces, boilers, and heat pumps, and interpret AFUE ratings",
    "Calculate airflow requirements using CFM and static pressure for basic duct sizing",
    "Identify common HVAC electrical components and describe basic troubleshooting procedures for control circuits",
    "Apply ASHRAE 62.1 ventilation standards and evaluate indoor air quality using filtration ratings and CO₂ thresholds",
    "Demonstrate mastery of foundational HVAC concepts through integrated checkpoint assessments"
  ],
  "lessons": [
    {
      "id": "hvac-101-l01",
      "title": "Thermodynamics for HVAC",
      "type": "video",
      "duration": 10,
      "objectives": [
        "Define heat and describe the three modes of heat transfer",
        "Explain BTU and how it relates to HVAC system sizing",
        "Distinguish between sensible heat and latent heat"
      ],
      "chunks": [
        {
          "id": "hvac-101-l01-c1",
          "title": "Heat Transfer Modes",
          "content": "Heat is energy that always moves from a warmer object to a cooler one. This happens in three main ways: conduction, convection, and radiation.\n\nConduction is heat transfer through direct contact. If you touch a hot pan, the heat conducts directly to your hand. In HVAC, this happens as heat moves through walls, windows, and insulation.\n\nConvection is heat transfer through the movement of fluids (liquids or gases). When a furnace heats air, the warm, less dense air rises, and cooler, denser air sinks to take its place. This creates a natural circulation that distributes heat throughout a room.\n\nRadiation is heat transfer through electromagnetic waves, which can travel through empty space. The sun warms the Earth through radiation. You can also feel radiant heat from a fireplace or a hot stovetop from across the room.\n\nHVAC systems are designed to control all three modes of heat transfer to keep a building comfortable.",
          "visualPrompts": [
            "An animated diagram showing heat flowing from a hot object to a cold one.",
            "A simple icon for Conduction: a hand touching a hot pan handle.",
            "A simple icon for Convection: arrows showing warm air rising from a vent.",
            "A simple icon for Radiation: sun rays warming the earth."
          ]
        },
        {
          "id": "hvac-101-l01-c2",
          "title": "BTU and Heat Measurement",
          "content": "In HVAC, we measure heat using the British Thermal Unit, or BTU. One BTU is the amount of energy needed to raise the temperature of one pound of water by one degree Fahrenheit. HVAC equipment capacity is rated in BTUs per hour (BTU/h).\n\nFor example, a residential furnace might be rated at 80,000 BTU/h, while a window air conditioner might have a cooling capacity of 10,000 BTU/h. A 'ton' of cooling, a common industry term, is equal to 12,000 BTU/h.\n\nTo choose the right size system, technicians calculate a building's 'heat load.' This is the total BTUs per hour that must be added or removed to maintain a comfortable indoor temperature. The calculation considers factors like insulation quality, window size, climate, and heat generated by people and appliances inside the space. Sizing a system correctly is critical for both comfort and energy efficiency.",
          "visualPrompts": [
            "A graphic showing a pound of water, a thermometer rising by 1°F, and a '1 BTU' label.",
            "Side-by-side images of a furnace and an AC unit with their BTU/h ratings displayed.",
            "A simple house diagram with arrows pointing in (sun, people) and out (windows, walls) labeled 'Heat Load Factors'."
          ]
        },
        {
          "id": "hvac-101-l01-c3",
          "title": "Sensible Heat, Latent Heat, and Psychrometrics Basics",
          "content": "Heat comes in two forms: sensible and latent. Sensible heat is heat you can 'sense' or feel—it changes a substance's temperature, which you can measure with a thermometer. When you heat water from 70°F to 150°F, you are adding sensible heat.\n\nLatent heat is 'hidden' heat. It's the energy required to change a substance's state without changing its temperature. For example, when water at 212°F boils into steam at 212°F, it absorbs a large amount of latent heat.\n\nAir conditioners must remove both types of heat. Lowering the air temperature is sensible cooling. Removing moisture from the air by condensing it into water is latent cooling.\n\nPsychrometrics is the study of the properties of air-and-water-vapor mixtures. Technicians use a psychrometric chart to visualize properties like temperature, humidity, and dew point to predict how air will behave as it's conditioned.",
          "visualPrompts": [
            "A split-screen animation: on the left, a thermometer in water shows the temperature rising (Sensible Heat). On the right, a pot of boiling water at a constant 212°F turns to steam (Latent Heat).",
            "An animation of an AC coil showing both temperature dropping and water droplets forming on the fins.",
            "A simplified psychrometric chart with key areas labeled: Dry-Bulb Temp, Relative Humidity, and Dew Point."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l01-f1",
          "front": "What are the three modes of heat transfer?",
          "back": "Conduction (direct contact), convection (fluid movement), and radiation (electromagnetic waves)."
        },
        {
          "id": "hvac-101-l01-f2",
          "front": "What is a BTU?",
          "back": "A British Thermal Unit — the energy required to raise one pound of water by 1 °F. HVAC equipment is rated in BTU/h."
        },
        {
          "id": "hvac-101-l01-f3",
          "front": "What is the difference between sensible heat and latent heat?",
          "back": "Sensible heat changes temperature (measurable with a thermometer). Latent heat changes the state of matter (e.g., liquid to vapor) without changing temperature."
        },
        {
          "id": "hvac-101-l01-f4",
          "front": "What does a psychrometric chart show?",
          "back": "It plots the relationships between dry-bulb temperature, wet-bulb temperature, relative humidity, dew point, and enthalpy of air–water-vapor mixtures."
        }
      ],
      "learningAids": [
        {
          "id": "hvac-101-l01-a1",
          "type": "image",
          "title": "Concept Card",
          "content": "Visual summary of the lesson's main concept."
        }
      ]
    },
    {
      "id": "hvac-101-l02",
      "title": "The Refrigeration Cycle",
      "type": "interactive",
      "duration": 12,
      "objectives": [
        "Identify the four main components of the vapor-compression cycle",
        "Describe the state changes of refrigerant through each stage",
        "Explain the role of the metering device in pressure and temperature drop"
      ],
      "chunks": [
        {
          "id": "hvac-101-l02-c1",
          "title": "Compressor and Condenser",
          "content": "The refrigeration cycle starts at the compressor, the heart of the system. The compressor acts like a pump, taking in low-pressure, cool refrigerant gas from the evaporator and squeezing it into a high-pressure, hot gas.\n\nThis hot gas then flows to the condenser coil, which is typically in the outdoor unit. Here, a fan blows outdoor air across the coil's fins. The refrigerant releases its heat to the outside air, causing it to cool down and condense into a high-pressure liquid. This process is similar to how steam condenses back into water on a cool surface. To improve efficiency, the liquid refrigerant is often subcooled slightly below its condensation temperature before leaving the condenser.",
          "visualPrompts": [
            "An animated diagram of the refrigeration cycle, with the compressor highlighted.",
            "A visual of the refrigerant as a cool, low-pressure gas entering the compressor and leaving as a hot, high-pressure gas.",
            "An animation of the condenser coil with a fan blowing air across it, showing heat radiating away and the gas turning into a liquid."
          ]
        },
        {
          "id": "hvac-101-l02-c2",
          "title": "Expansion Valve and Evaporator",
          "content": "Next, the high-pressure liquid refrigerant flows to the metering device, often an expansion valve (like a TXV). This valve has a tiny opening that causes a sudden, large drop in pressure. As the pressure drops, the refrigerant's temperature plummets, and it begins to boil, turning into a very cold, low-pressure mixture of liquid and vapor.\n\nThis cold mixture enters the evaporator coil, located inside the space to be cooled. The indoor blower fan pushes warm room air across the evaporator. The cold refrigerant inside the coil absorbs heat from the air. This absorbed heat causes the rest of the liquid refrigerant to boil into a low-pressure gas. The air leaving the coil is now cool and dehumidified, providing the cooling effect for the building.",
          "visualPrompts": [
            "The refrigeration cycle diagram, now highlighting the expansion valve.",
            "An animation showing high-pressure liquid entering the valve and a cold, low-pressure spray exiting.",
            "The diagram highlighting the evaporator coil, with warm air blowing across it and cool air coming out, showing the liquid refrigerant inside boiling into a gas."
          ]
        },
        {
          "id": "hvac-101-l02-c3",
          "title": "Refrigerant States and the Complete Cycle",
          "content": "Let's trace the full loop of refrigerant states: \n1. Exits Evaporator: Low-pressure, cool gas.\n2. Exits Compressor: High-pressure, hot gas.\n3. Exits Condenser: High-pressure, warm liquid.\n4. Exits Expansion Valve: Low-pressure, cold liquid/vapor mix.\nThis cycle repeats continuously to move heat from inside to outside.\n\nCommon refrigerants today include R-410A, though newer, more environmentally friendly options like R-32 are becoming more common. The efficiency of this cycle is measured by its Coefficient of Performance (COP), which is the ratio of cooling provided to the electrical energy used. A higher COP means a more efficient system. Understanding these state changes is key to diagnosing and servicing HVAC equipment.",
          "visualPrompts": [
            "The complete, animated refrigeration cycle diagram showing all four components and the state of the refrigerant at each point, using color coding (e.g., red for hot gas, blue for cold liquid/vapor).",
            "A simple graphic showing common refrigerant cylinders like R-410A.",
            "A scale or gauge visual for COP, with 'Less Efficient' on one end and 'More Efficient' on the other."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l02-f1",
          "front": "What are the four main components of the vapor-compression refrigeration cycle?",
          "back": "Compressor, condenser, expansion (metering) device, and evaporator."
        },
        {
          "id": "hvac-101-l02-f2",
          "front": "What happens to the refrigerant in the evaporator?",
          "back": "It absorbs heat from indoor air and boils from a low-pressure liquid-vapor mixture into a low-pressure vapor."
        },
        {
          "id": "hvac-101-l02-f3",
          "front": "What does a thermostatic expansion valve (TXV) do?",
          "back": "It meters the flow of high-pressure liquid refrigerant, creating a sharp pressure drop that lowers its temperature before entering the evaporator."
        },
        {
          "id": "hvac-101-l02-f4",
          "front": "What is COP in refrigeration?",
          "back": "Coefficient of Performance — the ratio of useful cooling (or heating) output to electrical energy input. Higher COP means better efficiency."
        }
      ],
      "interactiveActivities": [
        {
          "id": "hvac-101-l02-a1",
          "type": "sorting_buckets",
          "title": "Refrigerant State at Each Component",
          "description": "Sort each refrigerant description into the correct refrigeration cycle component.",
          "estimatedMinutes": 5,
          "difficultyLevel": "medium",
          "buckets": [
            "Compressor",
            "Condenser",
            "Expansion Valve",
            "Evaporator"
          ],
          "items": [
            {
              "text": "Low-pressure vapor is squeezed into high-pressure superheated vapor",
              "bucket": "Compressor"
            },
            {
              "text": "High-pressure vapor rejects heat and condenses into a liquid",
              "bucket": "Condenser"
            },
            {
              "text": "High-pressure liquid drops to low pressure and temperature",
              "bucket": "Expansion Valve"
            },
            {
              "text": "Cold refrigerant absorbs indoor heat and boils into vapor",
              "bucket": "Evaporator"
            },
            {
              "text": "Subcooling occurs to improve efficiency",
              "bucket": "Condenser"
            },
            {
              "text": "Superheat is measured to verify proper charge",
              "bucket": "Evaporator"
            },
            {
              "text": "Discharge temperature is highest here",
              "bucket": "Compressor"
            },
            {
              "text": "A TXV or EEV meters refrigerant flow",
              "bucket": "Expansion Valve"
            }
          ]
        }
      ],
      "learningAids": [
        {
          "id": "hvac-101-l02-a1",
          "type": "practice",
          "title": "Guided Practice",
          "content": "Follow the prompt sequence and document your reasoning."
        }
      ]
    },
    {
      "id": "hvac-101-l03",
      "title": "Heat Transfer & Refrigeration Checkpoint",
      "type": "quiz",
      "duration": 8,
      "quizBlueprint": {
        "totalQuestions": 4,
        "bloomProfile": {
          "remember": 1,
          "understand": 2,
          "apply": 1
        }
      },
      "questions": [
        {
          "id": "hvac-101-l03-q1",
          "text": "Which mode of heat transfer requires direct physical contact between materials?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Radiation"
            },
            {
              "id": "b",
              "text": "Convection"
            },
            {
              "id": "c",
              "text": "Conduction"
            },
            {
              "id": "d",
              "text": "Evaporation"
            }
          ],
          "correctOptionId": "c",
          "explanation": "Conduction transfers heat through direct molecular contact. Convection requires fluid movement and radiation uses electromagnetic waves."
        },
        {
          "id": "hvac-101-l03-q2",
          "text": "An air conditioner removes moisture from indoor air. What type of heat is associated with this moisture removal?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Sensible heat"
            },
            {
              "id": "b",
              "text": "Latent heat"
            },
            {
              "id": "c",
              "text": "Radiant heat"
            },
            {
              "id": "d",
              "text": "Specific heat"
            }
          ],
          "correctOptionId": "b",
          "explanation": "Latent heat is the energy involved in a phase change. When moisture condenses on the evaporator coil, latent heat is removed from the air without changing its temperature."
        },
        {
          "id": "hvac-101-l03-q3",
          "text": "In the vapor-compression cycle, where does the refrigerant change from a high-pressure liquid to a low-pressure mixture?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Compressor"
            },
            {
              "id": "b",
              "text": "Condenser"
            },
            {
              "id": "c",
              "text": "Evaporator"
            },
            {
              "id": "d",
              "text": "Expansion valve"
            }
          ],
          "correctOptionId": "d",
          "explanation": "The expansion (metering) valve creates a sudden pressure drop, converting the high-pressure liquid into a cold, low-pressure liquid-vapor mixture before entering the evaporator."
        },
        {
          "id": "hvac-101-l03-q4",
          "text": "A system rated at 36,000 BTU/h is equivalent to how many tons of cooling?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "1 ton"
            },
            {
              "id": "b",
              "text": "2 tons"
            },
            {
              "id": "c",
              "text": "3 tons"
            },
            {
              "id": "d",
              "text": "4 tons"
            }
          ],
          "correctOptionId": "c",
          "explanation": "One ton of cooling equals 12,000 BTU/h. Therefore 36,000 ÷ 12,000 = 3 tons."
        }
      ],
      "learningAids": [
        {
          "id": "hvac-101-l03-a1",
          "type": "mnemonic",
          "title": "Memory Cue",
          "content": "Use Plan, Solve, Explain to structure each response."
        }
      ]
    },
    {
      "id": "hvac-101-l04",
      "title": "Heating Systems",
      "type": "video",
      "duration": 10,
      "objectives": [
        "Compare gas furnaces, boilers, and heat pumps as heating sources",
        "Explain combustion analysis and flue gas safety",
        "Interpret AFUE ratings to evaluate heating efficiency"
      ],
      "chunks": [
        {
          "id": "hvac-101-l04-c1",
          "title": "Furnaces and Combustion",
          "content": "A gas furnace is a common heating system that burns fuel like natural gas or propane. The combustion happens inside a sealed metal chamber called a heat exchanger. A blower fan pushes house air across the hot outer surface of the heat exchanger, warming the air before distributing it through the ductwork. The combustion gases never mix with the house air; they are safely vented outside.\n\nHigh-efficiency 'condensing' furnaces have a second heat exchanger to extract even more heat from the exhaust gas. This process cools the gas enough that water vapor condenses out, allowing these furnaces to achieve efficiency ratings over 90%.\n\nTechnicians perform a combustion analysis to ensure safe and efficient operation. They measure gases like carbon monoxide (CO) in the flue pipe. High CO levels can indicate a serious safety hazard, such as a cracked heat exchanger.",
          "visualPrompts": [
            "A cutaway animation of a gas furnace showing the flame inside the heat exchanger and the separate path of house air blowing over it.",
            "A diagram comparing a standard furnace to a condensing furnace, highlighting the secondary heat exchanger.",
            "A visual of a technician using a combustion analyzer probe in a flue pipe, with a digital readout showing CO levels."
          ]
        },
        {
          "id": "hvac-101-l04-c2",
          "title": "Boilers and Hydronic Heating",
          "content": "Instead of heating air, boilers heat water or create steam. This hot water or steam is then circulated through pipes to radiators, baseboard heaters, or tubing in the floor to heat the building. This is called a hydronic heating system.\n\nHot-water boilers typically operate between 140°F and 180°F. Radiant floor heating systems are very comfortable and can use lower water temperatures, making them a great match for high-efficiency condensing boilers.\n\nBoilers have critical safety devices, such as pressure-relief valves and low-water cutoffs, to prevent dangerous conditions. Regular maintenance is essential to verify these safety features are working correctly and to ensure the system runs efficiently.",
          "visualPrompts": [
            "An animated diagram of a hydronic system, showing the boiler, pipes, and a radiator releasing heat into a room.",
            "An image of radiant floor heating tubing being installed in a concrete slab.",
            "Close-up shots of key safety components: a pressure-relief valve and an expansion tank."
          ]
        },
        {
          "id": "hvac-101-l04-c3",
          "title": "Heat Pumps and AFUE Ratings",
          "content": "A heat pump is essentially a reversible air conditioner. In summer, it functions as a standard AC, moving heat from inside to outside. In winter, a reversing valve changes the flow of refrigerant, allowing the unit to absorb heat from the cold outdoor air and move it inside to heat the home.\n\nAir-source heat pumps are most effective in moderate climates. Geothermal (or ground-source) heat pumps are more efficient in very cold climates because they exchange heat with the ground, which has a more stable temperature.\n\nFor furnaces and boilers, efficiency is measured by AFUE (Annual Fuel Utilization Efficiency). An 80% AFUE furnace converts 80 cents of every fuel dollar into usable heat. Heat pump heating efficiency is rated by HSPF (Heating Seasonal Performance Factor). A higher HSPF rating means better efficiency.",
          "visualPrompts": [
            "A split-screen animation of a heat pump: on the left (cooling), heat is absorbed indoors and rejected outdoors. On the right (heating), the flow is reversed.",
            "A graphic that looks like a dollar bill, with 95% labeled 'Heat for Home' and 5% labeled 'Lost' to illustrate 95% AFUE.",
            "A simple gauge showing HSPF ratings, with a pointer in the 'High Efficiency' zone."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l04-f1",
          "front": "What does AFUE stand for and what does it measure?",
          "back": "Annual Fuel Utilization Efficiency — the percentage of fuel energy a furnace or boiler converts into usable heat over a heating season."
        },
        {
          "id": "hvac-101-l04-f2",
          "front": "What makes a condensing furnace more efficient than a standard furnace?",
          "back": "It has a secondary heat exchanger that recovers latent heat from combustion flue gases, achieving AFUE ratings above 90%."
        },
        {
          "id": "hvac-101-l04-f3",
          "front": "How does a heat pump provide heating in winter?",
          "back": "It reverses the refrigeration cycle — the outdoor coil acts as an evaporator absorbing heat from outside air (or ground), and the indoor coil acts as a condenser releasing heat indoors."
        },
        {
          "id": "hvac-101-l04-f4",
          "front": "Why is combustion analysis important?",
          "back": "It measures CO, CO₂, O₂, and stack temperature to verify safe, complete combustion and detect dangerous conditions like a cracked heat exchanger."
        }
      ],
      "learningAids": [
        {
          "id": "hvac-101-l04-a1",
          "type": "image",
          "title": "Concept Card",
          "content": "Visual summary of the lesson's main concept."
        }
      ]
    },
    {
      "id": "hvac-101-l05",
      "title": "Air Distribution and Ductwork",
      "type": "interactive",
      "duration": 12,
      "objectives": [
        "Define static pressure and explain its role in duct design",
        "Calculate basic CFM requirements for a room",
        "Describe the purpose of dampers and air balancing"
      ],
      "chunks": [
        {
          "id": "hvac-101-l05-c1",
          "title": "Static Pressure and CFM",
          "content": "CFM (Cubic Feet per Minute) measures the volume of air the system's blower moves. Static pressure is the resistance the blower must push against to move that air through the duct system. It's measured in inches of water column (in. w.c.).\n\nThink of static pressure like blood pressure. If it's too high, the heart (the blower) has to work too hard. High static pressure is often caused by undersized ducts, dirty filters, or restrictive grilles. It leads to poor airflow, increased noise, and wasted energy.\n\nA common rule of thumb for cooling is to provide 400 CFM of airflow per ton of cooling capacity. Proper duct design aims to keep the total static pressure within the manufacturer's specified range, typically below 0.5 in. w.c. for residential systems.",
          "visualPrompts": [
            "An animation of a blower fan pushing air into a duct system, with arrows indicating the force of static pressure pushing back.",
            "A visual comparison: a wide, clear duct with low static pressure vs. a narrow, clogged duct with high static pressure.",
            "A simple equation graphic: '1 Ton Cooling ≈ 400 CFM Airflow'."
          ]
        },
        {
          "id": "hvac-101-l05-c2",
          "title": "Duct Types and Sizing",
          "content": "Ducts are the pathways for conditioned air. The most common types are rigid sheet metal and flexible insulated ducts.\n\nSheet metal ducts are durable and have a smooth interior, which creates less friction and allows air to flow efficiently. Flexible ducts, or 'flex ducts,' are easier to install in tight spaces but must be installed correctly. They should be pulled taut and properly supported to prevent sagging or sharp bends, which can severely restrict airflow.\n\nDucts must be sized correctly to handle the required CFM for each room without creating excessive static pressure. Technicians use industry standards like ACCA's Manual D to design duct systems that deliver the right amount of air quietly and efficiently.",
          "visualPrompts": [
            "Side-by-side images of rigid sheet metal ductwork and flexible insulated ductwork.",
            "A 'Do and Don't' visual for flex duct: a properly stretched, supported duct vs. a sagging, compressed duct.",
            "A cover image of the ACCA Manual D guide."
          ]
        },
        {
          "id": "hvac-101-l05-c3",
          "title": "Dampers and Air Balancing",
          "content": "Dampers are adjustable plates inside the ductwork that act like valves to control airflow. They are installed in the branch ducts that lead to individual rooms.\n\nAir balancing is the process of adjusting these dampers to ensure each room receives its designed amount of airflow (CFM). Without proper balancing, some rooms may be too hot or cold, while others are perfectly comfortable. Technicians use a tool called a flow hood, which fits over a supply register, to measure the exact CFM being delivered.\n\nBy systematically measuring and adjusting the airflow to each room, a technician can balance the entire system, leading to improved comfort, better efficiency, and a quieter system.",
          "visualPrompts": [
            "A cutaway view of a duct with a balancing damper shown in both open and partially closed positions.",
            "A diagram of a house with arrows of different sizes showing unbalanced airflow, then a second diagram with balanced airflow after damper adjustment.",
            "A photo or simple illustration of a technician holding a flow hood over a ceiling register."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l05-f1",
          "front": "What does CFM stand for and why does it matter?",
          "back": "Cubic Feet per Minute — it measures the volume of air moved by the blower. Correct CFM ensures adequate cooling/heating and comfort."
        },
        {
          "id": "hvac-101-l05-f2",
          "front": "What is static pressure in ductwork?",
          "back": "The resistance to airflow inside the duct system, measured in inches of water column (in. w.c.). High static pressure reduces airflow and strains the blower."
        },
        {
          "id": "hvac-101-l05-f3",
          "front": "What is the rule-of-thumb CFM per ton of cooling?",
          "back": "Approximately 400 CFM per ton (12,000 BTU/h) of cooling capacity."
        },
        {
          "id": "hvac-101-l05-f4",
          "front": "What is the purpose of air balancing?",
          "back": "To measure and adjust airflow at each register so every room receives its design CFM, eliminating hot/cold spots."
        }
      ],
      "interactiveActivities": [
        {
          "id": "hvac-101-l05-a1",
          "type": "matching_pairs",
          "title": "Duct System Components",
          "description": "Match each air distribution term to its correct definition.",
          "estimatedMinutes": 5,
          "difficultyLevel": "medium",
          "pairs": [
            {
              "left": "Static pressure",
              "right": "Resistance to airflow measured in in. w.c."
            },
            {
              "left": "CFM",
              "right": "Volume of air moved per minute"
            },
            {
              "left": "Flex duct",
              "right": "Insulated flexible hose that must be pulled taut"
            },
            {
              "left": "Balancing damper",
              "right": "Adjustable plate that regulates branch airflow"
            },
            {
              "left": "Flow hood",
              "right": "Instrument that measures air volume at a register"
            },
            {
              "left": "Manual D",
              "right": "ACCA standard for residential duct design"
            }
          ]
        }
      ],
      "learningAids": [
        {
          "id": "hvac-101-l05-a1",
          "type": "practice",
          "title": "Guided Practice",
          "content": "Follow the prompt sequence and document your reasoning."
        }
      ]
    },
    {
      "id": "hvac-101-l06",
      "title": "Heating & Airflow Checkpoint",
      "type": "quiz",
      "duration": 8,
      "quizBlueprint": {
        "totalQuestions": 4,
        "bloomProfile": {
          "remember": 1,
          "understand": 1,
          "apply": 2
        }
      },
      "questions": [
        {
          "id": "hvac-101-l06-q1",
          "text": "A furnace with a 92% AFUE rating is classified as which type?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Standard-efficiency furnace"
            },
            {
              "id": "b",
              "text": "Mid-efficiency furnace"
            },
            {
              "id": "c",
              "text": "Condensing furnace"
            },
            {
              "id": "d",
              "text": "Electric resistance furnace"
            }
          ],
          "correctOptionId": "c",
          "explanation": "Condensing furnaces have AFUE ratings of 90% or higher because they recover latent heat from flue gases via a secondary heat exchanger. Standard-efficiency units are typically 80% AFUE."
        },
        {
          "id": "hvac-101-l06-q2",
          "text": "A 3-ton cooling system requires approximately how many CFM of airflow?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "800 CFM"
            },
            {
              "id": "b",
              "text": "1,000 CFM"
            },
            {
              "id": "c",
              "text": "1,200 CFM"
            },
            {
              "id": "d",
              "text": "1,600 CFM"
            }
          ],
          "correctOptionId": "c",
          "explanation": "The rule of thumb is 400 CFM per ton. 3 tons × 400 CFM = 1,200 CFM."
        },
        {
          "id": "hvac-101-l06-q3",
          "text": "Which heating system uses a reversible refrigeration cycle?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Gas furnace"
            },
            {
              "id": "b",
              "text": "Steam boiler"
            },
            {
              "id": "c",
              "text": "Electric baseboard"
            },
            {
              "id": "d",
              "text": "Heat pump"
            }
          ],
          "correctOptionId": "d",
          "explanation": "A heat pump reverses the refrigeration cycle with a reversing valve, allowing it to provide either heating or cooling by switching the roles of the indoor and outdoor coils."
        },
        {
          "id": "hvac-101-l06-q4",
          "text": "Excessive static pressure in a duct system is most likely caused by which condition?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Oversized ductwork"
            },
            {
              "id": "b",
              "text": "A clean, low-MERV filter"
            },
            {
              "id": "c",
              "text": "Undersized ducts and clogged filters"
            },
            {
              "id": "d",
              "text": "An open bypass damper"
            }
          ],
          "correctOptionId": "c",
          "explanation": "Undersized ducts restrict airflow and dirty/clogged filters add resistance, both significantly increasing static pressure above the system's design limit."
        }
      ]
    },
    {
      "id": "hvac-101-l07",
      "title": "Controls and Electrical for HVAC",
      "type": "video",
      "duration": 10,
      "objectives": [
        "Identify common electrical components: thermostats, relays, contactors, and capacitors",
        "Read a basic HVAC wiring diagram",
        "Describe systematic troubleshooting steps for control circuits"
      ],
      "chunks": [
        {
          "id": "hvac-101-l07-c1",
          "title": "Thermostats and Control Signals",
          "content": "The thermostat is the brain of the HVAC system. It senses the room temperature and compares it to the desired set point. When needed, it sends a low-voltage signal, typically 24 volts AC (VAC), to the heating or cooling equipment to turn on.\n\nStandard thermostat wire colors indicate their function, making installation and troubleshooting easier. The most common are: R for 24V power, G for the indoor fan, Y for cooling, and W for heating. The C wire is a common wire that completes the circuit for modern thermostats.\n\nModern smart thermostats can be programmed with schedules to save energy, for example, by automatically lowering the temperature at night or when no one is home. They provide greater control and can significantly reduce utility bills.",
          "visualPrompts": [
            "An animation showing a thermostat sensing the temperature drop, then sending a signal down a wire to a furnace, which then turns on.",
            "A clear, color-coded diagram of the R, G, Y, W, and C thermostat terminals and wires.",
            "An image of a smart thermostat's screen showing a daily schedule."
          ]
        },
        {
          "id": "hvac-101-l07-c2",
          "title": "Relays, Contactors, and Capacitors",
          "content": "Relays and contactors are electrically-operated switches. The low-voltage signal from the thermostat energizes a small electromagnetic coil. This coil's magnetic field closes a switch to control a much higher voltage circuit, like the one powering a blower motor or compressor.\n\nContactors are simply heavy-duty relays designed to handle the high electrical current drawn by large motors. \n\nCapacitors are like temporary batteries. They store an electrical charge and release it to give a motor an extra 'boost' of power to start turning. A run capacitor stays in the circuit to help the motor run more efficiently. A weak or failed capacitor is a common reason a motor won't start.",
          "visualPrompts": [
            "An animated diagram of a contactor: a 24V signal energizes a coil, which magnetically pulls a switch closed to complete a 240V circuit to a motor.",
            "Side-by-side images of a small fan relay and a larger compressor contactor.",
            "An animation of a capacitor charging and then discharging a burst of energy to a motor at startup."
          ]
        },
        {
          "id": "hvac-101-l07-c3",
          "title": "Troubleshooting Control Circuits",
          "content": "A systematic approach is key to troubleshooting electrical issues. The process follows the path of electricity:\n1. Check for high voltage (120V or 240V) at the equipment's disconnect switch.\n2. Verify the control transformer is outputting 24 VAC.\n3. Trace the 24V signal from the thermostat's R terminal through the call (e.g., Y for cooling) to the component being controlled, like the contactor coil.\n\nCommon problems include a blown low-voltage fuse on the control board (often caused by a shorted thermostat wire), a bad contactor coil, or a failed capacitor. A multimeter is an essential tool for checking voltage and capacitance.\n\nSAFETY FIRST: Always turn off, lock out, and tag out the power source before working on any high-voltage components.",
          "visualPrompts": [
            "A flowchart for basic electrical troubleshooting.",
            "A technician using a multimeter to test voltage at a transformer's terminals.",
            "A visual of a 'Lockout/Tagout' lock on a power disconnect switch."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l07-f1",
          "front": "What voltage do most residential HVAC control circuits use?",
          "back": "24 VAC, stepped down from 120 V by a control transformer."
        },
        {
          "id": "hvac-101-l07-f2",
          "front": "What is the difference between a relay and a contactor?",
          "back": "Both are electromagnetic switches, but a contactor is designed for higher-amperage loads like compressor motors, while a relay handles lighter loads."
        },
        {
          "id": "hvac-101-l07-f3",
          "front": "What do the thermostat wire colors R, G, Y, and W typically control?",
          "back": "R = 24 V power, G = indoor fan, Y = cooling (compressor), W = heating."
        },
        {
          "id": "hvac-101-l07-f4",
          "front": "How do you test a run capacitor?",
          "back": "Use a multimeter on the capacitance (µF) setting. If the reading is more than ±6% from the rated value printed on the capacitor, it should be replaced."
        }
      ]
    },
    {
      "id": "hvac-101-l08",
      "title": "Indoor Air Quality and Ventilation",
      "type": "interactive",
      "duration": 12,
      "objectives": [
        "Summarize ASHRAE Standard 62.1 ventilation requirements",
        "Compare filter efficiency using MERV ratings",
        "Identify acceptable indoor CO₂ and humidity ranges"
      ],
      "chunks": [
        {
          "id": "hvac-101-l08-c1",
          "title": "ASHRAE 62.1 Ventilation Standard",
          "content": "Good indoor air quality (IAQ) requires proper ventilation—bringing in fresh outdoor air to dilute and remove indoor pollutants. ASHRAE Standard 62.1 is the industry guideline that specifies the minimum ventilation rates for commercial buildings.\n\nThe required amount of fresh air is based on the size of the space and the number of people in it. The goal is to control indoor pollutants like carbon dioxide (CO₂), volatile organic compounds (VOCs) from building materials, and other contaminants.\n\nDemand-Controlled Ventilation (DCV) is a smart strategy that adjusts ventilation based on occupancy. It uses CO₂ sensors to monitor the space. When CO₂ levels rise, indicating more people are present, the system automatically brings in more fresh air. This saves significant energy compared to ventilating a building at maximum capacity all the time.",
          "visualPrompts": [
            "An animation of a building with stale air (red) being pushed out as fresh air (blue) is brought in by a ventilation system.",
            "A simple graphic showing the ASHRAE 62.1 calculation: (CFM per person x # of people) + (CFM per sq. ft. x area).",
            "A diagram of a DCV system: a CO₂ sensor in a room sends a signal to a motorized damper on the fresh air intake."
          ]
        },
        {
          "id": "hvac-101-l08-c2",
          "title": "Filtration and MERV Ratings",
          "content": "Air filters are essential for cleaning the air that circulates through an HVAC system. Their effectiveness is rated on the MERV (Minimum Efficiency Reporting Value) scale, which ranges from 1 to 20. A higher MERV number means the filter can capture smaller particles.\n\n- MERV 1-4: Captures large particles like dust and lint.\n- MERV 8: A good standard for homes, capturing mold spores and pollen.\n- MERV 13: Recommended for commercial buildings, capturing bacteria, smoke, and fine dust.\n- MERV 17-20: HEPA-level filtration, used in hospitals and clean rooms.\n\nThere is a trade-off: a higher MERV filter is denser and creates more resistance to airflow (higher static pressure). The HVAC system must be designed to handle this resistance to ensure it can still move the proper amount of air.",
          "visualPrompts": [
            "A visual scale of MERV ratings, showing the types of particles captured at different levels (e.g., MERV 4 captures dust, MERV 8 captures mold, MERV 13 captures bacteria).",
            "A microscopic view showing particles being trapped in a filter's fibers.",
            "A 'balancing scale' visual showing 'Filtration Quality' on one side and 'Airflow Resistance' on the other."
          ]
        },
        {
          "id": "hvac-101-l08-c3",
          "title": "Humidity Control and CO₂ Monitoring",
          "content": "Maintaining proper indoor humidity is critical for both comfort and health. The ideal range for relative humidity is between 30% and 60%.\n\n- Below 30%: Air is too dry, which can cause skin irritation, static electricity, and damage to wood furniture.\n- Above 60%: Air is too damp, which can promote the growth of mold, mildew, and dust mites.\n\nCarbon dioxide (CO₂) levels are a key indicator of ventilation effectiveness. Outdoor air has a CO₂ concentration of about 420 parts per million (ppm). Indoor levels should be kept below 1,000 ppm. Levels consistently above this suggest that not enough fresh air is being brought into the space.",
          "visualPrompts": [
            "A gauge for relative humidity with a green 'comfort zone' between 30% and 60%.",
            "Images showing the effects of improper humidity: cracked wood for low humidity, mold on a wall for high humidity.",
            "A CO₂ meter showing a reading of 850 ppm with a 'Good' indicator, and another showing 1,400 ppm with a 'Ventilate' indicator."
          ]
        }
      ],
      "flashcards": [
        {
          "id": "hvac-101-l08-f1",
          "front": "What does ASHRAE 62.1 specify?",
          "back": "Minimum outdoor-air ventilation rates for commercial buildings to maintain acceptable indoor air quality."
        },
        {
          "id": "hvac-101-l08-f2",
          "front": "What MERV rating does ASHRAE recommend for most commercial buildings?",
          "back": "MERV 13 — it captures bacteria, smoke, and fine particles down to 0.3–1.0 µm."
        },
        {
          "id": "hvac-101-l08-f3",
          "front": "What is the recommended indoor relative humidity range?",
          "back": "30% to 60%. Below 30% causes dryness; above 60% promotes mold growth."
        },
        {
          "id": "hvac-101-l08-f4",
          "front": "What indoor CO₂ level indicates adequate ventilation?",
          "back": "Below 1,000 ppm. Outdoor air is roughly 420 ppm, so staying under 1,000 ppm means sufficient fresh air is being supplied."
        }
      ],
      "interactiveActivities": [
        {
          "id": "hvac-101-l08-a1",
          "type": "sorting_buckets",
          "title": "Filter MERV Rating Categories",
          "description": "Sort each description into the correct MERV rating range.",
          "estimatedMinutes": 5,
          "difficultyLevel": "medium",
          "buckets": [
            "MERV 1–4",
            "MERV 5–8",
            "MERV 9–12",
            "MERV 13–16"
          ],
          "items": [
            {
              "text": "Catches large debris like dust bunnies and textile fibers",
              "bucket": "MERV 1–4"
            },
            {
              "text": "Captures mold spores and dust-mite allergens",
              "bucket": "MERV 5–8"
            },
            {
              "text": "Filters auto-emission particles and fine dust",
              "bucket": "MERV 9–12"
            },
            {
              "text": "Captures bacteria, smoke, and aerosol droplets",
              "bucket": "MERV 13–16"
            },
            {
              "text": "Minimal pressure drop; basic equipment protection",
              "bucket": "MERV 1–4"
            },
            {
              "text": "ASHRAE-recommended level for most commercial HVAC",
              "bucket": "MERV 13–16"
            },
            {
              "text": "Common residential furnace filter level",
              "bucket": "MERV 5–8"
            },
            {
              "text": "Traps Legionella and fine pet dander",
              "bucket": "MERV 9–12"
            }
          ]
        }
      ]
    },
    {
      "id": "hvac-101-l09",
      "title": "Controls & IAQ Checkpoint",
      "type": "quiz",
      "duration": 8,
      "quizBlueprint": {
        "totalQuestions": 4,
        "bloomProfile": {
          "remember": 1,
          "understand": 2,
          "apply": 1
        }
      },
      "questions": [
        {
          "id": "hvac-101-l09-q1",
          "text": "On a standard residential thermostat, which wire color typically controls the cooling compressor?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "R (red)"
            },
            {
              "id": "b",
              "text": "G (green)"
            },
            {
              "id": "c",
              "text": "Y (yellow)"
            },
            {
              "id": "d",
              "text": "W (white)"
            }
          ],
          "correctOptionId": "c",
          "explanation": "Y (yellow) carries the cooling call from the thermostat, energizing the compressor contactor. R is power, G is the fan, and W is heat."
        },
        {
          "id": "hvac-101-l09-q2",
          "text": "A run capacitor on a compressor motor reads 38 µF but is rated at 45 µF. What should the technician do?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Leave it — 38 µF is within tolerance"
            },
            {
              "id": "b",
              "text": "Replace it — it is more than 6% below its rated value"
            },
            {
              "id": "c",
              "text": "Add a second capacitor in parallel"
            },
            {
              "id": "d",
              "text": "Increase the supply voltage"
            }
          ],
          "correctOptionId": "b",
          "explanation": "38 µF is about 15.5% below the 45 µF rating, well beyond the ±6% tolerance. A weak capacitor causes the motor to draw excessive amps and overheat."
        },
        {
          "id": "hvac-101-l09-q3",
          "text": "According to ASHRAE 62.1, what is the maximum recommended indoor CO₂ concentration for occupied spaces?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "400 ppm"
            },
            {
              "id": "b",
              "text": "800 ppm"
            },
            {
              "id": "c",
              "text": "1,000 ppm"
            },
            {
              "id": "d",
              "text": "5,000 ppm"
            }
          ],
          "correctOptionId": "c",
          "explanation": "ASHRAE guidelines recommend keeping indoor CO₂ below 1,000 ppm. Levels above this indicate insufficient outdoor-air ventilation."
        },
        {
          "id": "hvac-101-l09-q4",
          "text": "Which MERV rating range is considered HEPA-level filtration used in hospitals?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "MERV 5–8"
            },
            {
              "id": "b",
              "text": "MERV 9–12"
            },
            {
              "id": "c",
              "text": "MERV 13–16"
            },
            {
              "id": "d",
              "text": "MERV 17–20"
            }
          ],
          "correctOptionId": "d",
          "explanation": "MERV 17–20 corresponds to HEPA filtration, capturing at least 99.97% of particles 0.3 µm and larger. These filters are used in hospitals, clean rooms, and critical environments."
        }
      ]
    },
    {
      "id": "hvac-101-l10",
      "title": "Mastery Quiz: HVAC Foundations",
      "type": "quiz",
      "duration": 10,
      "quizBlueprint": {
        "totalQuestions": 4,
        "bloomProfile": {
          "understand": 1,
          "apply": 2,
          "analyze": 1
        }
      },
      "questions": [
        {
          "id": "hvac-101-l10-q1",
          "text": "A building's cooling load is 60,000 BTU/h. What tonnage system and approximate blower CFM are needed?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "3 tons / 1,200 CFM"
            },
            {
              "id": "b",
              "text": "5 tons / 2,000 CFM"
            },
            {
              "id": "c",
              "text": "5 tons / 2,500 CFM"
            },
            {
              "id": "d",
              "text": "6 tons / 2,400 CFM"
            }
          ],
          "correctOptionId": "b",
          "explanation": "60,000 BTU/h ÷ 12,000 BTU/ton = 5 tons. At 400 CFM per ton, the blower needs approximately 2,000 CFM."
        },
        {
          "id": "hvac-101-l10-q2",
          "text": "A technician finds that a heat pump heats well at 45 °F outdoor temperature but struggles at 15 °F. What is the most likely explanation?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "The compressor has failed"
            },
            {
              "id": "b",
              "text": "Air-source heat pumps lose heating capacity as outdoor temperature drops"
            },
            {
              "id": "c",
              "text": "The thermostat is wired incorrectly"
            },
            {
              "id": "d",
              "text": "The evaporator is oversized"
            }
          ],
          "correctOptionId": "b",
          "explanation": "Air-source heat pumps extract heat from outdoor air. As the outdoor temperature falls, there is less heat available and the unit's capacity decreases, often requiring auxiliary strip heat below a balance point."
        },
        {
          "id": "hvac-101-l10-q3",
          "text": "During commissioning, a technician measures 350 CFM at a supply register that should deliver 500 CFM. Which action is most appropriate?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Increase the thermostat set point"
            },
            {
              "id": "b",
              "text": "Open the branch balancing damper and re-measure"
            },
            {
              "id": "c",
              "text": "Replace the register grille"
            },
            {
              "id": "d",
              "text": "Add refrigerant to the system"
            }
          ],
          "correctOptionId": "b",
          "explanation": "Low airflow at a register usually means the balancing damper on that branch is partially closed. Opening it and re-measuring is the correct air-balancing procedure."
        },
        {
          "id": "hvac-101-l10-q4",
          "text": "An occupied conference room reads 1,400 ppm CO₂ and 72 °F. What should the technician adjust FIRST?",
          "skillId": "hvac-101-skill-core",
          "options": [
            {
              "id": "a",
              "text": "Lower the thermostat to 68 °F"
            },
            {
              "id": "b",
              "text": "Increase outdoor-air damper opening"
            },
            {
              "id": "c",
              "text": "Replace the air filter"
            },
            {
              "id": "d",
              "text": "Add a dehumidifier"
            }
          ],
          "correctOptionId": "b",
          "explanation": "1,400 ppm CO₂ exceeds the 1,000 ppm guideline, indicating insufficient ventilation. Increasing the outdoor-air damper opening brings in more fresh air to dilute CO₂. Temperature is already acceptable at 72 °F."
        }
      ]
    }
  ]
};
