import type { LearningModule } from "@/lib/modules/types";

export const science101Module: LearningModule = {
  id: "science-101",
  title: "Our Solar System",
  description: "Explore planets, orbits, and solar-system patterns through guided media and interactive practice.",
  subject: "Science",
  tags: ["space", "astronomy", "interactive"],
  minAge: 6,
  maxAge: 12,
  version: "1.1.0",
  learningObjectives: [
    "Identify key features of inner and outer planets.",
    "Explain why planets orbit the Sun in predictable paths.",
    "Use evidence to compare planetary environments.",
  ],
  lessons: [
    {
      id: "s101-l1",
      title: "The Sun and Inner Planets",
      type: "video",
      duration: 10,
      learningAids: [
        { id: "s101-l1-a1", type: "image", title: "Inner Planet Scale Card", content: "Compare Mercury, Venus, Earth, and Mars by size and distance." },
      ],
    },
    {
      id: "s101-l2",
      title: "Interactive: Planet Size Sort",
      type: "interactive",
      duration: 9,
      metadata: {
        prompts: [
          "Sort planets from smallest to largest and explain your evidence.",
          "Group planets by rocky vs gas/ice giant and explain the pattern.",
          "Choose one planet and describe one surprising fact.",
        ],
      },
      interactiveActivities: [
        {
          id: "s101-l2-ia1",
          type: "sorting_buckets",
          title: "Planet Type Sort",
          description: "Sort planets by composition and compare relative size.",
          estimatedMinutes: 8,
          difficultyLevel: "easy",
          instructions: [
            "Read each planet card.",
            "Drop it into rocky or gas/ice giant.",
            "Check size ranking hints after submit.",
          ],
          data: {
            buckets: [
              { id: "rocky", label: "Rocky Planet" },
              { id: "giant", label: "Gas or Ice Giant" },
            ],
            items: [
              { id: "mercury", label: "Mercury", correctBucketId: "rocky" },
              { id: "venus", label: "Venus", correctBucketId: "rocky" },
              { id: "earth", label: "Earth", correctBucketId: "rocky" },
              { id: "mars", label: "Mars", correctBucketId: "rocky" },
              { id: "jupiter", label: "Jupiter", correctBucketId: "giant" },
              { id: "saturn", label: "Saturn", correctBucketId: "giant" },
              { id: "uranus", label: "Uranus", correctBucketId: "giant" },
              { id: "neptune", label: "Neptune", correctBucketId: "giant" },
            ],
          },
        },
      ],
      learningAids: [
        { id: "s101-l2-a1", type: "practice", title: "Planet Card Sort", content: "Drag and drop planets into category bins." },
      ],
    },
    {
      id: "s101-l3",
      title: "Checkpoint Quiz: Inner Planets",
      type: "quiz",
      duration: 9,
      questions: [
        {
          id: "s101-l3-q1",
          text: "Which planet is known as the Red Planet?",
          skillId: "planet-identification",
          options: [
            { id: "a", text: "Mars" },
            { id: "b", text: "Venus" },
            { id: "c", text: "Jupiter" },
            { id: "d", text: "Saturn" },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l3-q2",
          text: "Which inner planet has the thickest cloud cover and is hottest?",
          skillId: "planet-comparison",
          options: [
            { id: "a", text: "Mercury" },
            { id: "b", text: "Venus" },
            { id: "c", text: "Earth" },
            { id: "d", text: "Mars" },
          ],
          correctOptionId: "b",
        },
        {
          id: "s101-l3-q3",
          text: "What do all inner planets have in common?",
          skillId: "planet-classification",
          options: [
            { id: "a", text: "They are rocky planets." },
            { id: "b", text: "They all have rings." },
            { id: "c", text: "They are gas giants." },
            { id: "d", text: "They orbit beyond Saturn." },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l3-q4",
          text: "Which planet is our home planet?",
          skillId: "planet-identification",
          options: [
            { id: "a", text: "Mars" },
            { id: "b", text: "Earth" },
            { id: "c", text: "Neptune" },
            { id: "d", text: "Mercury" },
          ],
          correctOptionId: "b",
        },
      ],
      interactiveActivities: [
        {
          id: "s101-l3-ia1",
          type: "matching_pairs",
          title: "Inner Planet Concept Match",
          description: "Match each inner-planet clue to the best scientific statement.",
          estimatedMinutes: 7,
          difficultyLevel: "medium",
          data: {
            left: [
              { id: "l1", label: "Red Planet" },
              { id: "l2", label: "Hottest inner planet with thick clouds" },
              { id: "l3", label: "All inner planets share this trait" },
            ],
            right: [
              { id: "r1", label: "Mars" },
              { id: "r2", label: "Venus" },
              { id: "r3", label: "Mostly rocky composition" },
            ],
            pairs: [
              { leftId: "l1", rightId: "r1" },
              { leftId: "l2", rightId: "r2" },
              { leftId: "l3", rightId: "r3" },
            ],
          },
        },
      ],
      quizBlueprint: {
        frequency: "lesson_assessment",
        questionsPerCheck: 4,
        totalQuestions: 4,
        timeLimitMinutes: 9,
        questionTypes: [{ type: "mcq_single", count: 4, pointsEach: 1, bloomsLevels: [1, 2, 3] }],
        difficultyDistribution: { easy: 1, medium: 2, hard: 1 },
        feedbackMode: "after_submit",
        adaptive: false,
        masteryThreshold: 0.75,
      },
    },
    {
      id: "s101-l4",
      title: "The Outer Planets",
      type: "video",
      duration: 12,
      learningAids: [
        { id: "s101-l4-a1", type: "image", title: "Outer Planet Snapshot", content: "Visual chart of Jupiter, Saturn, Uranus, and Neptune." },
        { id: "s101-l4-a2", type: "animation", title: "Gas Giant Layers", content: "Layered animation showing gas-giant structure." },
      ],
    },
    {
      id: "s101-l5",
      title: "Interactive: Orbit Simulator",
      type: "interactive",
      duration: 15,
      metadata: {
        prompts: [
          "Move a planet closer to the Sun and observe orbit speed changes.",
          "Compare one inner and one outer planet orbit and explain differences.",
          "Describe why all planets stay in orbit instead of flying away.",
        ],
      },
      interactiveActivities: [
        {
          id: "s101-l5-ia1",
          type: "simulation",
          title: "Orbit Speed Sandbox",
          description: "Adjust orbital distance and compare speed and period changes.",
          estimatedMinutes: 10,
          difficultyLevel: "medium",
          instructions: [
            "Choose a planet profile.",
            "Adjust distance from the Sun slider.",
            "Observe speed and period changes in the chart.",
          ],
          data: {
            controls: ["distance", "massProfile"],
            outputs: ["orbitalSpeed", "orbitalPeriod"],
            presets: ["innerOrbit", "earthLikeOrbit", "outerOrbit"],
          },
        },
      ],
      learningAids: [
        { id: "s101-l5-a1", type: "practice", title: "Orbit Control Panel", content: "Adjust distance and watch orbital period updates." },
      ],
    },
    {
      id: "s101-l6",
      title: "Checkpoint Quiz: Outer Planets and Orbits",
      type: "quiz",
      duration: 10,
      questions: [
        {
          id: "s101-l6-q1",
          text: "Which planet is the largest in our solar system?",
          skillId: "planet-comparison",
          options: [
            { id: "a", text: "Jupiter" },
            { id: "b", text: "Saturn" },
            { id: "c", text: "Earth" },
            { id: "d", text: "Mars" },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l6-q2",
          text: "Which planet is famous for its bright ring system?",
          skillId: "planet-identification",
          options: [
            { id: "a", text: "Neptune" },
            { id: "b", text: "Saturn" },
            { id: "c", text: "Venus" },
            { id: "d", text: "Mercury" },
          ],
          correctOptionId: "b",
        },
        {
          id: "s101-l6-q3",
          text: "What mainly keeps planets in orbit around the Sun?",
          skillId: "orbit-concepts",
          options: [
            { id: "a", text: "Magnetism from Earth" },
            { id: "b", text: "The Sun's gravity" },
            { id: "c", text: "Wind in space" },
            { id: "d", text: "Planet engines" },
          ],
          correctOptionId: "b",
        },
        {
          id: "s101-l6-q4",
          text: "A planet farther from the Sun usually has what kind of orbit period?",
          skillId: "orbit-concepts",
          options: [
            { id: "a", text: "Shorter orbit period" },
            { id: "b", text: "Same orbit period as Earth" },
            { id: "c", text: "Longer orbit period" },
            { id: "d", text: "No orbit period" },
          ],
          correctOptionId: "c",
        },
      ],
      interactiveActivities: [
        {
          id: "s101-l6-ia1",
          type: "matching_pairs",
          title: "Outer Planet Reasoning Match",
          description: "Match orbit and planet clues with the best explanation.",
          estimatedMinutes: 7,
          difficultyLevel: "medium",
          data: {
            left: [
              { id: "l1", label: "Largest planet" },
              { id: "l2", label: "Bright ring system" },
              { id: "l3", label: "Farther orbit path" },
            ],
            right: [
              { id: "r1", label: "Jupiter" },
              { id: "r2", label: "Saturn" },
              { id: "r3", label: "Longer orbital period" },
            ],
            pairs: [
              { leftId: "l1", rightId: "r1" },
              { leftId: "l2", rightId: "r2" },
              { leftId: "l3", rightId: "r3" },
            ],
          },
        },
      ],
      quizBlueprint: {
        frequency: "lesson_assessment",
        questionsPerCheck: 4,
        totalQuestions: 4,
        timeLimitMinutes: 10,
        questionTypes: [{ type: "mcq_single", count: 4, pointsEach: 1, bloomsLevels: [1, 2, 3] }],
        difficultyDistribution: { easy: 1, medium: 2, hard: 1 },
        feedbackMode: "after_submit",
        adaptive: false,
        masteryThreshold: 0.75,
      },
    },
    {
      id: "s101-l7",
      title: "Video: Dwarf Planets and Small Bodies",
      type: "video",
      duration: 8,
      learningAids: [
        { id: "s101-l7-a1", type: "image", title: "Asteroid Belt Map", content: "Visual map of asteroids, comets, and dwarf planets." },
      ],
    },
    {
      id: "s101-l8",
      title: "Mastery Quiz: Solar System Tour",
      type: "quiz",
      duration: 12,
      questions: [
        {
          id: "s101-l8-q1",
          text: "Which statement best compares inner and outer planets?",
          skillId: "planet-classification",
          options: [
            { id: "a", text: "Inner planets are mostly rocky; outer planets are mostly gas/ice giants." },
            { id: "b", text: "All planets are rocky." },
            { id: "c", text: "All planets have rings." },
            { id: "d", text: "Outer planets are all smaller than inner planets." },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l8-q2",
          text: "Which planet is closest to the Sun?",
          skillId: "planet-identification",
          options: [
            { id: "a", text: "Venus" },
            { id: "b", text: "Earth" },
            { id: "c", text: "Mercury" },
            { id: "d", text: "Mars" },
          ],
          correctOptionId: "c",
        },
        {
          id: "s101-l8-q3",
          text: "Why do outer planets often take longer to orbit the Sun?",
          skillId: "orbit-concepts",
          options: [
            { id: "a", text: "Their paths are larger, so each orbit is longer." },
            { id: "b", text: "They stop moving in winter." },
            { id: "c", text: "They have no gravity." },
            { id: "d", text: "They spin backward every day." },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l8-q4",
          text: "Which body is classified as a dwarf planet?",
          skillId: "planet-classification",
          options: [
            { id: "a", text: "Pluto" },
            { id: "b", text: "Earth" },
            { id: "c", text: "Jupiter" },
            { id: "d", text: "Mars" },
          ],
          correctOptionId: "a",
        },
        {
          id: "s101-l8-q5",
          text: "What is one key role of the Sun in the solar system?",
          skillId: "sun-concepts",
          options: [
            { id: "a", text: "It provides gravity and energy for the system." },
            { id: "b", text: "It orbits Earth once each day." },
            { id: "c", text: "It is a cold rocky planet." },
            { id: "d", text: "It has no influence on planets." },
          ],
          correctOptionId: "a",
        },
      ],
      interactiveActivities: [
        {
          id: "s101-l8-ia1",
          type: "matching_pairs",
          title: "Solar System Mastery Match",
          description: "Pair big ideas with the most accurate science evidence.",
          estimatedMinutes: 8,
          difficultyLevel: "medium",
          data: {
            left: [
              { id: "l1", label: "Inner vs outer planet pattern" },
              { id: "l2", label: "Closest planet to the Sun" },
              { id: "l3", label: "Main Sun role in the system" },
            ],
            right: [
              { id: "r1", label: "Inner mostly rocky, outer mostly gas/ice giants" },
              { id: "r2", label: "Mercury" },
              { id: "r3", label: "Source of gravity and energy for the system" },
            ],
            pairs: [
              { leftId: "l1", rightId: "r1" },
              { leftId: "l2", rightId: "r2" },
              { leftId: "l3", rightId: "r3" },
            ],
          },
        },
      ],
      quizBlueprint: {
        frequency: "mastery_check",
        questionsPerCheck: 5,
        totalQuestions: 5,
        timeLimitMinutes: 12,
        questionTypes: [{ type: "mcq_single", count: 5, pointsEach: 1, bloomsLevels: [1, 2, 3, 4] }],
        difficultyDistribution: { easy: 1, medium: 3, hard: 1 },
        feedbackMode: "after_submit",
        adaptive: false,
        masteryThreshold: 0.8,
      },
    },
  ],
};
