// ─── Core Games (named exports with types) ───
export { ColorMixer } from "./color-mixer";
export type { ColorMixerProps } from "./color-mixer";

export { LetterCatcher } from "./letter-catcher";
export type { LetterCatcherProps } from "./letter-catcher";

export { MemoryMatch } from "./memory-match";
export type { MemoryMatchProps } from "./memory-match";

export { NumberCrunch } from "./number-crunch";
export type { NumberCrunchProps } from "./number-crunch";

export { PatternTrain } from "./pattern-train";
export type { PatternTrainProps } from "./pattern-train";

export { ShapeSafari } from "./shape-safari";
export type { ShapeSafariProps } from "./shape-safari";

export { StorySequencer } from "./story-sequencer";
export type { StorySequencerProps } from "./story-sequencer";

export { WordBuilder } from "./word-builder";
export type { WordBuilderProps } from "./word-builder";

// ─── EdTech Games ───
export { default as AeroArchitect } from "./aero-architect";
export { default as AlphabetAirship } from "./alphabet-airship";
export { default as ArtisticAlgorithms } from "./artistic-algorithms";
export { default as BioBlast } from "./bio-blast";
export { default as BiomeBuilder } from "./biome-builder";
export { default as BotBuilder } from "./bot-builder";
export { default as ChronicleCase } from "./chronicle-case";
export { default as CipherCity } from "./cipher-city";
export { default as CircuitCrusader } from "./circuit-crusader";
export { default as ClimateCommander } from "./climate-commander";
export { default as CosmicCanvas } from "./cosmic-canvas";
export { default as CountConstellations } from "./count-constellations";
export { default as EchosExpedition } from "./echos-expedition";
export { default as EcoEngineer } from "./eco-engineer";
export { default as EthicalEngine } from "./ethical-engine";
export { default as EthosEngine } from "./ethos-engine";
export { default as EvolutionPrime } from "./evolution-prime";
export { default as FloraFusion } from "./flora-fusion";
export { default as FractionFactory } from "./fraction-factory";
export { default as FractionForge } from "./fraction-forge";
export { default as FusionFounder } from "./fusion-founder";
export { default as GeneticGarden } from "./genetic-garden";
export { default as GlobalHarmony } from "./global-harmony";
export { default as GravityGoliath } from "./gravity-goliath";
export { default as HistoHunt } from "./histo-hunt";
export { default as HistoryHacker } from "./history-hacker";
export { default as LinguistLookout } from "./linguist-lookout";
export { default as LogicLabyrinth } from "./logic-labyrinth";
export { default as LogicalLink } from "./logical-link";
export { default as LunasLegend } from "./lunas-legend";
export { default as MarketMaker } from "./market-maker";
export { default as MarsColony } from "./mars-colony";
export { default as NanoNavigator } from "./nano-navigator";
export { default as NanoNexus } from "./nano-nexus";
export { default as NeuralNavigator } from "./neural-navigator";
export { default as NeuralNet } from "./neural-net";
export { default as OrbitOperator } from "./orbit-operator";
export { default as PixelsPath } from "./pixels-path";
export { default as ProteinPainter } from "./protein-painter";
export { default as QuantumCascade } from "./quantum-cascade";
export { default as QuantumQuest } from "./quantum-quest";
export { default as QuantumQuirk } from "./quantum-quirk";
export { default as RhymeRiver } from "./rhyme-river";
export { default as RhythmRules } from "./rhythm-rules";
export { default as SentenceSafari } from "./sentence-safari";
export { default as SparksSparkQuest } from "./sparks-spark-quest";
export { default as StarSteer } from "./star-steer";
export { default as StellarState } from "./stellar-state";
export { default as StorySmith } from "./story-smith";
export { default as SyntaxSerpent } from "./syntax-serpent";
export { default as SynthesisSphere } from "./synthesis-sphere";
export { default as SyntheticArchitect } from "./synthetic-architect";
export { default as TectonicTrek } from "./tectonic-trek";
export { default as TerrasTrek } from "./terras-trek";
export { default as VelocityVector } from "./velocity-vector";
export { default as VocabularyVoyager } from "./vocabulary-voyager";
export { default as WordWoods } from "./word-woods";

// ─── Templates ───
export { default as ImmersiveArcadeTemplate } from "./immersive-arcade-template";
export { default as QuizAdventureFactory } from "./quiz-adventure-factory";
export { default as QuizAdventureGame } from "./quiz-adventure-game";
export { default as RewardRealmCharacterGauntlet } from "./reward-realm-character-gauntlet";

// ─── Arcade Games (061-070, 121-129) ───
export { default as Arcade061PixelPrismPatrol } from "./arcade-061-pixel-prism-patrol";
export { default as Arcade062SparkFactorFurnace } from "./arcade-062-spark-factor-furnace";
export { default as Arcade063EchoClaimCascade } from "./arcade-063-echo-claim-cascade";
export { default as Arcade064LunaSequenceSymphony } from "./arcade-064-luna-sequence-symphony";
export { default as Arcade065TerraEcosystemRescue } from "./arcade-065-terra-ecosystem-rescue";
export { default as Arcade066SparkThrusterTrial } from "./arcade-066-spark-thruster-trial";
export { default as Arcade067EchoTruthlineProtocol } from "./arcade-067-echo-truthline-protocol";
export { default as Arcade068TerraWildsRecovery } from "./arcade-068-terra-wilds-recovery";
export { default as Arcade069LunaPulseRally } from "./arcade-069-luna-pulse-rally";
export { default as Arcade070PixelFirewallFrontier } from "./arcade-070-pixel-firewall-frontier";
export { default as Arcade121BreezeTrail } from "./arcade-121-breeze-trail";
export { default as Arcade122SproutTrail } from "./arcade-122-sprout-trail";
export { default as Arcade123PebbleTrail } from "./arcade-123-pebble-trail";
export { default as Arcade124NimbusTrail } from "./arcade-124-nimbus-trail";
export { default as Arcade125FlareTrail } from "./arcade-125-flare-trail";
export { default as Arcade126SkyCircuit } from "./arcade-126-sky-circuit";
export { default as Arcade127RiverCircuit } from "./arcade-127-river-circuit";
export { default as Arcade128EchoCircuit } from "./arcade-128-echo-circuit";
export { default as Arcade129LunaCircuit } from "./arcade-129-luna-circuit";

// ─── Classic Games (game-*) ───
export { default as Game2048 } from "./game-2048";
export { default as GameAnagram } from "./game-anagram";
export { default as GameAsteroids } from "./game-asteroids";
export { default as GameBinaryPuzzle } from "./game-binary-puzzle";
export { default as GameBomberman } from "./game-bomberman";
export { default as GameBreakout } from "./game-breakout";
export { default as GameBubbleShooter } from "./game-bubble-shooter";
export { default as GameCheckers } from "./game-checkers";
export { default as GameChess } from "./game-chess";
export { default as GameColorFlood } from "./game-color-flood";
export { default as GameConnectFour } from "./game-connect-four";
export { default as GameConnections } from "./game-connections";
export { default as GameCookieClicker } from "./game-cookie-clicker";
export { default as GameCrossword } from "./game-crossword";
export { default as GameDotConnect } from "./game-dot-connect";
export { default as GameDuckHunt } from "./game-duck-hunt";
export { default as GameFactors } from "./game-factors";
export { default as GameFlappy } from "./game-flappy";
export { default as GameFrogger } from "./game-frogger";
export { default as GameHangman } from "./game-hangman";
export { default as GameLogicGrid } from "./game-logic-grid";
export { default as GameMahjong } from "./game-mahjong";
export { default as GameMake24 } from "./game-make-24";
export { default as GameMathSprint } from "./game-math-sprint";
export { default as GameMathTrainer } from "./game-math-trainer";
export { default as GameMemoryMatch } from "./game-memory-match";
export { default as GameMinesweeper } from "./game-minesweeper";
export { default as GameMissileCommand } from "./game-missile-command";
export { default as GameNumberDots } from "./game-number-dots";
export { default as GameNummMatch } from "./game-numm-match";
export { default as GamePong } from "./game-pong";
export { default as GameReactionTime } from "./game-reaction-time";
export { default as GameReversi } from "./game-reversi";
export { default as GameSimon } from "./game-simon";
export { default as GameSlidingPuzzle } from "./game-sliding-puzzle";
export { default as GameSnake } from "./game-snake";
export { default as GameSokoban } from "./game-sokoban";
export { default as GameSolitaire } from "./game-solitaire";
export { default as GameSpaceInvaders } from "./game-space-invaders";
export { default as GameSpiderSolitaire } from "./game-spider-solitaire";
export { default as GameSudoku } from "./game-sudoku";
export { default as GameTetris } from "./game-tetris";
export { default as GameTicTacToe } from "./game-tic-tac-toe";
export { default as GameTowerStack } from "./game-tower-stack";
export { default as GameTriviaQuiz } from "./game-trivia-quiz";
export { default as GameTypingSpeed } from "./game-typing-speed";
export { default as GameWhackAMole } from "./game-whack-a-mole";
export { default as GameWordPluck } from "./game-word-pluck";
export { default as GameWordRescue } from "./game-word-rescue";
export { default as GameWordScramble } from "./game-word-scramble";
export { default as GameWordle } from "./game-wordle";

// ─── Zone Games ───
export { default as Zone041SignalRescue } from "./zone-041-signal-rescue";
export { default as Zone042MathRailCommander } from "./zone-042-math-rail-commander";
export { default as Zone043EchoStorySignal } from "./zone-043-echo-story-signal";
export { default as Zone044TerraLabSort } from "./zone-044-terra-lab-sort";
export { default as Zone045LunaRhythmForge } from "./zone-045-luna-rhythm-forge";
export { default as Zone046PixelCipherSprint } from "./zone-046-pixel-cipher-sprint";
export { default as Zone047SparkGridFuse } from "./zone-047-spark-grid-fuse";
export { default as Zone048EchoEvidenceJudge } from "./zone-048-echo-evidence-judge";
export { default as Zone049TerraHabitatTriage } from "./zone-049-terra-habitat-triage";
export { default as Zone050PixelLaneDefender } from "./zone-050-pixel-lane-defender";
export { default as Zone051LunaChorusCascade } from "./zone-051-luna-chorus-cascade";
export { default as Zone052SparkReactorGrid } from "./zone-052-spark-reactor-grid";
export { default as Zone053EchoDebateDuel } from "./zone-053-echo-debate-duel";
export { default as Zone054TerraWeatherCommand } from "./zone-054-terra-weather-command";
export { default as Zone055PixelDroneIntercept } from "./zone-055-pixel-drone-intercept";
export { default as Zone056SparkOrbitalSurge } from "./zone-056-spark-orbital-surge";
export { default as Zone057EchoSignalCrossfire } from "./zone-057-echo-signal-crossfire";
export { default as Zone058TerraRiftShelter } from "./zone-058-terra-rift-shelter";
export { default as Zone059LunaStageStrategy } from "./zone-059-luna-stage-strategy";
export { default as Zone060PixelCircuitSiege } from "./zone-060-pixel-circuit-siege";
export { default as Zone061SparkFluxGauntlet } from "./zone-061-spark-flux-gauntlet";
export { default as Zone062EchoProofRelay } from "./zone-062-echo-proof-relay";
export { default as Zone063TerraGreenhouseCommand } from "./zone-063-terra-greenhouse-command";
export { default as Zone064LunaBeatlineRun } from "./zone-064-luna-beatline-run";
export { default as Zone065PixelBreachHunter } from "./zone-065-pixel-breach-hunter";
export { default as Zone066SparkThrusterTrial } from "./zone-066-spark-thruster-trial";
export { default as Zone067EchoTruthlineProtocol } from "./zone-067-echo-truthline-protocol";
export { default as Zone068TerraWildsRecovery } from "./zone-068-terra-wilds-recovery";
export { default as Zone069LunaPulseRally } from "./zone-069-luna-pulse-rally";
export { default as Zone070PixelFirewallFrontier } from "./zone-070-pixel-firewall-frontier";
export { default as Zone071SparkReactorConvoy } from "./zone-071-spark-reactor-convoy";
export { default as Zone072EchoSignalTribunal } from "./zone-072-echo-signal-tribunal";
export { default as Zone073TerraFrontlineWardens } from "./zone-073-terra-frontline-wardens";
export { default as Zone074LunaSkylineSet } from "./zone-074-luna-skyline-set";
export { default as Zone075PixelSentinelLattice } from "./zone-075-pixel-sentinel-lattice";
export { default as Zone076SparkVaultThrust } from "./zone-076-spark-vault-thrust";
export { default as Zone077PixelBlockDrop } from "./zone-077-pixel-block-drop";
export { default as Zone078SparkBreakoutSurge } from "./zone-078-spark-breakout-surge";
export { default as Zone079LunaZigzagRun } from "./zone-079-luna-zigzag-run";
export { default as Zone080EchoWordRescue } from "./zone-080-echo-word-rescue";
export { default as Zone081TerraMinefieldMap } from "./zone-081-terra-minefield-map";
export { default as Zone082PixelShaftDrop } from "./zone-082-pixel-shaft-drop";
export { default as Zone083LunaSequenceFlash } from "./zone-083-luna-sequence-flash";
export { default as Zone084EchoAnagramBlast } from "./zone-084-echo-anagram-blast";
export { default as Zone085SparkIdleForge } from "./zone-085-spark-idle-forge";
export { default as Zone086TerraTilePair } from "./zone-086-terra-tile-pair";
export { default as Zone087PixelMerge2048 } from "./zone-087-pixel-merge-2048";
export { default as Zone088SparkFlapSurge } from "./zone-088-spark-flap-surge";
export { default as Zone089LunaSudokuGrid } from "./zone-089-luna-sudoku-grid";
export { default as Zone090EchoConnectDrop } from "./zone-090-echo-connect-drop";
export { default as Zone091TerraWhackSquad } from "./zone-091-terra-whack-squad";
export { default as Zone092PixelCardMatch } from "./zone-092-pixel-card-match";
export { default as Zone093SparkSnakeTrail } from "./zone-093-spark-snake-trail";
export { default as Zone094LunaWordGrid } from "./zone-094-luna-word-grid";
export { default as Zone095EchoBubbleBurst } from "./zone-095-echo-bubble-burst";
export { default as Zone096TerraCrossword } from "./zone-096-terra-crossword";
export { default as Zone097PixelTypeRush } from "./zone-097-pixel-type-rush";
export { default as Zone098SparkDiceRoll } from "./zone-098-spark-dice-roll";
export { default as Zone099LunaEndlessRun } from "./zone-099-luna-endless-run";
export { default as Zone101VoxelCraftWorld } from "./zone-101-voxel-craft-world";
export { default as Zone102NeonHeistCity } from "./zone-102-neon-heist-city";
export { default as Zone103StormRoyaleArena } from "./zone-103-storm-royale-arena";
export { default as Zone104SoulDungeonAscent } from "./zone-104-soul-dungeon-ascent";
export { default as Zone105HexQuestSaga } from "./zone-105-hex-quest-saga";
export { default as Zone106FrontierTrailRider } from "./zone-106-frontier-trail-rider";
export { default as Zone107DiceDestinyRpg } from "./zone-107-dice-destiny-rpg";
export { default as Zone108ElderRealmQuest } from "./zone-108-elder-realm-quest";
export { default as Zone109GuildRaidLegends } from "./zone-109-guild-raid-legends";
export { default as Zone110TacticalOpsStrike } from "./zone-110-tactical-ops-strike";
export { default as Zone111DropZoneSurvivor } from "./zone-111-drop-zone-survivor";
export { default as Zone112HarvestBloomFarm } from "./zone-112-harvest-bloom-farm";
export { default as Zone113RuinSurvivorTrek } from "./zone-113-ruin-survivor-trek";
export { default as Zone114InfernoRunAscent } from "./zone-114-inferno-run-ascent";
export { default as Zone115MindPalaceRpg } from "./zone-115-mind-palace-rpg";
export { default as Zone116AbyssalKnightDeep } from "./zone-116-abyssal-knight-deep";
export { default as Zone117ImpostorStation } from "./zone-117-impostor-station";
export { default as Zone118TurboBallArena } from "./zone-118-turbo-ball-arena";
export { default as Zone119PrimalTamerIsle } from "./zone-119-primal-tamer-isle";
export { default as Zone120TerraDigWorld } from "./zone-120-terra-dig-world";
export { default as Zone121SparkHelixLock } from "./zone-121-spark-helix-lock";
export { default as Zone122EchoJudgmentCircuit } from "./zone-122-echo-judgment-circuit";
export { default as Zone123TerraColonyEvac } from "./zone-123-terra-colony-evac";
export { default as Zone124LunaNovaCadence } from "./zone-124-luna-nova-cadence";
export { default as Zone125PixelContainmentMatrix } from "./zone-125-pixel-containment-matrix";
