import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import AlertsClient from "./alerts-client";

export const dynamic = "force-dynamic";

function coerceNumber(value: unknown) {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
}

function readNumericSetting(value: unknown, fallback: number) {
  const direct = coerceNumber(value);
  if (direct !== null) return direct;
  if (value && typeof value === "object" && "value" in value) {
    const nested = coerceNumber((value as { value?: unknown }).value);
    if (nested !== null) return nested;
  }
  return fallback;
}

export default async function AdminAlertsPage() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    redirect("/auth/sign-in");
  }

  const { data: profile, error: profileError } = await supabase
    .from("user_profiles")
    .select("is_admin")
    .eq("user_id", user.id)
    .maybeSingle();

  if (profileError || !profile?.is_admin) {
    return (
      <main className="mx-auto flex w-full max-w-4xl flex-col items-center justify-center gap-4 px-6 py-24">
        <h1 className="text-2xl font-semibold">Access Denied</h1>
        <p className="text-sm text-red-600">You must be an administrator to access alerts.</p>
      </main>
    );
  }

  const admin = createSupabaseAdminClient();
  const [alertsResult, settingsResult, queuedSummaryResult, failedSummaryResult, sentSummaryResult] = await Promise.all([
    admin
      .from("admin_alerts")
      .select("id, severity, category, message, metadata, acknowledged, acknowledged_at, created_at")
      .order("created_at", { ascending: false })
      .limit(200),
    admin
      .from("app_settings")
      .select("key, value")
      .in("key", [
        "media_queue_sla_stale_hours",
        "media_queue_sla_backlog_limit",
        "media_queue_sla_failure_24h_limit",
        "media_queue_alert_dedupe_hours",
        "media_queue_alert_auto_resolve_hours",
      ]),
    admin
      .from("admin_alert_notifications")
      .select("id", { count: "exact", head: true })
      .eq("status", "queued"),
    admin
      .from("admin_alert_notifications")
      .select("id", { count: "exact", head: true })
      .eq("status", "failed"),
    admin
      .from("admin_alert_notifications")
      .select("id", { count: "exact", head: true })
      .eq("status", "sent"),
  ]);

  const settingsMap = new Map((settingsResult.data ?? []).map((row) => [row.key, row.value]));
  const initialSettings = {
    staleHours: readNumericSetting(settingsMap.get("media_queue_sla_stale_hours"), 6),
    backlogLimit: readNumericSetting(settingsMap.get("media_queue_sla_backlog_limit"), 30),
    failure24hLimit: readNumericSetting(settingsMap.get("media_queue_sla_failure_24h_limit"), 20),
    dedupeWindowHours: readNumericSetting(settingsMap.get("media_queue_alert_dedupe_hours"), 24),
    autoResolveHours: readNumericSetting(settingsMap.get("media_queue_alert_auto_resolve_hours"), 12),
  };
  const initialNotificationSummary = {
    queuedCount: queuedSummaryResult.count ?? 0,
    failedCount: failedSummaryResult.count ?? 0,
    sentCount: sentSummaryResult.count ?? 0,
  };

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-col gap-6 px-6 py-12">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">Admin Alerts</h1>
        <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-300">
          Rate-limit and operational anomaly alerts generated by control systems.
        </p>
      </header>

      <AlertsClient
        initialAlerts={alertsResult.data ?? []}
        initialSettings={initialSettings}
        initialNotificationSummary={initialNotificationSummary}
      />
    </main>
  );
}
