import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import AlertsClient from "./alerts-client";

export const dynamic = "force-dynamic";

export default async function AdminAlertsPage() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    redirect("/auth/sign-in");
  }

  const { data: profile, error: profileError } = await supabase
    .from("user_profiles")
    .select("is_admin")
    .eq("user_id", user.id)
    .maybeSingle();

  if (profileError || !profile?.is_admin) {
    return (
      <main className="mx-auto flex w-full max-w-4xl flex-col items-center justify-center gap-4 px-6 py-24">
        <h1 className="text-2xl font-semibold">Access Denied</h1>
        <p className="text-sm text-red-600">You must be an administrator to access alerts.</p>
      </main>
    );
  }

  const admin = createSupabaseAdminClient();
  const { data: alerts } = await admin
    .from("admin_alerts")
    .select("id, severity, category, message, metadata, acknowledged, acknowledged_at, created_at")
    .order("created_at", { ascending: false })
    .limit(200);

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-col gap-6 px-6 py-12">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">Admin Alerts</h1>
        <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-300">
          Rate-limit and operational anomaly alerts generated by control systems.
        </p>
      </header>

      <AlertsClient initialAlerts={alerts ?? []} />
    </main>
  );
}
