/**
 * StoryForge Cinema — Scene Decomposition Service
 * 
 * Transforms raw book text into a structured array of CinematicScene objects.
 * In production, this would call an LLM API. For now, we use a deterministic
 * heuristic to demonstrate the pipeline architecture.
 */

import type { CinematicScene, InteractiveHotspot } from "./types";

const MOOD_KEYWORDS: Record<CinematicScene["mood"], string[]> = {
  calm: ["gentle", "quiet", "peaceful", "soft", "rested", "still"],
  tense: ["danger", "fear", "dark", "storm", "threat", "chase", "fight"],
  joyful: ["laugh", "happy", "joy", "dance", "celebrate", "bright", "smile"],
  melancholy: ["sad", "tear", "lost", "alone", "gray", "miss", "gone"],
  adventurous: ["journey", "discover", "explore", "quest", "brave", "ship", "fly"],
  mysterious: ["secret", "hidden", "shadow", "whisper", "strange", "unknown"],
};

/**
 * Infers a mood from paragraph text using keyword frequency analysis.
 */
function inferMood(text: string): CinematicScene["mood"] {
  const lower = text.toLowerCase();
  let bestMood: CinematicScene["mood"] = "calm";
  let bestScore = 0;

  for (const [mood, keywords] of Object.entries(MOOD_KEYWORDS) as [CinematicScene["mood"], string[]][]) {
    const score = keywords.reduce((sum, kw) => {
      const regex = new RegExp(kw, "gi");
      return sum + (lower.match(regex) || []).length;
    }, 0);

    if (score > bestScore) {
      bestScore = score;
      bestMood = mood;
    }
  }

  return bestMood;
}

/**
 * Extracts character names from text using a simple heuristic:
 * capitalized words that appear frequently and aren't common English words.
 */
function extractCharacters(text: string): string[] {
  const COMMON_WORDS = new Set([
    "The", "And", "But", "For", "Not", "You", "All", "Can", "Had", "Her",
    "Was", "One", "Our", "Out", "Are", "Has", "His", "How", "Its", "May",
    "New", "Now", "Old", "See", "Way", "Who", "Did", "Get", "Let", "Say",
    "She", "Too", "Use", "Then", "Than", "They", "This", "That", "With",
    "Have", "From", "Been", "Some", "When", "What", "There", "Which",
    "Their", "Will", "Each", "Make", "Like", "Long", "Very", "After",
    "Chapter", "Project", "Gutenberg",
  ]);

  const words = text.match(/\b[A-Z][a-z]{2,}\b/g) || [];
  const freq: Record<string, number> = {};

  for (const word of words) {
    if (!COMMON_WORDS.has(word)) {
      freq[word] = (freq[word] || 0) + 1;
    }
  }

  return Object.entries(freq)
    .filter(([, count]) => count >= 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([name]) => name);
}

/**
 * Extracts dialogue lines from the text.
 */
function extractDialogue(text: string): string[] {
  const dialogueRegex = /"([^"]+)"/g;
  const matches: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = dialogueRegex.exec(text)) !== null) {
    if (match[1].length > 10 && match[1].length < 300) {
      matches.push(match[1]);
    }
  }

  return matches.slice(0, 5);
}

/**
 * Generates interactive hotspots for a scene.
 */
function generateHotspots(text: string, sceneIndex: number): InteractiveHotspot[] {
  const hotspots: InteractiveHotspot[] = [];

  // Vocabulary hotspot: find an uncommon word
  const uncommonWords = text.match(/\b[a-z]{8,}\b/g) || [];
  if (uncommonWords.length > 0) {
    const word = uncommonWords[Math.floor(uncommonWords.length / 2)];
    hotspots.push({
      id: `vocab-${sceneIndex}-${word}`,
      type: "vocabulary",
      label: word,
      positionPercent: { x: 20, y: 70 },
      content: {
        kind: "vocabulary",
        word,
        definition: `A word meaning something related to the narrative context. (Full definition generated by LLM in production.)`,
      },
    });
  }

  // Explore hotspot for every scene
  const firstSentence = text.split(/[.!?]/)[0]?.trim() || "A scene unfolds.";
  hotspots.push({
    id: `explore-${sceneIndex}`,
    type: "explore",
    label: "Explore Scene",
    positionPercent: { x: 80, y: 30 },
    content: {
      kind: "explore",
      description: firstSentence.slice(0, 200),
    },
  });

  return hotspots;
}

/**
 * Decomposes a chapter/section of text into a CinematicScene.
 */
function decomposeChapterToScene(
  chapterText: string,
  sceneIndex: number,
  totalChapters: number
): CinematicScene {
  const mood = inferMood(chapterText);
  const characters = extractCharacters(chapterText);
  const dialogue = extractDialogue(chapterText);
  const hotspots = generateHotspots(chapterText, sceneIndex);

  // Extract first meaningful paragraph as setting description
  const paragraphs = chapterText.split(/\n\s*\n/).filter((p) => p.trim().length > 30);
  const setting = paragraphs[0]?.trim().slice(0, 300) || "An uncharted landscape reveals itself.";

  // Generate narration from the opening
  const narration = paragraphs.slice(0, 2).join(" ").slice(0, 500);

  // Camera direction based on mood
  const cameraDirections: Record<CinematicScene["mood"], string> = {
    calm: "Slow dolly forward, soft focus on the central subject, warm golden-hour lighting.",
    tense: "Handheld tracking shot with shallow depth of field, quick cuts between subjects.",
    joyful: "Sweeping crane shot upward, vibrant saturated colors, lens flare from sunlight.",
    melancholy: "Static wide shot with slow zoom, desaturated blues and grays, gentle rain particles.",
    adventurous: "Epic aerial establishing shot, dynamic camera following the protagonist through the landscape.",
    mysterious: "Low-angle push-in through fog, chiaroscuro lighting, selective focus reveals.",
  };

  // Duration is proportional to text length
  const wordCount = chapterText.split(/\s+/).length;
  const durationSeconds = Math.max(30, Math.min(300, Math.round(wordCount / 5)));

  return {
    sceneIndex,
    title: `Scene ${sceneIndex + 1} of ${totalChapters}`,
    setting,
    characters,
    dialogue,
    narration,
    cameraDirection: cameraDirections[mood],
    mood,
    durationSeconds,
    interactiveHotspots: hotspots,
  };
}

/**
 * Main pipeline entry: decomposes an array of chapter texts into CinematicScenes.
 */
export function decomposeTextToScenes(chapters: string[]): CinematicScene[] {
  return chapters.map((chapter, index) =>
    decomposeChapterToScene(chapter, index, chapters.length)
  );
}
