/**
 * Canonical micro-app target configuration shared by build/deploy scripts.
 */

export const MICROAPP_TARGETS = [
  {
    appId: "koydo_main",
    displayName: "Koydo",
    variant: "full",
    enabledSubjects: ["*"],
    minAge: 0,
    maxAge: 99,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "koydo.app",
  },
  {
    appId: "koydo_junior",
    displayName: "Koydo Junior",
    variant: "kids",
    enabledSubjects: ["Math", "Reading", "Science"],
    minAge: 3,
    maxAge: 8,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "junior.koydo.app",
  },
  {
    appId: "koydo_sat",
    displayName: "Koydo SAT Prep",
    variant: "teen",
    enabledSubjects: ["Math", "Reading", "Science", "Languages"],
    minAge: 14,
    maxAge: 19,
    defaultLocale: "en",
    region: "us",
    defaultCurrency: "USD",
    pricingTier: "premium_19.99",
    suggestedDomain: "sat.koydo.app",
  },
  {
    appId: "koydo_finance",
    displayName: "Koydo Finance Pro",
    variant: "adult",
    enabledSubjects: ["Finance", "Accounting"],
    minAge: 16,
    maxAge: 99,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "premium_19.99",
    suggestedDomain: "finance.koydo.app",
  },
  {
    appId: "koydo_university",
    displayName: "Koydo University",
    variant: "adult",
    enabledSubjects: ["Exam Prep", "Finance", "Accounting", "Coding"],
    minAge: 18,
    maxAge: 99,
    defaultLocale: "en",
    region: "us",
    defaultCurrency: "USD",
    pricingTier: "premium_19.99",
    suggestedDomain: "university.koydo.app",
  },
  {
    appId: "koydo_math",
    displayName: "Koydo Math Forge",
    variant: "teen",
    enabledSubjects: ["Math"],
    minAge: 8,
    maxAge: 18,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "math.koydo.app",
  },
  {
    appId: "koydo_arena",
    displayName: "Koydo Arena",
    variant: "full",
    enabledSubjects: ["*"],
    minAge: 5,
    maxAge: 99,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "free",
    suggestedDomain: "arena.koydo.app",
  },
  {
    appId: "koydo_trades",
    displayName: "Koydo Trades",
    variant: "adult",
    enabledSubjects: ["Electrical", "Plumbing", "HVAC", "Civil Engineering", "Farming", "CDL"],
    minAge: 16,
    maxAge: 99,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "trades.koydo.app",
  },
  {
    appId: "koydo_cdl",
    displayName: "Koydo CDL Prep",
    variant: "adult",
    enabledSubjects: ["CDL"],
    minAge: 18,
    maxAge: 99,
    defaultLocale: "en",
    region: "us",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "cdl.koydo.app",
  },
  {
    appId: "koydo_stem",
    displayName: "Koydo STEM Lab",
    variant: "teen",
    enabledSubjects: ["Coding", "Data Science", "AI", "Cybersecurity", "Cloud Computing", "Robotics"],
    minAge: 10,
    maxAge: 25,
    defaultLocale: "en",
    region: "global",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "stem.koydo.app",
  },
  {
    appId: "koydo_math_es",
    displayName: "Koydo Matemáticas",
    variant: "teen",
    enabledSubjects: ["Math"],
    minAge: 8,
    maxAge: 18,
    defaultLocale: "es",
    region: "latam",
    defaultCurrency: "USD",
    pricingTier: "freemium",
    suggestedDomain: "math-es.koydo.app",
  },
  {
    appId: "koydo_exam_jp",
    displayName: "Koydo 受験対策",
    variant: "teen",
    enabledSubjects: ["Math", "Science", "Reading"],
    minAge: 15,
    maxAge: 19,
    defaultLocale: "ja",
    region: "jp",
    defaultCurrency: "JPY",
    pricingTier: "premium_19.99",
    suggestedDomain: "exam-jp.koydo.app",
  },
  {
    appId: "koydo_junior_de",
    displayName: "Koydo Junior DE",
    variant: "kids",
    enabledSubjects: ["Math", "Reading", "Science"],
    minAge: 3,
    maxAge: 8,
    defaultLocale: "de",
    region: "dach",
    defaultCurrency: "EUR",
    pricingTier: "freemium",
    suggestedDomain: "junior-de.koydo.app",
  },
  {
    appId: "koydo_ar",
    displayName: "كويدو",
    variant: "full",
    enabledSubjects: ["*"],
    minAge: 0,
    maxAge: 99,
    defaultLocale: "ar",
    region: "mena",
    defaultCurrency: "AED",
    pricingTier: "freemium",
    suggestedDomain: "ar.koydo.app",
  },
  {
    appId: "koydo_kr",
    displayName: "코이도 학습",
    variant: "teen",
    enabledSubjects: ["Math", "Science", "Coding"],
    minAge: 8,
    maxAge: 18,
    defaultLocale: "ko",
    region: "kr",
    defaultCurrency: "KRW",
    pricingTier: "freemium",
    suggestedDomain: "kr.koydo.app",
  },
  {
    appId: "koydo_hi",
    displayName: "Koydo हिंदी",
    variant: "full",
    enabledSubjects: ["*"],
    minAge: 0,
    maxAge: 99,
    defaultLocale: "hi",
    region: "in",
    defaultCurrency: "INR",
    pricingTier: "freemium",
    suggestedDomain: "hi.koydo.app",
  },
  {
    appId: "koydo_math_zh",
    displayName: "Koydo 数学",
    variant: "teen",
    enabledSubjects: ["Math"],
    minAge: 8,
    maxAge: 18,
    defaultLocale: "zh",
    region: "cn",
    defaultCurrency: "CNY",
    pricingTier: "freemium",
    suggestedDomain: "math-zh.koydo.app",
  },
];

export const MICROAPP_TARGETS_BY_ID = Object.fromEntries(
  MICROAPP_TARGETS.map((target) => [target.appId, target]),
);

export function toEnvSuffix(appId) {
  return appId.toUpperCase().replace(/[^A-Z0-9]/g, "_");
}

export function getProjectIdEnvKey(appId) {
  return `VERCEL_PROJECT_ID_${toEnvSuffix(appId)}`;
}

export function getDomainEnvKey(appId) {
  return `MICROAPP_DOMAIN_${toEnvSuffix(appId)}`;
}
