import type { GameType } from "./types";
import { ASSETS } from "@/lib/config/assets";

export type GameCategory =
  | "literacy"
  | "math"
  | "logic"
  | "creative"
  | "science"
  | "adventure"
  | "arcade";

export type GameEngine = "Unreal Engine 5.5+" | "Unity 6+" | "Godot 4.3+";
export type GameAgeGroup =
  | "Kindergarten (4-6)"
  | "Elementary (7-11)"
  | "Middle School (12-14)"
  | "High School (15-18)"
  | "College (19+)";
export type GameTrack = "Educational Core" | "Reward Realm";

export type RegisteredGame = {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  ageMin: number;
  ageMax: number;
  ageGroup: GameAgeGroup;
  engine: GameEngine;
  track: GameTrack;
  category: GameCategory;
  mode: "core" | "arcade" | "legacy";
  safeForChildren: boolean;
  ageLockRecommended: boolean;
  educationalWeight: number;
  graphicsTier: "4k-ready";
  mechanic:
    | "core"
    | "precision-choice"
    | "sequence-recall"
    | "lane-sort"
    | "timed-equation"
    | "pattern-scan"
    | "signal-balance";
  backdropImage: string;
  backdropVideo?: string | null;
};

/* ─── Helper to build a game entry with defaults ─── */
function g(
  id: string,
  title: string,
  description: string,
  overrides: Partial<RegisteredGame> = {},
): RegisteredGame {
  return {
    id,
    title,
    description,
    icon: "🎮",
    color: "from-indigo-500 to-cyan-500",
    ageMin: 7,
    ageMax: 11,
    ageGroup: "Elementary (7-11)",
    engine: "Unity 6+",
    track: "Educational Core",
    category: "arcade",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 75,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
    ...overrides,
  };
}

/* ═══════════════════════════════════════════════════
   CORE GAMES — 11 original educational games
   ═══════════════════════════════════════════════════ */
export const CORE_GAMES: RegisteredGame[] = [
  {
    id: "letter-catcher",
    title: "Letter Catcher",
    description: "Letters In Motion",
    icon: "🔤",
    color: "from-sky-400 to-blue-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "literacy",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 95,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
  {
    id: "word-builder",
    title: "Word Builder",
    description: "Build New Words",
    icon: "📝",
    color: "from-emerald-400 to-teal-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "literacy",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 95,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
  {
    id: "number-crunch",
    title: "Number Crunch",
    description: "Math Speed Sprint",
    icon: "🧮",
    color: "from-amber-400 to-orange-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "math",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 95,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.bgBottom,
    backdropVideo: null,
  },
  {
    id: "pattern-train",
    title: "Pattern Train",
    description: "Pattern Logic Ride",
    icon: "🚂",
    color: "from-violet-400 to-purple-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "logic",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 90,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.bgAuth,
    backdropVideo: null,
  },
  {
    id: "garden-patch-planner",
    title: "Garden Patch Planner",
    description: "Garden Logic Bloom",
    icon: "🌱",
    color: "from-emerald-400 to-lime-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "science",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 93,
    graphicsTier: "4k-ready",
    mechanic: "pattern-scan",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
  {
    id: "bug-trail-balancer",
    title: "Bug Trail Balancer",
    description: "Bug Bridge Sums",
    icon: "🐞",
    color: "from-lime-400 to-emerald-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "math",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 94,
    graphicsTier: "4k-ready",
    mechanic: "signal-balance",
    backdropImage: ASSETS.bgBottom,
    backdropVideo: null,
  },
  {
    id: "cloud-crew-forecast",
    title: "Cloud Crew Forecast",
    description: "Forecast Pack Quest",
    icon: "☁️",
    color: "from-sky-400 to-cyan-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "science",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 92,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.heroSignIn,
    backdropVideo: null,
  },
  {
    id: "story-sequencer",
    title: "Story Sequencer",
    description: "Story Order Quest",
    icon: "📖",
    color: "from-rose-400 to-pink-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "literacy",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 90,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.heroSignIn,
    backdropVideo: null,
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description: "Memory Match Cards",
    icon: "🃏",
    color: "from-cyan-400 to-sky-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "logic",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 85,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.bgBottom,
    backdropVideo: null,
  },
  {
    id: "color-mixer",
    title: "Color Mixer",
    description: "Mix Bright Colors",
    icon: "🎨",
    color: "from-fuchsia-400 to-pink-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "creative",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 80,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.bgAuth,
    backdropVideo: null,
  },
  {
    id: "shape-safari",
    title: "Shape Safari",
    description: "Shape Hunt Safari",
    icon: "🔷",
    color: "from-lime-400 to-green-500",
    ageMin: 4,
    ageMax: 6,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "math",
    mode: "core",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 85,
    graphicsTier: "4k-ready",
    mechanic: "core",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
];

/* ═══════════════════════════════════════════════════
   LEGACY GAMES — 56 Gemini-era games with real .tsx
   ═══════════════════════════════════════════════════ */
export const LEGACY_GAMES: RegisteredGame[] = [
  g("neural", "Neural Navigator", "Play Learn Grow", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "science" }),
  g("fraction", "Fraction Forge", "Think Move Learn", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "math" }),
  g("vocabulary", "Vocabulary Voyager", "Solve Share Smile", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "literacy" }),
  g("artistic", "Artistic Algorithms", "Build Explore Learn", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "creative" }),
  g("ethical", "Ethical Engine", "Focus Practice Win", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "logic" }),
  g("synthesis", "Synthesis Sphere", "Team Up Learn", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "science" }),
  g("velocity", "Velocity Vector", "Discover Create Grow", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "math" }),
  g("logic", "Logical Link", "Play Learn Grow", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "logic" }),
  g("canvas", "Cosmic Canvas", "Think Move Learn", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "creative" }),
  g("chronicle", "Chronicle Case", "Solve Share Smile", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "adventure" }),
  g("syntax", "Syntax Serpent", "Build Explore Learn", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "literacy" }),
  g("genetic", "Genetic Garden", "Focus Practice Win", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science" }),
  g("quantum", "Quantum Quest", "Team Up Learn", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science" }),
  g("market", "Market Maker", "Discover Create Grow", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "math" }),
  g("orbit", "Orbit Operator", "Play Learn Grow", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science" }),
  g("cipher", "Cipher City", "Think Move Learn", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "logic" }),
  g("biome", "Biome Builder", "Solve Share Smile", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science" }),
  g("rhythm", "Rhythm Rules", "Build Explore Learn", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "creative" }),
  g("tectonic", "Tectonic Trek", "Focus Practice Win", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "science" }),
  g("flora", "Flora Fusion", "Team Up Learn", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science" }),
  g("bot", "Bot Builder", "Discover Create Grow", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "logic" }),
  g("eco", "Eco Engineer", "Play Learn Grow", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science" }),
  g("aero", "Aero Architect", "Think Move Learn", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science" }),
  g("histo", "Histo Hunt", "Solve Share Smile", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "adventure" }),
  g("nano", "Nano Navigator", "Build Explore Learn", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science" }),
  g("quantum-quirk", "Quantum Quirk", "Focus Practice Win", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "science", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("star-steer", "Star Steer", "Team Up Learn", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("logic-labyrinth", "Logic Labyrinth", "Discover Create Grow", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "logic", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("bio-blast", "Bio Blast", "Play Learn Grow", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "science", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("ethos-engine", "Ethos Engine", "Think Move Learn", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "logic", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("echo-expedition", "Echo's Expedition", "Solve Share Smile", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "adventure", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("terra-trek", "Terra's Trek", "Build Explore Learn", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("spark-quest", "Spark's Spark-Quest", "Focus Practice Win", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("pixel-path", "Pixel's Path", "Team Up Learn", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "logic", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("luna-legend", "Luna's Legend", "Discover Create Grow", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "adventure", ageMin: 12, ageMax: 14, ageGroup: "Middle School (12-14)" }),
  g("circuit-crusader", "Circuit Crusader", "Play Learn Grow", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "logic", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("gravity-goliath", "Gravity Goliath", "Think Move Learn", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("protein-painter", "Protein Painter", "Solve Share Smile", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("linguist-lookout", "Linguist Lookout", "Build Explore Learn", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "literacy", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("fusion-founder", "Fusion Founder", "Focus Practice Win", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("stellar-state", "Stellar State", "Team Up Learn", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("neural-net", "Neural Net", "Discover Create Grow", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("climate-commander", "Climate Commander", "Play Learn Grow", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("history-hacker", "History Hacker", "Think Move Learn", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "adventure", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("nano-nexus", "Nano Nexus", "Solve Share Smile", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science", ageMin: 15, ageMax: 18, ageGroup: "High School (15-18)", ageLockRecommended: true }),
  g("mars-colony", "Mars Colony", "Build Explore Learn", { icon: "🧠", color: "from-emerald-500 to-lime-500", category: "science", ageMin: 19, ageMax: 22, ageGroup: "College (19+)", ageLockRecommended: true }),
  g("quantum-cascade", "Quantum Cascade", "Focus Practice Win", { icon: "🌌", color: "from-orange-500 to-rose-500", category: "science", ageMin: 19, ageMax: 22, ageGroup: "College (19+)", ageLockRecommended: true }),
  g("synthetic-architect", "Synthetic Architect", "Team Up Learn", { icon: "🛸", color: "from-fuchsia-500 to-violet-500", category: "science", ageMin: 19, ageMax: 22, ageGroup: "College (19+)", ageLockRecommended: true }),
  g("global-harmony", "Global Harmony", "Discover Create Grow", { icon: "⚡", color: "from-sky-500 to-blue-600", category: "adventure", ageMin: 19, ageMax: 22, ageGroup: "College (19+)", ageLockRecommended: true }),
  g("evolution-prime", "Evolution Prime", "Play Learn Grow", { icon: "🎮", color: "from-indigo-500 to-cyan-500", category: "science", ageMin: 19, ageMax: 22, ageGroup: "College (19+)", ageLockRecommended: true }),
  g("word-woods", "Word Woods", "Think Move Learn", { icon: "🌳", color: "from-emerald-500 to-lime-500", category: "literacy" }),
  g("story-smith", "Story Smith", "Solve Share Smile", { icon: "📜", color: "from-orange-500 to-rose-500", category: "literacy" }),
  g("alphabet-airship", "Alphabet Airship", "Build Explore Learn", { icon: "✈️", color: "from-sky-500 to-blue-600", category: "literacy", ageMin: 4, ageMax: 6, ageGroup: "Kindergarten (4-6)" }),
  g("sentence-safari", "Sentence Safari", "Focus Practice Win", { icon: "🦁", color: "from-fuchsia-500 to-violet-500", category: "literacy" }),
  g("rhyme-river", "Rhyme River", "Team Up Learn", { icon: "🏞️", color: "from-indigo-500 to-cyan-500", category: "literacy", ageMin: 4, ageMax: 6, ageGroup: "Kindergarten (4-6)" }),
  g("count-constellations", "Count Constellations", "Discover Create Grow", { icon: "🌟", color: "from-emerald-500 to-lime-500", category: "math" }),
  g("fraction-factory", "Fraction Factory", "Play Learn Grow", { icon: "🏭", color: "from-orange-500 to-rose-500", category: "math" }),
  g("garden-glow-lab", "Garden Glow Lab", "Think Move Learn", { icon: "🌿", color: "from-emerald-400 to-green-500", category: "science" }),
  g("firefly-word-weave", "Firefly Word Weave", "Solve Share Smile", { icon: "🪲", color: "from-amber-400 to-yellow-500", category: "literacy" }),
  g("river-route-rangers", "River Route Rangers", "Build Explore Learn", { icon: "🛶", color: "from-sky-400 to-blue-500", category: "adventure" }),
];

/* ═══════════════════════════════════════════════════
   ARCADE GAMES — 19 games with real .tsx files
   (arcade-061 through arcade-070, arcade-121 through arcade-129)
   ═══════════════════════════════════════════════════ */
export const ARCADE_GAMES: RegisteredGame[] = [
  g("arcade-061", "Pixel Prism Patrol", "Play Learn Grow", { icon: "🔮", color: "from-indigo-500 to-cyan-500", category: "logic", mode: "arcade", mechanic: "lane-sort" }),
  g("arcade-062", "Spark Factor Furnace", "Think Move Learn", { icon: "🔥", color: "from-orange-500 to-rose-500", category: "math", mode: "arcade", mechanic: "timed-equation" }),
  g("arcade-063", "Echo Claim Cascade", "Solve Share Smile", { icon: "📢", color: "from-fuchsia-500 to-violet-500", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("arcade-064", "Luna Sequence Symphony", "Build Explore Learn", { icon: "🎵", color: "from-sky-500 to-blue-600", category: "creative", mode: "arcade", mechanic: "sequence-recall" }),
  g("arcade-065", "Terra Ecosystem Rescue", "Focus Practice Win", { icon: "🌍", color: "from-emerald-500 to-lime-500", category: "science", mode: "arcade", mechanic: "signal-balance" }),
  g("arcade-066", "Spark Thruster Trial", "Team Up Learn", { icon: "🚀", color: "from-orange-500 to-rose-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("arcade-067", "Echo Truthline Protocol", "Discover Create Grow", { icon: "⚖️", color: "from-fuchsia-500 to-violet-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("arcade-068", "Terra Wilds Recovery", "Play Learn Grow", { icon: "🏕️", color: "from-emerald-500 to-lime-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("arcade-069", "Luna Pulse Rally", "Think Move Learn", { icon: "🌙", color: "from-indigo-500 to-cyan-500", category: "arcade", mode: "arcade", mechanic: "signal-balance" }),
  g("arcade-070", "Pixel Firewall Frontier", "Solve Share Smile", { icon: "🛡️", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("arcade-121", "Breeze Trail", "Build Explore Learn", { icon: "🌬️", color: "from-sky-400 to-cyan-500", category: "adventure", mode: "arcade", mechanic: "sequence-recall" }),
  g("arcade-122", "Sprout Trail", "Focus Practice Win", { icon: "🌱", color: "from-emerald-400 to-lime-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("arcade-123", "Pebble Trail", "Team Up Learn", { icon: "🪨", color: "from-stone-400 to-amber-500", category: "adventure", mode: "arcade", mechanic: "lane-sort" }),
  g("arcade-124", "Nimbus Trail", "Discover Create Grow", { icon: "☁️", color: "from-sky-300 to-blue-500", category: "science", mode: "arcade", mechanic: "signal-balance" }),
  g("arcade-125", "Flare Trail", "Play Learn Grow", { icon: "🔥", color: "from-orange-400 to-red-500", category: "arcade", mode: "arcade", mechanic: "timed-equation" }),
  g("arcade-126", "Sky Circuit", "Think Move Learn", { icon: "✈️", color: "from-sky-500 to-indigo-500", category: "arcade", mode: "arcade", mechanic: "lane-sort" }),
  g("arcade-127", "River Circuit", "Solve Share Smile", { icon: "🏞️", color: "from-cyan-500 to-teal-500", category: "adventure", mode: "arcade", mechanic: "pattern-scan" }),
  g("arcade-128", "Echo Circuit", "Build Explore Learn", { icon: "📡", color: "from-violet-500 to-purple-500", category: "logic", mode: "arcade", mechanic: "sequence-recall" }),
  g("arcade-129", "Luna Circuit", "Focus Practice Win", { icon: "🌙", color: "from-indigo-400 to-violet-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
];

/* ═══════════════════════════════════════════════════
   CLASSIC GAMES — 48 classic game ports with real .tsx
   ═══════════════════════════════════════════════════ */
export const CLASSIC_GAMES: RegisteredGame[] = [
  g("2048", "2048", "Merge Number Tiles", { icon: "🔢", color: "from-amber-400 to-orange-500", category: "math", mechanic: "pattern-scan" }),
  g("anagram", "Anagram", "Unscramble Word Puzzles", { icon: "🔠", color: "from-sky-400 to-blue-500", category: "literacy", mechanic: "precision-choice" }),
  g("asteroids", "Asteroids", "Blast Space Rocks", { icon: "☄️", color: "from-indigo-500 to-cyan-500", category: "arcade", mechanic: "precision-choice" }),
  g("binary-puzzle", "Binary Puzzle", "Solve Binary Grid", { icon: "0️⃣", color: "from-emerald-500 to-lime-500", category: "logic", mechanic: "pattern-scan" }),
  g("bomberman", "Bomberman", "Blast Clear Path", { icon: "💣", color: "from-orange-500 to-rose-500", category: "arcade", mechanic: "lane-sort" }),
  g("breakout", "Breakout", "Break Block Wall", { icon: "🧱", color: "from-fuchsia-500 to-violet-500", category: "arcade", mechanic: "precision-choice" }),
  g("bubble-shooter", "Bubble Shooter", "Pop Color Bubbles", { icon: "🫧", color: "from-sky-400 to-blue-500", category: "arcade", mechanic: "precision-choice" }),
  g("checkers", "Checkers", "Jump Capture Kings", { icon: "⬛", color: "from-stone-500 to-stone-700", category: "logic", mechanic: "precision-choice" }),
  g("chess", "Chess", "Classic Board Strategy", { icon: "♟️", color: "from-stone-600 to-stone-800", category: "logic", mechanic: "precision-choice", ageMin: 7, ageMax: 18, educationalWeight: 90 }),
  g("color-flood", "Color Flood", "Flood Fill Board", { icon: "🎨", color: "from-fuchsia-400 to-pink-500", category: "logic", mechanic: "pattern-scan" }),
  g("connect-four", "Connect Four", "Four In Row", { icon: "🔴", color: "from-red-400 to-yellow-500", category: "logic", mechanic: "precision-choice" }),
  g("connections", "Connections", "Group Word Links", { icon: "🔗", color: "from-violet-400 to-purple-500", category: "literacy", mechanic: "pattern-scan" }),
  g("cookie-clicker", "Cookie Clicker", "Click Earn Grow", { icon: "🍪", color: "from-amber-300 to-amber-500", category: "math", mechanic: "precision-choice" }),
  g("crossword", "Crossword", "Solve Word Grid", { icon: "📰", color: "from-stone-400 to-stone-600", category: "literacy", mechanic: "precision-choice" }),
  g("dot-connect", "Dot Connect", "Connect All Dots", { icon: "⚫", color: "from-indigo-400 to-violet-500", category: "logic", mechanic: "pattern-scan" }),
  g("duck-hunt", "Duck Hunt", "Aim Shoot Ducks", { icon: "🦆", color: "from-emerald-400 to-green-500", category: "arcade", mechanic: "precision-choice" }),
  g("factors", "Factors", "Find Number Factors", { icon: "✖️", color: "from-sky-500 to-blue-600", category: "math", mechanic: "timed-equation" }),
  g("flappy", "Flappy", "Fly Through Pipes", { icon: "🐤", color: "from-sky-300 to-sky-500", category: "arcade", mechanic: "precision-choice" }),
  g("frogger", "Frogger", "Cross Safe Roads", { icon: "🐸", color: "from-emerald-500 to-lime-500", category: "arcade", mechanic: "lane-sort" }),
  g("hangman", "Hangman", "Guess Word Letters", { icon: "🪢", color: "from-amber-400 to-amber-600", category: "literacy", mechanic: "precision-choice" }),
  g("logic-grid", "Logic Grid", "Solve Logic Grid", { icon: "🧩", color: "from-violet-500 to-purple-600", category: "logic", mechanic: "pattern-scan" }),
  g("mahjong", "Mahjong", "Match Tile Pairs", { icon: "🀄", color: "from-emerald-400 to-teal-500", category: "logic", mechanic: "pattern-scan" }),
  g("make-24", "Make 24", "Math Equals Twenty-Four", { icon: "2️⃣", color: "from-amber-500 to-orange-500", category: "math", mechanic: "timed-equation" }),
  g("math-sprint", "Math Sprint", "Speed Math Race", { icon: "🏃", color: "from-sky-500 to-blue-500", category: "math", mechanic: "timed-equation" }),
  g("math-trainer", "Math Trainer", "Practice Math Skills", { icon: "📐", color: "from-indigo-400 to-blue-500", category: "math", mechanic: "timed-equation" }),
  g("memory-game", "Memory Game", "Flip Match Cards", { icon: "🃏", color: "from-fuchsia-400 to-violet-500", category: "logic", mechanic: "sequence-recall" }),
  g("minesweeper", "Minesweeper", "Clear Mine Field", { icon: "💣", color: "from-stone-400 to-stone-600", category: "logic", mechanic: "pattern-scan" }),
  g("missile-command", "Missile Command", "Defend City Base", { icon: "🚀", color: "from-red-500 to-orange-500", category: "arcade", mechanic: "precision-choice" }),
  g("number-dots", "Number Dots", "Connect Number Dots", { icon: "🔵", color: "from-sky-400 to-cyan-500", category: "math", mechanic: "pattern-scan" }),
  g("numm-match", "Numm Match", "Match Number Pairs", { icon: "🔢", color: "from-emerald-400 to-lime-500", category: "math", mechanic: "pattern-scan" }),
  g("pong", "Pong", "Paddle Ball Rally", { icon: "🏓", color: "from-stone-500 to-stone-700", category: "arcade", mechanic: "precision-choice" }),
  g("reaction-time", "Reaction Time", "Test Fast Reflexes", { icon: "⚡", color: "from-yellow-400 to-amber-500", category: "arcade", mechanic: "precision-choice" }),
  g("reversi", "Reversi", "Flip Board Tiles", { icon: "⚫", color: "from-emerald-600 to-emerald-800", category: "logic", mechanic: "precision-choice" }),
  g("simon", "Simon", "Repeat Color Pattern", { icon: "🔴", color: "from-red-400 to-blue-500", category: "logic", mechanic: "sequence-recall" }),
  g("sliding-puzzle", "Sliding Puzzle", "Slide Tile Solve", { icon: "🧩", color: "from-amber-400 to-orange-500", category: "logic", mechanic: "pattern-scan" }),
  g("snake", "Snake", "Grow Snake Trail", { icon: "🐍", color: "from-emerald-400 to-green-600", category: "arcade", mechanic: "precision-choice" }),
  g("sokoban", "Sokoban", "Push Box Puzzle", { icon: "📦", color: "from-amber-400 to-amber-600", category: "logic", mechanic: "pattern-scan" }),
  g("solitaire", "Solitaire", "Stack Card Suits", { icon: "🃏", color: "from-emerald-500 to-teal-600", category: "logic", mechanic: "pattern-scan" }),
  g("space-invaders", "Space Invaders", "Blast Alien Fleet", { icon: "👾", color: "from-indigo-500 to-violet-600", category: "arcade", mechanic: "precision-choice" }),
  g("spider-solitaire", "Spider Solitaire", "Eight Suit Stack", { icon: "🕷️", color: "from-stone-500 to-stone-700", category: "logic", mechanic: "pattern-scan" }),
  g("sudoku", "Sudoku", "Fill Number Grid", { icon: "🔢", color: "from-sky-400 to-indigo-500", category: "math", mechanic: "pattern-scan" }),
  g("tetris", "Tetris", "Stack Block Lines", { icon: "🧱", color: "from-cyan-500 to-blue-600", category: "arcade", mechanic: "lane-sort" }),
  g("tic-tac-toe", "Tic Tac Toe", "Three In Row", { icon: "❌", color: "from-sky-400 to-blue-500", category: "logic", mechanic: "precision-choice" }),
  g("tower-stack", "Tower Stack", "Stack Tower High", { icon: "🏗️", color: "from-amber-400 to-red-500", category: "arcade", mechanic: "precision-choice" }),
  g("trivia-quiz", "Trivia Quiz", "Answer Quick Trivia", { icon: "❓", color: "from-violet-400 to-purple-500", category: "logic", mechanic: "precision-choice" }),
  g("typing-speed", "Typing Speed", "Type Fast Words", { icon: "⌨️", color: "from-sky-500 to-blue-600", category: "literacy", mechanic: "timed-equation" }),
  g("whack-a-mole", "Whack A Mole", "Whack Fast Moles", { icon: "🦫", color: "from-emerald-400 to-green-500", category: "arcade", mechanic: "precision-choice" }),
  g("word-pluck", "Word Pluck", "Pluck Hidden Words", { icon: "🔍", color: "from-amber-400 to-orange-500", category: "literacy", mechanic: "pattern-scan" }),
  g("word-rescue", "Word Rescue", "Rescue Lost Words", { icon: "🆘", color: "from-red-400 to-rose-500", category: "literacy", mechanic: "precision-choice" }),
  g("word-scramble", "Word Scramble", "Unscramble Word Mix", { icon: "🔀", color: "from-fuchsia-400 to-violet-500", category: "literacy", mechanic: "precision-choice" }),
  g("wordle", "Wordle", "Guess Five Letters", { icon: "📝", color: "from-emerald-500 to-lime-500", category: "literacy", mechanic: "precision-choice" }),
];

/* ═══════════════════════════════════════════════════
   ZONE GAMES — 65 zone games with real .tsx files
   (zone-041 through zone-076, zone-077 through zone-099,
    zone-101 through zone-125)
   ═══════════════════════════════════════════════════ */
export const ZONE_GAMES: RegisteredGame[] = [
  // Zone original (041-076)
  g("zone-041", "Signal Rescue", "Rescue Signal Fast", { icon: "📡", color: "from-indigo-500 to-cyan-500", category: "logic", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-042", "Math Rail Commander", "Command Math Rails", { icon: "🚂", color: "from-emerald-500 to-lime-500", category: "math", mode: "arcade", mechanic: "timed-equation" }),
  g("zone-043", "Echo Story Signal", "Signal Story Path", { icon: "📖", color: "from-orange-500 to-rose-500", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-044", "Terra Lab Sort", "Sort Lab Samples", { icon: "🧪", color: "from-fuchsia-500 to-violet-500", category: "science", mode: "arcade", mechanic: "lane-sort" }),
  g("zone-045", "Luna Rhythm Forge", "Forge Beat Rhythm", { icon: "🥁", color: "from-sky-500 to-blue-600", category: "creative", mode: "arcade", mechanic: "sequence-recall" }),
  g("zone-046", "Pixel Cipher Sprint", "Sprint Cipher Codes", { icon: "🔐", color: "from-indigo-500 to-cyan-500", category: "logic", mode: "arcade", mechanic: "timed-equation" }),
  g("zone-047", "Spark Grid Fuse", "Fuse Power Grid", { icon: "⚡", color: "from-emerald-500 to-lime-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-048", "Echo Evidence Judge", "Judge Key Evidence", { icon: "⚖️", color: "from-orange-500 to-rose-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-049", "Terra Habitat Triage", "Triage Wild Habitats", { icon: "🏕️", color: "from-fuchsia-500 to-violet-500", category: "science", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-050", "Pixel Lane Defender", "Defend Pixel Lanes", { icon: "🛡️", color: "from-sky-500 to-blue-600", category: "arcade", mode: "arcade", mechanic: "lane-sort" }),
  g("zone-051", "Luna Chorus Cascade", "Cascade Music Chorus", { icon: "🎶", color: "from-indigo-500 to-cyan-500", category: "creative", mode: "arcade", mechanic: "sequence-recall" }),
  g("zone-052", "Spark Reactor Grid", "Power Reactor Grid", { icon: "⚛️", color: "from-emerald-500 to-lime-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-053", "Echo Debate Duel", "Duel Debate Points", { icon: "🗣️", color: "from-orange-500 to-rose-500", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-054", "Terra Weather Command", "Command Weather Ops", { icon: "🌦️", color: "from-fuchsia-500 to-violet-500", category: "science", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-055", "Pixel Drone Intercept", "Intercept Drone Signal", { icon: "🚁", color: "from-sky-500 to-blue-600", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-056", "Spark Orbital Surge", "Surge Orbital Path", { icon: "🛸", color: "from-indigo-500 to-cyan-500", category: "science", mode: "arcade", mechanic: "lane-sort" }),
  g("zone-057", "Echo Signal Crossfire", "Crossfire Signal Lock", { icon: "📻", color: "from-emerald-500 to-lime-500", category: "logic", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-058", "Terra Rift Shelter", "Shelter Rift Zone", { icon: "🏔️", color: "from-orange-500 to-rose-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-059", "Luna Stage Strategy", "Stage Strategy Plan", { icon: "🎭", color: "from-fuchsia-500 to-violet-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-060", "Pixel Circuit Siege", "Siege Circuit Path", { icon: "🔌", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-061", "Spark Flux Gauntlet", "Run Flux Gauntlet", { icon: "⚡", color: "from-indigo-500 to-cyan-500", category: "arcade", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-062", "Echo Proof Relay", "Relay Proof Chain", { icon: "🔗", color: "from-emerald-500 to-lime-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-063", "Terra Greenhouse Command", "Command Green House", { icon: "🌿", color: "from-orange-500 to-rose-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-064", "Luna Beatline Run", "Run Beatline Track", { icon: "🎵", color: "from-fuchsia-500 to-violet-500", category: "creative", mode: "arcade", mechanic: "sequence-recall" }),
  g("zone-065", "Pixel Breach Hunter", "Hunt Data Breach", { icon: "🔍", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-066", "Spark Thruster Trial", "Trial Thruster Burn", { icon: "🚀", color: "from-indigo-500 to-cyan-500", category: "science", mode: "arcade", mechanic: "timed-equation" }),
  g("zone-067", "Echo Truthline Protocol", "Protocol Truth Check", { icon: "✅", color: "from-emerald-500 to-lime-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-068", "Terra Wilds Recovery", "Recover Wild Lands", { icon: "🌲", color: "from-orange-500 to-rose-500", category: "science", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-069", "Luna Pulse Rally", "Rally Pulse Beat", { icon: "💓", color: "from-fuchsia-500 to-violet-500", category: "arcade", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-070", "Pixel Firewall Frontier", "Guard Firewall Line", { icon: "🔥", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-071", "Spark Reactor Convoy", "Convoy Reactor Core", { icon: "⚛️", color: "from-indigo-500 to-cyan-500", category: "science", mode: "arcade", mechanic: "lane-sort" }),
  g("zone-072", "Echo Signal Tribunal", "Tribunal Signal Judge", { icon: "⚖️", color: "from-emerald-500 to-lime-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-073", "Terra Frontline Wardens", "Guard Frontline Post", { icon: "🛡️", color: "from-orange-500 to-rose-500", category: "adventure", mode: "arcade", mechanic: "signal-balance" }),
  g("zone-074", "Luna Skyline Set", "Set Skyline Stage", { icon: "🌆", color: "from-fuchsia-500 to-violet-500", category: "creative", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-075", "Pixel Sentinel Lattice", "Lattice Sentinel Guard", { icon: "🏰", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-076", "Spark Vault Thrust", "Thrust Vault Power", { icon: "💎", color: "from-indigo-500 to-cyan-500", category: "arcade", mode: "arcade", mechanic: "timed-equation" }),
  // Zone classic (077-099)
  g("zone-077", "Pixel Block Drop", "Drop Block Stack", { icon: "🧱", color: "from-cyan-500 to-blue-600", category: "arcade", mode: "arcade", mechanic: "lane-sort" }),
  g("zone-078", "Spark Breakout Surge", "Surge Break Blocks", { icon: "💥", color: "from-orange-400 to-red-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-079", "Luna Zigzag Run", "Run Zigzag Path", { icon: "🏃", color: "from-indigo-400 to-violet-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-080", "Echo Word Rescue", "Rescue Lost Words", { icon: "📝", color: "from-emerald-400 to-lime-500", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-081", "Terra Minefield Map", "Map Safe Minefield", { icon: "💣", color: "from-stone-400 to-stone-600", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-082", "Pixel Shaft Drop", "Drop Shaft Fast", { icon: "⛏️", color: "from-amber-400 to-orange-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-083", "Luna Sequence Flash", "Flash Color Sequence", { icon: "🔴", color: "from-red-400 to-blue-500", category: "logic", mode: "arcade", mechanic: "sequence-recall" }),
  g("zone-084", "Echo Anagram Blast", "Blast Word Anagrams", { icon: "🔠", color: "from-fuchsia-400 to-violet-500", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-085", "Spark Idle Forge", "Forge Idle Power", { icon: "🔨", color: "from-amber-300 to-amber-500", category: "math", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-086", "Terra Tile Pair", "Pair Matching Tiles", { icon: "🀄", color: "from-emerald-400 to-teal-500", category: "logic", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-087", "Pixel Merge 2048", "Merge Number Tiles", { icon: "🔢", color: "from-amber-400 to-orange-500", category: "math", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-088", "Spark Flap Surge", "Surge Flap Flight", { icon: "🐤", color: "from-sky-300 to-sky-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-089", "Luna Sudoku Grid", "Fill Sudoku Grid", { icon: "🔢", color: "from-sky-400 to-indigo-500", category: "math", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-090", "Echo Connect Drop", "Drop Connect Four", { icon: "🔴", color: "from-red-400 to-yellow-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-091", "Terra Whack Squad", "Whack Mole Squad", { icon: "🦫", color: "from-emerald-400 to-green-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-092", "Pixel Card Match", "Match Card Pairs", { icon: "🃏", color: "from-fuchsia-400 to-violet-500", category: "logic", mode: "arcade", mechanic: "sequence-recall" }),
  g("zone-093", "Spark Snake Trail", "Trail Snake Grow", { icon: "🐍", color: "from-emerald-400 to-green-600", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-094", "Luna Word Grid", "Search Word Grid", { icon: "🔍", color: "from-amber-400 to-orange-500", category: "literacy", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-095", "Echo Bubble Burst", "Burst Color Bubbles", { icon: "🫧", color: "from-sky-400 to-blue-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-096", "Terra Crossword", "Solve Word Cross", { icon: "📰", color: "from-stone-400 to-stone-600", category: "literacy", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-097", "Pixel Type Rush", "Rush Type Fast", { icon: "⌨️", color: "from-sky-500 to-blue-600", category: "literacy", mode: "arcade", mechanic: "timed-equation" }),
  g("zone-098", "Spark Dice Roll", "Roll Lucky Dice", { icon: "🎲", color: "from-amber-400 to-orange-500", category: "math", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-099", "Luna Endless Run", "Run Endless Path", { icon: "🏃", color: "from-indigo-400 to-violet-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  // Zone unique (101-125)
  g("zone-101", "Voxel Craft World", "Build Voxel World", { icon: "🧊", color: "from-emerald-400 to-cyan-500", category: "creative", mode: "arcade", mechanic: "precision-choice", ageMin: 7, ageMax: 14, ageGroup: "Elementary (7-11)" }),
  g("zone-102", "Neon Heist City", "Heist Neon City", { icon: "🌃", color: "from-fuchsia-500 to-violet-600", category: "adventure", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-103", "Storm Royale Arena", "Storm Arena Battle", { icon: "⛈️", color: "from-sky-500 to-indigo-600", category: "arcade", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-104", "Soul Dungeon Ascent", "Ascend Dark Dungeon", { icon: "🗡️", color: "from-stone-500 to-stone-700", category: "adventure", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-105", "Hex Quest Saga", "Quest Hex World", { icon: "⬡", color: "from-emerald-500 to-teal-600", category: "adventure", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-106", "Frontier Trail Rider", "Ride Frontier Trail", { icon: "🐎", color: "from-amber-400 to-amber-600", category: "adventure", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-107", "Dice Destiny RPG", "Roll Destiny Dice", { icon: "🎲", color: "from-violet-400 to-purple-500", category: "adventure", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-108", "Elder Realm Quest", "Quest Elder Realm", { icon: "🧙", color: "from-emerald-500 to-teal-600", category: "adventure", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-109", "Guild Raid Legends", "Raid Guild Dungeon", { icon: "⚔️", color: "from-orange-500 to-red-500", category: "adventure", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-110", "Tactical Ops Strike", "Strike Tactical Ops", { icon: "🎯", color: "from-stone-500 to-stone-700", category: "arcade", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-111", "Drop Zone Survivor", "Survive Drop Zone", { icon: "🪂", color: "from-sky-400 to-blue-600", category: "arcade", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-112", "Harvest Bloom Farm", "Farm Harvest Bloom", { icon: "🌾", color: "from-amber-300 to-amber-500", category: "science", mode: "arcade", mechanic: "pattern-scan" }),
  g("zone-113", "Ruin Survivor Trek", "Trek Ruin Survive", { icon: "🏚️", color: "from-stone-400 to-amber-500", category: "adventure", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-114", "Inferno Run Ascent", "Ascend Inferno Run", { icon: "🔥", color: "from-orange-500 to-red-600", category: "arcade", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-115", "Mind Palace RPG", "Explore Mind Palace", { icon: "🧠", color: "from-violet-400 to-purple-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-116", "Abyssal Knight Deep", "Dive Knight Abyss", { icon: "🤿", color: "from-indigo-500 to-blue-700", category: "adventure", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)", ageLockRecommended: true }),
  g("zone-117", "Impostor Station", "Find Station Impostor", { icon: "🕵️", color: "from-red-400 to-rose-500", category: "logic", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-118", "Turbo Ball Arena", "Arena Ball Turbo", { icon: "⚽", color: "from-emerald-400 to-green-500", category: "arcade", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-119", "Primal Tamer Isle", "Tame Primal Beasts", { icon: "🦎", color: "from-emerald-500 to-teal-500", category: "science", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-120", "Terra Dig World", "Dig World Deep", { icon: "⛏️", color: "from-amber-400 to-orange-500", category: "science", mode: "arcade", mechanic: "precision-choice" }),
  g("zone-121", "Spark Helix Lock", "Lock Helix Spiral", { icon: "🧬", color: "from-indigo-500 to-cyan-500", category: "science", mode: "arcade", mechanic: "pattern-scan", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)" }),
  g("zone-122", "Echo Judgment Circuit", "Circuit Judgment Call", { icon: "⚖️", color: "from-emerald-500 to-lime-500", category: "logic", mode: "arcade", mechanic: "precision-choice", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)" }),
  g("zone-123", "Terra Colony Evac", "Evacuate Terra Colony", { icon: "🚀", color: "from-orange-500 to-rose-500", category: "science", mode: "arcade", mechanic: "signal-balance", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)" }),
  g("zone-124", "Luna Nova Cadence", "Cadence Nova Beat", { icon: "🌙", color: "from-fuchsia-500 to-violet-500", category: "creative", mode: "arcade", mechanic: "sequence-recall", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)" }),
  g("zone-125", "Pixel Containment Matrix", "Contain Pixel Matrix", { icon: "🔲", color: "from-sky-500 to-blue-600", category: "logic", mode: "arcade", mechanic: "pattern-scan", ageMin: 12, ageMax: 18, ageGroup: "Middle School (12-14)" }),
];

/* ═══════════════════════════════════════════════════
   HANDCRAFTED GAMES — 6 newly built educational games
   ═══════════════════════════════════════════════════ */
export const HANDCRAFTED_GAMES: RegisteredGame[] = [
  {
    id: "tangram-builder",
    title: "Tangram Builder",
    description: "Shape Puzzle Art",
    icon: "🔷",
    color: "from-violet-400 to-purple-500",
    ageMin: 5,
    ageMax: 10,
    ageGroup: "Elementary (7-11)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "math",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 88,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
  {
    id: "pipe-flow",
    title: "Pipe Flow",
    description: "Connect Water Pipes",
    icon: "💧",
    color: "from-sky-400 to-blue-500",
    ageMin: 6,
    ageMax: 12,
    ageGroup: "Elementary (7-11)",
    engine: "Unity 6+",
    track: "Educational Core",
    category: "logic",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 85,
    graphicsTier: "4k-ready",
    mechanic: "pattern-scan",
    backdropImage: ASSETS.bgBottom,
    backdropVideo: null,
  },
  {
    id: "fossil-dig",
    title: "Fossil Dig",
    description: "Excavate Classify Discover",
    icon: "🦴",
    color: "from-amber-400 to-orange-500",
    ageMin: 5,
    ageMax: 11,
    ageGroup: "Elementary (7-11)",
    engine: "Godot 4.3+",
    track: "Educational Core",
    category: "science",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 90,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.bgAuth,
    backdropVideo: null,
  },
  {
    id: "lemonade-stand",
    title: "Lemonade Stand",
    description: "Business Math Sim",
    icon: "🍋",
    color: "from-yellow-400 to-amber-500",
    ageMin: 7,
    ageMax: 12,
    ageGroup: "Elementary (7-11)",
    engine: "Unreal Engine 5.5+",
    track: "Educational Core",
    category: "math",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 92,
    graphicsTier: "4k-ready",
    mechanic: "timed-equation",
    backdropImage: ASSETS.heroSignIn,
    backdropVideo: null,
  },
  {
    id: "mirror-draw",
    title: "Mirror Draw",
    description: "Symmetry Art Draw",
    icon: "✏️",
    color: "from-fuchsia-400 to-pink-500",
    ageMin: 4,
    ageMax: 9,
    ageGroup: "Kindergarten (4-6)",
    engine: "Unity 6+",
    track: "Educational Core",
    category: "creative",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 80,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.heroHome,
    backdropVideo: null,
  },
  {
    id: "tiny-chef",
    title: "Tiny Chef",
    description: "Cook Learn Measure",
    icon: "👨‍🍳",
    color: "from-emerald-400 to-green-500",
    ageMin: 5,
    ageMax: 10,
    ageGroup: "Elementary (7-11)",
    engine: "Godot 4.3+",
    track: "Educational Core",
    category: "math",
    mode: "legacy",
    safeForChildren: true,
    ageLockRecommended: false,
    educationalWeight: 87,
    graphicsTier: "4k-ready",
    mechanic: "precision-choice",
    backdropImage: ASSETS.bgBottom,
    backdropVideo: null,
  },
];

/* ═══════════════════════════════════════════════════
   COMBINED CATALOG — only real games with components
   ═══════════════════════════════════════════════════ */
/* ─── pipeline games (2026-03) ─── */
export const PIPELINE_GAMES: RegisteredGame[] = [
  g("flag-dash", "Flag Dash", "Race to identify country flags from around the world", { category: "adventure", ageMin: 7, ageMax: 14, educationalWeight: 85, mechanic: "precision-choice" }),
  g("element-match", "Element Match", "Match periodic table symbols to element names", { category: "science", ageMin: 12, ageMax: 18, educationalWeight: 90, mechanic: "pattern-scan" }),
  g("timeline-dash", "Timeline Dash", "Arrange historical events in chronological order", { category: "literacy", ageMin: 10, ageMax: 18, educationalWeight: 88, mechanic: "lane-sort" }),
  g("body-atlas", "Body Atlas", "Place organs in the correct location on the human body", { category: "science", ageMin: 7, ageMax: 14, educationalWeight: 90, mechanic: "precision-choice" }),
  g("debug-detective", "Debug Detective", "Find and identify bugs in code snippets", { category: "logic", ageMin: 10, ageMax: 18, educationalWeight: 92, mechanic: "precision-choice" }),
  g("note-hunter", "Note Hunter", "Identify musical notes on the staff with audio feedback", { category: "creative", ageMin: 7, ageMax: 14, educationalWeight: 85, mechanic: "precision-choice" }),
  g("chord-builder", "Chord Builder", "Build chords by selecting notes on a piano keyboard", { category: "creative", ageMin: 10, ageMax: 18, educationalWeight: 88, mechanic: "precision-choice" }),
  g("beat-lab", "Beat Lab", "Listen to rhythm patterns and recreate them on a drum grid", { category: "creative", ageMin: 5, ageMax: 12, educationalWeight: 80, mechanic: "pattern-scan" }),
  g("budget-hero", "Budget Hero", "Build smart budgets across real-world financial scenarios", { category: "math", ageMin: 12, ageMax: 18, educationalWeight: 92, mechanic: "signal-balance" }),
  g("stock-sprint", "Stock Sprint", "Trade stocks in a simulated market with news events", { category: "math", ageMin: 14, ageMax: 22, educationalWeight: 88, mechanic: "signal-balance" }),
  g("nutrition-lab", "Nutrition Lab", "Build balanced meals hitting calorie, protein, and fiber targets", { category: "science", ageMin: 7, ageMax: 14, educationalWeight: 85, mechanic: "signal-balance" }),
  g("code-blocks", "Code Blocks", "Stack programming blocks to guide a robot through mazes", { category: "logic", ageMin: 7, ageMax: 12, educationalWeight: 92, mechanic: "sequence-recall" }),
  g("bridges-builder", "Bridges Builder", "Connect islands with the right number of bridges", { category: "logic", ageMin: 7, ageMax: 99, educationalWeight: 80, mechanic: "pattern-scan" }),
  g("light-towers", "Light Towers", "Place lights to illuminate every cell without conflicts", { category: "logic", ageMin: 7, ageMax: 99, educationalWeight: 80, mechanic: "pattern-scan" }),
  g("capital-quest", "Capital Quest", "Match countries to their capitals and learn world geography", { category: "adventure", ageMin: 7, ageMax: 14, educationalWeight: 85, mechanic: "precision-choice" }),
  g("truck-highway", "Truck Highway", "CDL-themed endless driving game with traffic avoidance and trivia checkpoints", { category: "adventure", ageMin: 16, ageMax: 99, educationalWeight: 85, mechanic: "precision-choice" }),
];

export const GAME_CATALOG: RegisteredGame[] = [
  ...CORE_GAMES,
  ...LEGACY_GAMES,
  ...CLASSIC_GAMES,
  ...ARCADE_GAMES,
  ...ZONE_GAMES,
  ...HANDCRAFTED_GAMES,
  ...PIPELINE_GAMES,
];

const gameMap = new Map(GAME_CATALOG.map((game) => [game.id, game]));

export function getRegisteredGame(gameId: string): RegisteredGame | null {
  return gameMap.get(gameId) ?? null;
}

export function isCoreGameType(gameId: string): gameId is GameType {
  return CORE_GAMES.some((game) => game.id === gameId);
}
