// This file is auto-generated by scripts/compile-media-prompts.mjs
// Do not edit manually.

export type MediaPrompt = {
  id: string;
  category: string;
  prompt: string;
  [key: string]: unknown;
};

export const MEDIA_PROMPTS: Record<string, MediaPrompt> = {
  "ANIM_PHASE_TRANSITION_01": {
    "id": "ANIM_PHASE_TRANSITION_01",
    "category": "ANIMATIONS",
    "prompt": "Create a horizontal progress-step transition animation for a lesson flow.\nVisual: a glowing dot travels along a path connecting 5 evenly spaced nodes.\nWhen it reaches the next node, the node fills with color and pulses once.\nPalette: use emerald-400 for completed nodes, zinc-300 for upcoming, white dot traveler.\nMotion: smooth ease-in-out travel (0.6s per segment), subtle pulse on arrival (0.3s).\nBackground: transparent.\nDuration: 0.9 seconds per transition, triggered by code.\nAccessibility: include anim_phase_transition-static.png showing all nodes filled."
  },
  "ANIM_FLASHCARD_FLIP_01": {
    "id": "ANIM_FLASHCARD_FLIP_01",
    "category": "ANIMATIONS",
    "prompt": "Create a card-flip animation for a flashcard review component.\nVisual: a rounded-corner card rotates 180 degrees on its Y-axis, revealing a different colored back.\nFront: white card with subtle border. Back: soft gradient (emerald to teal).\nMotion: realistic 3D perspective flip with slight overshoot and settle.\nDuration: 0.5 seconds.\nBackground: transparent.\nAccessibility: include anim_flashcard_flip-static.png showing the back of the card."
  },
  "ANIM_QUIZ_CORRECT_01": {
    "id": "ANIM_QUIZ_CORRECT_01",
    "category": "ANIMATIONS",
    "prompt": "Create a correct-answer celebration micro-animation.\nVisual: a checkmark draws itself in emerald-500, then a brief ring of small stars/sparkles\nexpands outward and fades. Clean, geometric, not cartoonish.\nMotion: checkmark draw (0.3s), sparkle expand (0.4s), fade (0.3s).\nTotal duration: 1.0 second, non-looping.\nBackground: transparent.\nAccessibility: include anim_quiz_correct-static.png showing the completed checkmark."
  },
  "ANIM_QUIZ_INCORRECT_01": {
    "id": "ANIM_QUIZ_INCORRECT_01",
    "category": "ANIMATIONS",
    "prompt": "Create a gentle incorrect-answer animation. This must NOT feel punishing.\nVisual: a soft X mark fades in with a slight wobble, then transforms into\na question mark with a subtle \"try again\" gesture.\nPalette: amber-400 (not red — red feels punishing to young learners).\nMotion: wobble in (0.3s), morph to question mark (0.4s), gentle pulse (0.3s).\nTotal duration: 1.0 second, non-looping.\nBackground: transparent.\nAccessibility: include anim_quiz_incorrect-static.png showing the question mark."
  },
  "ANIM_CELEBRATION_DEFAULT_01": {
    "id": "ANIM_CELEBRATION_DEFAULT_01",
    "category": "ANIMATIONS",
    "prompt": "Generate a celebration burst for the lesson completion screen.\nVisual: circles, triangles, and squares explode from center-out in a joyful burst.\nPalette: emerald-400, violet-400, amber-400, sky-400 on transparent background.\nMotion: quick burst (0.3s), then slow float-down with rotation and fade (1.5s).\nEasing: soft-out curves, no aggressive bounce.\nTotal duration: 1.8 seconds, can replay without visual clipping.\nAccessibility: include anim_celebration_default-static.png."
  },
  "ANIM_STAR_RATING_01": {
    "id": "ANIM_STAR_RATING_01",
    "category": "ANIMATIONS",
    "prompt": "Create a 3-star rating animation for the lesson celebration screen.\nVisual: 3 star outlines. Stars fill in sequence (left to right) based on score.\nEach star: draws outline, fills with gold, bounces once, settles.\nUnfilled stars remain as soft outlines.\nStagger: 0.3s between each star.\nPalette: amber-400 filled, zinc-200 outline.\nCode-driven: accept a parameter (1, 2, or 3) to determine how many stars fill.\nBackground: transparent.\nAccessibility: include anim_star_rating-static.png showing all 3 stars filled."
  },
  "ANIM_LOADING_DEFAULT_01": {
    "id": "ANIM_LOADING_DEFAULT_01",
    "category": "ANIMATIONS",
    "prompt": "Create a loopable loading animation for page transitions.\nVisual: node network connecting and disconnecting with soft emerald and violet glows.\nMotion: gentle pulse and subtle path travel, no sudden jumps.\nStyle: minimalist flat vector with restrained glow effects.\nBackground: transparent.\nDuration: 2.0-2.5 second seamless loop.\nAccessibility: include anim_loading_default-static.png with final stable frame."
  },
  "ANIM_SKELETON_SHIMMER_01": {
    "id": "ANIM_SKELETON_SHIMMER_01",
    "category": "ANIMATIONS",
    "prompt": "Create a shimmer/pulse effect for skeleton loading states.\nVisual: a horizontal light sweep moves left-to-right across a rounded rectangle shape.\nPalette: zinc-100 base, white-50 shimmer highlight.\nMotion: smooth linear sweep, 1.5s loop, no easing spikes.\nBackground: transparent.\nUse case: overlaid on skeleton placeholder cards in module/lesson loading states.\nAccessibility: include anim_skeleton_shimmer-static.png."
  },
  "ANIM_MODULE_UNLOCK_01": {
    "id": "ANIM_MODULE_UNLOCK_01",
    "category": "ANIMATIONS",
    "prompt": "Create a lock-to-unlock animation for curriculum progression.\nScene: closed silver lock icon on a rounded card.\nMotion: short rattle (0.3s), transform into pixel shards (0.4s), reveal open doorway icon (0.3s).\nTone: rewarding and playful, not violent or destructive.\nDuration: 1.0-1.3 seconds.\nBackground: transparent.\nAccessibility: include anim_module_unlock-static.png showing the open doorway."
  },
  "ANIM_WORLD_DISCOVER_01": {
    "id": "ANIM_WORLD_DISCOVER_01",
    "category": "ANIMATIONS",
    "prompt": "Create a world-reveal animation for when a new Explorer World becomes available.\nVisual: a dark fog/cloud parts to reveal a glowing orb in the center.\nThe orb resolves into the world's badge emoji (rendered as vector).\nMotion: fog part (0.6s), orb glow and resolve (0.5s), subtle float settle (0.3s).\nPalette: fog in zinc-400/zinc-600, orb glow matches world theme color.\nBackground: transparent.\nDuration: 1.4 seconds.\nAccessibility: include anim_world_discover-static.png showing the revealed badge."
  },
  "MODEL_ATOM_01": {
    "id": "MODEL_ATOM_01",
    "category": "ANIMATIONS",
    "prompt": "Generate a low-poly educational atom model for interactive science lessons.\nNucleus: separate proton (red) and neutron (blue) meshes clustered in center.\nElectrons: individual meshes grouped by orbit path (3 orbits) for code-driven animation.\nMaterial: clean matte/plastic hybrid, bright but not neon.\nTopology: game-ready, optimized for web (< 500KB).\nNamed mesh groups: \"nucleus\", \"orbit_1\", \"orbit_2\", \"orbit_3\", \"electron_1a\", etc.\nInclude anchor points for selection/highlight interactions."
  },
  "MODEL_SOLAR_SYSTEM_01": {
    "id": "MODEL_SOLAR_SYSTEM_01",
    "category": "ANIMATIONS",
    "prompt": "Generate a simplified solar system model for the Cosmic Quest world.\nSun: central glowing sphere (amber/gold).\nPlanets: 8 stylized spheres on orbit rings, each a separate named mesh.\nScale: educational (not to real scale — planets visible relative to orbits).\nMaterial: clean matte with subtle metallic sheen.\nTopology: web-optimized (< 1MB total).\nNamed groups: \"sun\", \"mercury\", \"venus\", \"earth\", \"mars\", \"jupiter\", \"saturn\", \"uranus\", \"neptune\", \"orbit_ring_{n}\"."
  },
  "MODEL_PLANT_CELL_01": {
    "id": "MODEL_PLANT_CELL_01",
    "category": "ANIMATIONS",
    "prompt": "Generate a cross-section plant cell model for the Nature Lab world.\nVisible structures: cell wall, cell membrane, nucleus, chloroplasts, vacuole, mitochondria.\nEach structure is a separate named mesh for interactive highlighting.\nMaterial: translucent outer wall, semi-opaque interior structures with distinct colors.\nStyle: educational diagram aesthetic, not photorealistic.\nTopology: web-optimized (< 800KB).\nNamed groups: \"cell_wall\", \"membrane\", \"nucleus\", \"chloroplast_{n}\", \"vacuole\", \"mitochondria_{n}\"."
  },
  "ANIM_AVATAR_ROBOT_IDLE_01": {
    "id": "ANIM_AVATAR_ROBOT_IDLE_01",
    "category": "ANIMATIONS",
    "prompt": "Design a friendly robot idle animation for profile and onboarding screens.\nMotion loop: gentle vertical bob, antenna twitch, periodic blink, occasional small wave.\nStyle: clean vector art, approachable, classroom-safe. Friendly helper aesthetic; avoid militarized or intimidating robot design.\nPalette: zinc-700 body, emerald-400 eyes/accents, amber-400 antenna tip.\nLoop duration: 3.0 seconds.\nAvoid jitter and hard edges.\nAccessibility: include anim_avatar_robot_idle-static.png."
  },
  "ANIM_AVATAR_PLACEHOLDER_01": {
    "id": "ANIM_AVATAR_PLACEHOLDER_01",
    "category": "ANIMATIONS",
    "prompt": "Generate 6 distinct avatar placeholder animations for the profile selection screen.\nEach avatar is a simple, abstract character (geometric shapes — no human faces).\nEach has a unique idle micro-animation:\n1. Gentle bounce\n2. Slow spin\n3. Breathe (scale pulse)\n4. Eye blink (two dots)\n5. Color shift (hue rotate within a small range)\n6. Wave (small arm/appendage)\n\nPalette per avatar matches PROFILE_THEMES from select-profile page:\n1. emerald-400 to teal-500\n2. violet-400 to purple-500\n3. amber-400 to orange-500\n4. sky-400 to blue-500\n5. rose-400 to pink-500\n6. lime-400 to green-500\n\nLoop duration: 2.5-3.5 seconds each.\nBackground: transparent.\nAccessibility: include -static.png for each."
  },
  "ANIM_AUTH_HERO_ORBS_01": {
    "id": "ANIM_AUTH_HERO_ORBS_01",
    "category": "ANIMATIONS",
    "prompt": "Create an ambient background loop for the sign-in hero section.\nVisual: 3-4 translucent organic blobs drifting slowly across a soft gradient field.\nPalette: emerald-300, sky-300, amber-200 with low opacity.\nMotion: slow float, slight scale breathing, no abrupt direction changes.\nDuration: 10-14 seconds seamless loop.\nBackground: transparent.\nAccessibility: include anim_auth_hero_orbs-static.png fallback frame."
  },
  "ANIM_AUTH_SOCIAL_REVEAL_01": {
    "id": "ANIM_AUTH_SOCIAL_REVEAL_01",
    "category": "ANIMATIONS",
    "prompt": "Create a gentle reveal animation for a 2-column social sign-in grid.\nVisual: four rounded pill placeholders fade and slide upward in a stagger.\nStagger timing: 80ms between cells.\nMotion: fade + translateY(8px -> 0), no bounce.\nDuration: 420-520ms total.\nTone: premium, calm, inviting.\nAccessibility: include anim_auth_social_reveal-static.png."
  },
  "ANIM_AUTH_HEADER_ACCENT_01": {
    "id": "ANIM_AUTH_HEADER_ACCENT_01",
    "category": "ANIMATIONS",
    "prompt": "Generate a subtle animated accent for the top header under-brand area.\nVisual: thin organic ribbon with soft light pulse traveling left-to-right.\nPalette: gradient blend of mint -> sky -> warm gold.\nMotion: low-frequency pulse, no flashing.\nLoop: 4-6 seconds.\nUse case: decorative layer behind brand mark, should never distract from navigation.\nAccessibility: include anim_auth_header_accent-static.png."
  },
  "VIDEO_TREE_INTRO_01": {
    "id": "VIDEO_TREE_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create an immersive intro to a nature exploration world.\nScene beats:\n1) Dawn light breaks through a canopy of stylized trees (low-poly with soft glow edges).\n2) Camera descends to forest floor — mushrooms, moss, dewdrops catch light.\n3) A seed in the soil cracks open, sending a glowing root tendril downward and a tiny sprout upward.\n4) Camera pulls back to reveal the full forest, alive with gentle particle effects (pollen, fireflies).\nStyle: soft-tech naturalism — organic shapes with subtle digital glow accents.\nPalette: emerald-400, teal-500, amber highlights.\nCamera: slow continuous descent then pull-back, no cuts.\nDuration: 20-24 seconds."
  },
  "VIDEO_TREE_PHOTOSYNTHESIS_01": {
    "id": "VIDEO_TREE_PHOTOSYNTHESIS_01",
    "category": "VIDEOS",
    "prompt": "Create a stylized macro journey inside a leaf cell.\nScene beats:\n1) Enter chloroplast environment with layered green structures resembling a cathedral.\n2) Photons arrive as gentle golden light packets hitting molecular machinery.\n3) Internal machinery spins and converts inputs into crystalline sugar forms.\n4) Pull back to show the leaf from outside, glowing with stored energy.\nTone: scientific wonder, clear process flow, not medically graphic.\nCamera: smooth forward track with subtle parallax, then gentle pull-back.\nDuration: 24-30 seconds."
  },
  "VIDEO_TREE_GROWTH_01": {
    "id": "VIDEO_TREE_GROWTH_01",
    "category": "VIDEOS",
    "prompt": "Time-lapse of a seed growing into a tree in a gentle stylized environment.\nScene beats:\n1) Seed in dark soil, rain drops land softly.\n2) Root system extends downward (visible through cross-section).\n3) Sprout breaks surface, stem grows, first leaves unfurl.\n4) Tree matures through seasons (spring blossoms, summer canopy, autumn leaves, winter bare).\nStyle: warm picture-book aesthetic with clean geometry.\nCamera: side cross-section view transitioning to full tree reveal.\nDuration: 22-26 seconds."
  },
  "VIDEO_OCEAN_INTRO_01": {
    "id": "VIDEO_OCEAN_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create a descent into the deep ocean.\nScene beats:\n1) Surface: sunlight dances on gentle waves, looking down into blue.\n2) Descent: light fades gradually, colors shift from teal to deep blue to dark.\n3) Mid-depth: a school of bioluminescent fish swims past, trailing soft light.\n4) Deep: the ocean floor reveals unexpected structures — thermal vents, coral formations, glowing creatures.\nStyle: cinematic wonder, calm pacing, scientific atmosphere.\nPalette: sky-400 surface transitioning to blue-900 depth, with cyan/teal bioluminescence.\nCamera: continuous vertical descent, very slow rotation.\nDuration: 22-26 seconds."
  },
  "VIDEO_OCEAN_CORAL_01": {
    "id": "VIDEO_OCEAN_CORAL_01",
    "category": "VIDEOS",
    "prompt": "Explore a vibrant coral reef showing symbiotic relationships.\nScene beats:\n1) Wide shot of reef with diverse coral shapes and colors.\n2) Close-up: clownfish sheltering in anemone tentacles.\n3) Close-up: cleaner shrimp on a larger fish.\n4) Pull back to show the reef as a connected community, arrows/lines suggesting energy flow.\nStyle: stylized realism — vivid colors, clear forms, not photorealistic.\nCamera: gentle lateral tracking with close-up inserts.\nDuration: 24-28 seconds."
  },
  "VIDEO_OCEAN_WATERCYCLE_01": {
    "id": "VIDEO_OCEAN_WATERCYCLE_01",
    "category": "VIDEOS",
    "prompt": "Visualize the water cycle starting and ending in the ocean.\nScene beats:\n1) Ocean surface: sun heats water, vapor rises as soft glowing particles.\n2) Sky: particles collect into a cloud (gentle condensation).\n3) Mountain: cloud releases rain over a landscape.\n4) River: water flows back to the ocean, completing the loop.\nStyle: clean, diagrammatic but beautiful — not a flat infographic.\nCamera: continuous pan following the water's journey in a circular path.\nDuration: 22-26 seconds, loop-friendly ending."
  },
  "VIDEO_SPACE_INTRO_01": {
    "id": "VIDEO_SPACE_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create an awe-inspiring launch into space.\nScene beats:\n1) Earth's surface at dawn, camera rises through clouds.\n2) Break through atmosphere — sky transitions from blue to black.\n3) Stars appear, then a slow pan reveals a galaxy arm stretching across the viewport.\n4) Camera settles near a colorful nebula with gentle particle drift.\nStyle: cinematic but accessible — wonder without intimidation.\nPalette: violet-400, sky-400, amber-400 nebula highlights against deep black.\nCamera: continuous upward rise then slow lateral drift.\nDuration: 22-26 seconds."
  },
  "VIDEO_SPACE_GRAVITY_01": {
    "id": "VIDEO_SPACE_GRAVITY_01",
    "category": "VIDEOS",
    "prompt": "Visualize gravity using the classic fabric-of-space metaphor.\nScene beats:\n1) Flat grid plane representing spacetime.\n2) A large sphere (planet) is placed, grid deforms into a well.\n3) A small sphere (moon) rolls along the curved grid, orbiting.\n4) Remove the planet — grid snaps flat, moon flies off in a straight line.\nStyle: clean minimal geometry, educational clarity over cinematic drama.\nCamera: slightly elevated 3/4 view, slow orbit.\nDuration: 20-24 seconds."
  },
  "VIDEO_SPACE_FIBONACCI_01": {
    "id": "VIDEO_SPACE_FIBONACCI_01",
    "category": "VIDEOS",
    "prompt": "Show the Fibonacci spiral appearing across scales.\nScene beats:\n1) Nautilus shell forming in void space with golden ratio overlay lines.\n2) Transition: same spiral in a sunflower seed arrangement.\n3) Transition: same spiral in a galaxy arm, camera pulling far back.\nStyle: elegant, minimal, dark background with warm gold spiral lines.\nCamera: smooth zoom-out transitions across all three examples.\nDuration: 22-26 seconds, loop-friendly ending."
  },
  "VIDEO_NUMBERS_INTRO_01": {
    "id": "VIDEO_NUMBERS_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create a world where numbers are alive.\nScene beats:\n1) A simple landscape where objects are made of numbers — trees with \"3\" leaves, clouds of \"7\"s.\n2) Numbers rearrange themselves into patterns (1, 1, 2, 3, 5... Fibonacci emerging).\n3) A number \"puzzle box\" opens, revealing a glowing equation that balances.\n4) Camera pulls back to show the whole number landscape humming with pattern energy.\nStyle: playful geometry, bright and clean, no clutter.\nPalette: amber-400, emerald-400, violet-400 numbers on warm white/cream background.\nCamera: slow dolly through the landscape.\nDuration: 20-24 seconds."
  },
  "VIDEO_NUMBERS_SAFARI_01": {
    "id": "VIDEO_NUMBERS_SAFARI_01",
    "category": "VIDEOS",
    "prompt": "Create a bright low-poly jungle with a friendly plush-like lion.\nLearning beats:\n1) Lion passes 1 tree — number \"1\" appears floating above.\n2) Lion passes 2 bushes — number \"2\" appears.\n3) Lion passes 3 rocks — number \"3\" appears.\nNumbers should be large, bubbly 3D text with high contrast.\nMotion: gentle side-scrolling pan, no fast movement.\nStyle: warm, toylike, golden-hour lighting.\nDuration: 18-22 seconds."
  },
  "VIDEO_NUMBERS_BUBBLESORT_01": {
    "id": "VIDEO_NUMBERS_BUBBLESORT_01",
    "category": "VIDEOS",
    "prompt": "Visualize bubble sort using colored glass spheres of varying size arranged on a line.\nAnimate pairwise swaps from left to right in clear steps.\nEach swap should be smooth, countable, with a soft \"click\" visual (brief ring effect).\nAfter each pass, the largest settled element gets a subtle glow.\nStyle: minimalist geometry, high contrast, clean white background.\nCamera: orthographic frontal view for maximum clarity.\nDuration: 20-24 seconds."
  },
  "VIDEO_STORY_INTRO_01": {
    "id": "VIDEO_STORY_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create an invitation into the world of stories.\nScene beats:\n1) An old book lies closed on a wooden desk. Warm candlelight flickers.\n2) The book opens itself — pages flutter, golden light rises from the text.\n3) Miniature story worlds emerge from the pages: a tiny castle, a small dragon, a sailing ship.\n4) Camera rises through the emerging world until it fills the screen.\nStyle: warm, magical realism — grounded but wonder-filled.\nPalette: amber-400, rose-400, warm whites, parchment tones.\nCamera: close to medium, slow rise.\nDuration: 22-26 seconds."
  },
  "VIDEO_STORY_QUILL_01": {
    "id": "VIDEO_STORY_QUILL_01",
    "category": "VIDEOS",
    "prompt": "A floating quill writes on parchment in mid-air.\nAs words form, they spring to life as miniature golden constructs:\n- \"castle\" becomes a tiny castle\n- \"dragon\" becomes a small friendly dragon\n- \"river\" becomes a flowing ribbon of water\nVisual priority: the transition from ink strokes to imagined reality.\nLighting: warm study-lamp ambience, no harsh shadows.\nCamera: close framing on the writing, medium pull-back for reveals.\nDuration: 20-24 seconds."
  },
  "VIDEO_STORY_SHAPES_01": {
    "id": "VIDEO_STORY_SHAPES_01",
    "category": "VIDEOS",
    "prompt": "First-person exploration of a playroom with a magnifying tool.\nAs the tool hovers over objects:\n- Clock face highlights as a glowing circle\n- Window pane highlights as a glowing square\n- Pizza slice highlights as a glowing triangle\nEach shape label appears briefly in clean sans-serif text.\nStyle: colorful mystery-adventure tone, playful and safe, detective vibe.\nCamera: slow handheld-like glide with very low shake.\nDuration: 20-24 seconds."
  },
  "VIDEO_WORLD_INTRO_01": {
    "id": "VIDEO_WORLD_INTRO_01",
    "category": "VIDEOS",
    "prompt": "Create a journey across civilizations and landscapes.\nScene beats:\n1) A spinning globe slows and focuses on a point.\n2) Zoom into that point — ancient architecture emerges (stylized, not photorealistic).\n3) Time accelerates: the same location transforms through eras (ancient -> medieval -> modern).\n4) Camera pulls back to the globe, now glowing with connection lines between cities.\nStyle: warm documentary aesthetic, respectful of all cultures shown.\nPalette: emerald-400, amber-400, earth tones.\nCamera: globe zoom-in, time-lapse, globe pull-back — continuous flow.\nDuration: 24-28 seconds."
  },
  "VIDEO_WORLD_ROME_01": {
    "id": "VIDEO_WORLD_ROME_01",
    "category": "VIDEOS",
    "prompt": "Generate a historical atmosphere of the Roman Senate chamber.\nEmphasize architecture scale: tall columns, vaulted ceiling, natural sunlight shafts.\nDust motes dance in light beams. Calm ambient crowd motion in background.\nCharacters should remain stylized (slightly geometric) to avoid uncanny valley.\nTone: respectful, documentary-like, informative — not glorifying conquest.\nCamera: slow forward track from entrance to central floor.\nDuration: 20-25 seconds."
  },
  "VIDEO_WORLD_CYBERETHICS_01": {
    "id": "VIDEO_WORLD_CYBERETHICS_01",
    "category": "VIDEOS",
    "prompt": "Create a stylized digital city where avatars walk along data pathways.\nScene beats:\n1) Bright, orderly digital city with friendly avatar pedestrians.\n2) A fork appears in the path — one side bright and cooperative, the other glitchy and chaotic.\n3) An avatar pauses, considers, and chooses the safe/bright path.\n4) The chosen path lights up brighter, the glitchy path fades.\nGoal: represent online ethics and responsible digital choices using visual metaphor.\nStyle: futuristic but warm, accessible — not dystopian or threatening.\nDuration: 22-28 seconds."
  },
  "VIDEO_SHARED_COLORMIX_01": {
    "id": "VIDEO_SHARED_COLORMIX_01",
    "category": "VIDEOS",
    "prompt": "Macro-style animation of red and blue paint blobs moving in zero gravity.\nWhen they merge, they form a vivid purple swirl with soft particle trails.\nFocus on smooth fluid blending and visual satisfaction.\nStyle: glossy liquid simulation with clean lighting, high-gloss surfaces.\nDuration: 16-20 seconds, loop-capable ending."
  },
  "VIDEO_SHARED_LOGICGATE_01": {
    "id": "VIDEO_SHARED_LOGICGATE_01",
    "category": "VIDEOS",
    "prompt": "Visualize an AND gate with two streams of blue light entering a central junction.\nIf both streams arrive together, output becomes bright gold.\nIf one stream is missing, output fades softly to nothing.\nDesign: clean white environment, minimal geometry, maximum instructional clarity.\nCamera: mostly locked with slight push-in on successful output.\nDuration: 18-22 seconds."
  },
  "VIDEO_BG_TREE_01": {
    "id": "VIDEO_BG_TREE_01",
    "category": "VIDEOS",
    "prompt": "A subtle forest canopy with light filtering through leaves.\nVery slow leaf sway, occasional particle drift (pollen/dust motes).\nNo focal subject — pure ambient atmosphere.\nPalette: emerald-400, soft greens, dappled warm light.\nDuration: 10 seconds, seamless loop.\nCamera: locked, very slight breathing zoom (< 2% scale)."
  },
  "VIDEO_BG_OCEAN_01": {
    "id": "VIDEO_BG_OCEAN_01",
    "category": "VIDEOS",
    "prompt": "Underwater scene with soft caustic light patterns on a sandy floor.\nOccasional small fish silhouette drifts across. Gentle particle float (bubbles).\nNo focal subject — pure ambient.\nPalette: sky-400, teal-500, deep blue.\nDuration: 10 seconds, seamless loop.\nCamera: locked, very subtle drift."
  },
  "VIDEO_BG_SPACE_01": {
    "id": "VIDEO_BG_SPACE_01",
    "category": "VIDEOS",
    "prompt": "Slow star field with distant nebula color. Very gentle particle drift.\nNo planets or focal objects — just the quiet vastness of space.\nPalette: violet-400, deep black, subtle warm highlights.\nDuration: 10 seconds, seamless loop.\nCamera: locked with imperceptible slow rotation."
  },
  "VIDEO_BG_NUMBERS_01": {
    "id": "VIDEO_BG_NUMBERS_01",
    "category": "VIDEOS",
    "prompt": "Abstract floating number digits and mathematical symbols drifting slowly in space.\nVery low opacity, out of focus, non-distracting.\nPalette: amber-400, warm white, soft cream background.\nDuration: 10 seconds, seamless loop.\nCamera: locked."
  },
  "VIDEO_BG_STORY_01": {
    "id": "VIDEO_BG_STORY_01",
    "category": "VIDEOS",
    "prompt": "Parchment texture with very subtle ink blots that slowly bloom and fade.\nWarm candlelight flicker on edges. No text, no objects — pure atmosphere.\nPalette: rose-400, amber, parchment tones.\nDuration: 10 seconds, seamless loop.\nCamera: locked."
  },
  "VIDEO_BG_WORLD_01": {
    "id": "VIDEO_BG_WORLD_01",
    "category": "VIDEOS",
    "prompt": "Slowly rotating stylized globe with soft connection lines pulsing between points.\nLow opacity, non-distracting background.\nPalette: emerald-400, earth tones, warm highlights.\nDuration: 10 seconds, seamless loop.\nCamera: locked with very slow globe rotation."
  }
};

export function getPrompt(id: string): string | undefined {
  return MEDIA_PROMPTS[id]?.prompt;
}

export function getPromptsByCategory(category: string): MediaPrompt[] {
  return Object.values(MEDIA_PROMPTS).filter(p => p.category === category);
}
